### ISSUE TITLE
Browser crash with 'x^' in function plotter

### ISSUE THREAD

**Issue by appeye** [jsxgraph/jsxgraph#105]
Hey, 
I've been experimenting with JSX Graph a bit the past few weeks and I am very impressed by the possibilities!

I do have a little issue when it comes to building with  functiongraphs.
I've made a function plotter like the one from this example:
http://jsxgraph.uni-bayreuth.de/wiki/index.php/Even_simpler_function_plotter

I'm using JS Bin with Auto update and noticed that the browser kept crashing when i was typing some functions. The crash occurs when you type  x^     (wanting to type for example x^3).

Turning off auto-update and typing it x^3 and running manually works fine but crashes if you type only x^.
I thought this had to do with JS Bin but then I noticed the same problem in the function plotting example linked above. typing only x^ and clicking 'plot' will cause a crash.

This issue becomes very frustrating in JS Bin with autoupdates because you might lose your work because of the crashes.

Any ideas ?
Thanks,

Appe

**Comment by pgonzbecer** [comment]
A good idea would be to try-catch it's evaluation on it's update. So something like:

```
try {
  eval("function(x) { return "+equation+"; }"); // equation is in js math, not ascii math
  // code
} catch(e) { console.log(e); }
```

**Comment by migerh** [comment]
Thanks for the suggestion, but that won't help. I just found the bug. Just as I suspected it's caused by an endless loop. But the loop is not caused by JessieCode or jison (the parser generator we use for jessiecode). It's caused in parser/geonext.js.
