### ISSUE TITLE
Ask for help to update jsxgraph on cdnjs

### ISSUE THREAD

**Issue by PeterDaveHello** [jsxgraph/jsxgraph#126]
Hi there, I'm Peter from cdnjs, I wanna update jsxgraph on cdnjs to latest, but don't know what files to include, and as https://github.com/cdnjs/cdnjs/issues/3638 said, we want to setup auto-update for every lib, would you please help us to apply it on jsxgraph? Thanks.

**Comment by alfredwassermann** [comment]
Dear Peter, thank you very much for doing this valuable work!
The JSXGraph files to be imported are 
geogebra.min.js, intergeo.min.js, sketch.min.js, geonext.min.js, jsxgraphcore.js

What can I do to support auto-update?

Best wishes,
Alfred

**Comment by PeterDaveHello** [comment]
Thanks for your prompt reply, would you please tell me where do you put these files? We need pre-built files in the repository, and we use git's tag to recognize different versions, you can send a PR to cdnjs or just tell me the path of files, I am not sure if I missed something but I didn't find them in repository, is it necessary to build it by myself? thanks.

**Comment by alfredwassermann** [comment]
I just added the files, they are in the "distrib" folder now.
Does it mean, when I tag a new version (and only then) the auto update is triggered?

**Comment by PeterDaveHello** [comment]
In fact, auto-update will run in a certain period, and I'll confirm the update result, then commit it.

**Comment by PeterDaveHello** [comment]
Hi @alfredwassermann, I found that the structure in that dir is very different with current cdnjs, but I have no idea how to make sure the correctness, would you please do me a favor to take a look at it?

jsxgraph on cdnjs:
https://cdnjs.com/libraries/jsxgraph

Thanks a lot.

**Comment by alfredwassermann** [comment]
Dear Peter, yes, it is different.  To make the update process more stable, I created a new directory "update_cdnjs" which will contain the files which should be updated by cdnjs.
Is this ok?
Best wishes,
Alfred

**Comment by PeterDaveHello** [comment]
HI @alfredwassermann,

WOW, thanks! 

Do you have a schedule for next release? I can't wait for it, ha!

**Comment by alfredwassermann** [comment]
Hi Peter,
good to hear that it works now. 
Please forgive me my ignorance, but what steps have to be done from my side for an (auto-)update?
Do I still have to update the package.js file in my fork of cdnjs and send a pull request?

Best wishes,
Alfred

**Comment by PeterDaveHello** [comment]
Hi @alfredwassermann,

Just add tag for the new releases, and make sure this structure exist properly, then our updater will grab the files on this repo, thanks.

Regards,
Peter
