### ISSUE TITLE
GeonextParser.geonext2JS not working as expected after updating to the newest version

### ISSUE THREAD

**Issue by shangsunset** [jsxgraph/jsxgraph#133]
Hi,
with my old version(90), using GeonextParser.geonext2JS would translate `(x + y)^n` to `JXG.Math.pow((x+y), n)`. but after updating to the newest version(99.3), it is only translated to `pow((x+y), n)`, which yields `pow` is undefined error. is there a solution for this? or there is a new way to do this now? thanks.

**Comment by migerh** [comment]
Hi,

yes, the geonext2JS() function no longer outputs JavaScript but JessieCode instead. Depending on what you want to do with the output you might want to take a look at ```JXG.createFunction()```:

http://jsfiddle.net/migerh/d4y9Ldk6/

Here's what the reference has to say about it:

http://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.html#.createFunction


michael

**Comment by shangsunset** [comment]
@migerh perfect. thats just what i need! thanks! one more question about the new version. after the update, the control panel became like this
![screen shot 2015-03-16 at 4 19 47 pm](https://cloud.githubusercontent.com/assets/3700269/6675649/884002d0-cbf8-11e4-8053-e6809c6f4fe4.png)

why did this happen? is there a solution to it? thanks again.

**Comment by migerh** [comment]
@shangsunset try using utf-8 for pages serving jsxgraph constructions. Also see this thread in our Google Group for some more information:

https://groups.google.com/d/msg/jsxgraph/hpab9WlMBGA/foLzB535jMcJ

**Comment by shangsunset** [comment]
really appreciate your answers. 

quick question, when using Geonext2JS, 'board' param is optional. however, with createFunction, 'board' seems to be required. what should i do when i dont need to define a board. without passing 'board', i get 'Cannot read property 'snippet' of undefined' error. 

thanks again.

**Comment by migerh** [comment]
Because createFunction uses the JessieCode instance inside the board to resolve references to elements. You should be able to use your own instance without a board via

    JXG.createFunction(code, {jc: new JessieCode()}, params, true);

**Comment by shangsunset** [comment]
what should the instance be in this case? when i use {jc: new
JessieCode()}, i got JessieCode is not defined error. sorry, im still new
to jsxgraph.

**Comment by migerh** [comment]
Yeah, sorry, forgot the namespace:

    JXG.createFunction(code, {jc: new JXG.JessieCode()}, params, true);

**Comment by shangsunset** [comment]
hmm got "Cannot read property 'options' of null". this is what i put:   xeq
= JXG.createFunction(xeq, {jc: new JXG.JessieCode()},'x', true);
