### ISSUE TITLE
Invalid Jessie code generated with Empty point coordinates when dumping from nodejs

### ISSUE THREAD

**Issue by robotiko** [jsxgraph/jsxgraph#138]
Creating a board in nodeJS server,  calling JXG.Dump.toJessie(board)  with simple points,  generates invalid Jessie code where points have no coordinates. 

The only particular detail at server side is the board initialization with box= null  that is also at repo example (https://github.com/jsxgraph/jsxgraph/blob/master/examples/node/rendering.js ) and doesn't seems to give trouble with other JSXGraph functions. 

Snippet:

var JXG  = require("./lib/jsxgraphcore.js");
var board = JXG.JSXGraph.initBoard(null, {boundingbox: [0, 25, 25, 0]});

var A = board.create('point', [0.0, 0.0],{name:'A'});
var B = board.create('point', [1.0,0.0],{name:'B'});
var ref = board.create('segment', [A, B],{name:'Ref'});

console.log('Jessie:'+JXG.Dump.toJessie(board));

and the result is:

// A
s0 = point() <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , name: 'A', id: 'jxgBoard1P1'>> ;

// B
s1 = point() <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , name: 'B', id: 'jxgBoard1P3'>> ;

// Ref
s2 = segment(''jxgBoard1P1'', ''jxgBoard1P3'') <<strokecolor: '#0000ff', highlightstrokecolor: '#888888', fillcolor: 'none', highlightfillcolor: 'none', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, firstarrow: false, lastarrow: false, straightfirst: false, straightlast: false, withticks: false, point1: <<visible: false, withLabel: false, fixed: false, name: ''>> , point2: <<visible: false, withLabel: false, fixed: false, name: ''>> , ticks: <<drawLabels: true, label: <<offset: [4,-9]>> , drawZero: false, insertTicks: false, minTicksDistance: 50, minorHeight: 4, majorHeight: -1, minorTicks: 4, defaultDistance: 1, strokeOpacity: 0.3>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'top', offset: [10,10]>> , snapsizex: 1, snapsizey: 1, touchfirstpoint: false, touchlastpoint: false, name: 'Ref', id: 'jxgBoard1L5'>> ;
 
$board.setBoundingBox([0,25,25,0], true);

dumping in javascript has the same issue:
board.create("point", [], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"name":"A","id":"jxgBoard1P1"});
board.create("point", [], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"name":"B","id":"jxgBoard1P3"});
board.create("segment", ['jxgBoard1P1', 'jxgBoard1P3'], {"strokecolor":"#0000ff","highlightstrokecolor":"#888888","fillcolor":"none","highlightfillcolor":"none","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"firstarrow":false,"lastarrow":false,"straightfirst":false,"straightlast":false,"withticks":false,"point1":{"visible":false,"withLabel":false,"fixed":false,"name":""},"point2":{"visible":false,"withLabel":false,"fixed":false,"name":""},"ticks":{"drawLabels":true,"label":{"offset":[4,-9]},"drawZero":false,"insertTicks":false,"minTicksDistance":50,"minorHeight":4,"majorHeight":-1,"minorTicks":4,"defaultDistance":1,"strokeOpacity":0.3},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"top","offset":[10,10]},"snapsizex":1,"snapsizey":1,"touchfirstpoint":false,"touchlastpoint":false,"name":"Ref","id":"jxgBoard1L5"});

**Comment by migerh** [comment]
Thanks for reporting this, I just submitted a patch that should fix this problem.

**Comment by robotiko** [comment]
Just checked and is working.
Thanks
