### ISSUE TITLE
Invalid Jessie and JS code generated when dumping basic entities such as segments, circles and intersections

### ISSUE THREAD

**Issue by robotiko** [jsxgraph/jsxgraph#139]
Related to  #138.

It seems that Dump to Jessie is generating "unparseable" Jessie code.
It seems that entity names are "over quoted" among other failures. 

Using http://bin.sketchometry.com/  to validate the Jessie code, it fails in most items. 

Dumping to JS sometime generates good code and sometimes does the same. 

Attached example output from simple example in JS and  Jessie for the same working example.
(version: 0.99.4-dev to fix #138 )

JS:
board.create("point", [0, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"A","id":"jxgBoard1P1"});
board.create("point", [1, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"B","id":"jxgBoard1P3"});
board.create("segment", ['jxgBoard1P1', 'jxgBoard1P3'], {"strokecolor":"#0000ff","highlightstrokecolor":"#888888","fillcolor":"none","highlightfillcolor":"none","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"firstarrow":false,"lastarrow":false,"straightfirst":false,"straightlast":false,"withticks":false,"point1":{"visible":false,"withLabel":false,"fixed":false,"name":""},"point2":{"visible":false,"withLabel":false,"fixed":false,"name":""},"ticks":{"drawLabels":true,"label":{"offset":[4,-9]},"drawZero":false,"insertTicks":false,"minTicksDistance":50,"minorHeight":4,"majorHeight":-1,"minorTicks":4,"defaultDistance":1,"strokeOpacity":0.3},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"top","offset":[10,10]},"snapsizex":1,"snapsizey":1,"touchfirstpoint":false,"touchlastpoint":false,"name":"Ref","id":"jxgBoard1L5"});
board.create("circle", ['jxgBoard1P1'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C6","name":"k_{a}"});
board.create("circle", ['jxgBoard1P3'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C7","name":"k_{b}"});
board.create("intersection", ['jxgBoard1C6', 'jxgBoard1C7', 1, 0], {"strokecolor":"#ff0000","highlightstrokecolor":"#C3D9FF","fillcolor":"#ff0000","highlightfillcolor":"#EEEEEE","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"style":5,"face":"o","size":3,"showinfobox":true,"infoboxdigits":"auto","attractorunit":"user","attractordistance":0,"snapsizex":1,"snapsizey":1,"snaptopoints":false,"ignoredsnaptopoints":[],"id":"jxgBoard1P8","name":"name2"});
board.create("point", [0.005950000000000091, 0.9999822985933301], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"2","id":"jxgBoard1P10"});
board.create("circle", ['jxgBoard1P1'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C12","name":"k_{c}"});
board.create("circle", ['jxgBoard1P3'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C13","name":"k_{d}"});
board.create("intersection", ['jxgBoard1C12', 'jxgBoard1C13', 1, 0], {"strokecolor":"#ff0000","highlightstrokecolor":"#C3D9FF","fillcolor":"#ff0000","highlightfillcolor":"#EEEEEE","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"style":5,"face":"o","size":3,"showinfobox":true,"infoboxdigits":"auto","attractorunit":"user","attractordistance":0,"snapsizex":1,"snapsizey":1,"snaptopoints":false,"ignoredsnaptopoints":[],"id":"jxgBoard1P14","name":"name3"});
board.create("point", [0.9940499999999999, 0.9999822985933301], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"3","id":"jxgBoard1P16"});
board.create("polygon", ['jxgBoard1P1', 'jxgBoard1P10', 'jxgBoard1P16', 'jxgBoard1P3', 'jxgBoard1P1'], {"strokecolor":"blue","highlightstrokecolor":"#C3D9FF","strokeopacity":0.6,"highlightstrokeopacity":1,"strokewidth":5,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"borders":{"withLabel":false,"strokeWidth":1,"highlightStrokeWidth":1,"layer":5,"label":{"position":"top"}},"vertices":{"layer":9,"withLabel":false,"name":"","strokeColor":"#ff0000","fillColor":"#ff0000","fixed":false},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[0,0]},"id":"jxgBoard1Py22","name":"P_{a}","lines":{"ids":["jxgBoard1L21","jxgBoard1L18","jxgBoard1L19","jxgBoard1L20"],"colors":["#0000ff","#0000ff","#0000ff","#0000ff"]}});
$board.setBoundingBox([-2.5,3.49998229859333,3.5000000000000004,-2.5000177014066702], true);

Jessie:// A
s0 = point(0, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'A', id: 'jxgBoard1P1'>> ;

// B
s1 = point(1, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'B', id: 'jxgBoard1P3'>> ;

// Ref
s2 = segment(''jxgBoard1P1'', ''jxgBoard1P3'') <<strokecolor: '#0000ff', highlightstrokecolor: '#888888', fillcolor: 'none', highlightfillcolor: 'none', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, firstarrow: false, lastarrow: false, straightfirst: false, straightlast: false, withticks: false, point1: <<visible: false, withLabel: false, fixed: false, name: ''>> , point2: <<visible: false, withLabel: false, fixed: false, name: ''>> , ticks: <<drawLabels: true, label: <<offset: [4,-9]>> , drawZero: false, insertTicks: false, minTicksDistance: 50, minorHeight: 4, majorHeight: -1, minorTicks: 4, defaultDistance: 1, strokeOpacity: 0.3>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'top', offset: [10,10]>> , snapsizex: 1, snapsizey: 1, touchfirstpoint: false, touchlastpoint: false, name: 'Ref', id: 'jxgBoard1L5'>> ;

// k_{a}
s3 = circle(''jxgBoard1P1'') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C6', name: 'k_{a}'>> ;

// k_{b}
s4 = circle(''jxgBoard1P3'') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C7', name: 'k_{b}'>> ;

// name2
s5 = intersection(''jxgBoard1C6'', ''jxgBoard1C7'', 1, 0) <<strokecolor: '#ff0000', highlightstrokecolor: '#C3D9FF', fillcolor: '#ff0000', highlightfillcolor: '#EEEEEE', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , style: 5, face: 'o', size: 3, showinfobox: true, infoboxdigits: 'auto', attractorunit: 'user', attractordistance: 0, snapsizex: 1, snapsizey: 1, snaptopoints: false, ignoredsnaptopoints: [], id: 'jxgBoard1P8', name: 'name2'>> ;

// 2
s6 = point(0.005950000000000091, 0.9999822985933301) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: '2', id: 'jxgBoard1P10'>> ;

// k_{c}
s7 = circle(''jxgBoard1P1'') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C12', name: 'k_{c}'>> ;

// k_{d}
s8 = circle(''jxgBoard1P3'') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C13', name: 'k_{d}'>> ;

// name3
s9 = intersection(''jxgBoard1C12'', ''jxgBoard1C13'', 1, 0) <<strokecolor: '#ff0000', highlightstrokecolor: '#C3D9FF', fillcolor: '#ff0000', highlightfillcolor: '#EEEEEE', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , style: 5, face: 'o', size: 3, showinfobox: true, infoboxdigits: 'auto', attractorunit: 'user', attractordistance: 0, snapsizex: 1, snapsizey: 1, snaptopoints: false, ignoredsnaptopoints: [], id: 'jxgBoard1P14', name: 'name3'>> ;

// 3
s10 = point(0.9940499999999999, 0.9999822985933301) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: '3', id: 'jxgBoard1P16'>> ;

// P_{a}
s11 = polygon('jxgBoard1P1', 'jxgBoard1P10', 'jxgBoard1P16', 'jxgBoard1P3', 'jxgBoard1P1') <<strokecolor: 'blue', highlightstrokecolor: '#C3D9FF', strokeopacity: 0.6, highlightstrokeopacity: 1, strokewidth: 5, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, borders: <<withLabel: false, strokeWidth: 1, highlightStrokeWidth: 1, layer: 5, label: <<position: 'top'>> >> , vertices: <<layer: 9, withLabel: false, name: '', strokeColor: '#ff0000', fillColor: '#ff0000', fixed: false>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [0,0]>> , id: 'jxgBoard1Py22', name: 'P_{a}', lines: <<ids: ['jxgBoard1L21','jxgBoard1L18','jxgBoard1L19','jxgBoard1L20'], colors: ['#0000ff','#0000ff','#0000ff','#0000ff']>> >> ;

$board.setBoundingBox([-2.5,3.49998229859333,3.5000000000000004,-2.5000177014066702], true);

I can provide additional more complex examples where names can be over tagged up to 4 times that shows JS failures too.  Some real outputs:

board.create("circle", [''''jxgBoard1P3''''], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C13","name":"k_{d}"});
board.create("point", [4, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"B","id":"jxgBoard1P26"});
board.create("segment", ['jxgBoard1P24', 'jxgBoard1P26'], {"strokecolor":"#0000ff","highlightstrokecolor":"#888888","fillcolor":"none","highlightfillcolor":"none","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"firstarrow":false,"lastarrow":false,"straightfirst":false,"straightlast":false,"withticks":false,"point1":{"visible":false,"withLabel":false,"fixed":false,"name":""},"point2":{"visible":false,"withLabel":false,"fixed":false,"name":""},"ticks":{"drawLabels":true,"label":{"offset":[4,-9]},"drawZero":false,"insertTicks":false,"minTicksDistance":50,"minorHeight":4,"majorHeight":-1,"minorTicks":4,"defaultDistance":1,"strokeOpacity":0.3},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"top","offset":[10,10]},"snapsizex":1,"snapsizey":1,"touchfirstpoint":false,"touchlastpoint":false,"name":"Ref","id":"jxgBoard1L28"});
board.create("circle", ['jxgBoard1P24'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C29","name":"k_{e}"});
board.create("circle", ['jxgBoard1P26'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C30","name":"k_{f}"});
board.create("intersection", ['jxgBoard1C29', 'jxgBoard1C30', 1, 0], {"strokecolor":"#ff0000","highlightstrokecolor":"#C3D9FF","fillcolor":"#ff0000","highlightfillcolor":"#EEEEEE","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":false,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"style":5,"face":"o","size":3,"showinfobox":true,"infoboxdigits":"auto","attractorunit":"user","attractordistance":0,"snapsizex":1,"snapsizey":1,"snaptopoints":false,"ignoredsnaptopoints":[],"id":"jxgBoard1P31","name":"name1"});

and jessie 

// 2
s6 = point(0.005950000000000091, 0.9999822985933301) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: '2', id: 'jxgBoard1P10'>> ;

// k_{c}
s7 = circle('''''jxgBoard1P1''''') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C12', name: 'k_{c}'>> ;

// k_{d}
s8 = circle('''''jxgBoard1P3''''') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C13', name: 'k_{d}'>> ;

// name3
s9 = intersection('''''jxgBoard1C12''''', '''''jxgBoard1C13''''', 1, 0) <<strokecolor: '#ff0000', highlightstrokecolor: '#C3D9FF', fillcolor: '#ff0000', highlightfillcolor: '#EEEEEE', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: false, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , style: 5, face: 'o', size: 3, showinfobox: true, infoboxdigits: 'auto', attractorunit: 'user', attractordistance: 0, snapsizex: 1, snapsizey: 1, snaptopoints: false, ignoredsnaptopoints: [], id: 'jxgBoard1P14', name: 'name3'>> ;

**Comment by alfredwassermann** [comment]
This issues are resolved in commit 1aa1f146fcdda1bf39ed0f278720dfb5f73872d6 and before.
