### ISSUE TITLE
Circle Dump using JXG.Dump.toJavaScript and JXG.Dump.toJessie  generate invalid output

### ISSUE THREAD

**Issue by robotiko** [jsxgraph/jsxgraph#141]
Dumping a circle, generates invalid output without without circle center coordinate neither radius
Simplest  example:

var board = JXG.JSXGraph.initBoard('box');
var A = board.create('point', [0.0, 0.0], {name: 'A'});
var circleA = board.create('circle', [A, 5]);

console.log('JS:'+JXG.Dump.toJavaScript(board));
console.log('Jessie:' + JXG.Dump.toJessie(board));

--------------------

Console output 
JS:
board.create("point", [0, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"A","id":"jxgBoard1P1"});
board.create("circle", ['jxgBoard1P1'], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C3","name":"k_{a}"});
$board.setBoundingBox([-5,5,5,-5], true);

Jessie:
// A
s0 = point(0, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'A', id: 'jxgBoard1P1'>> ;

// k_{a}
s1 = circle(''jxgBoard1P1'') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C3', name: 'k_{a}'>> ;

$board.setBoundingBox([-5,5,5,-5], true);

**Comment by alfredwassermann** [comment]
Fixed by 718dcdd8a395b7510321b3693e3c1e9c1daf6874
But the fix works only if radius is given by a number, not by functions.

**Comment by robotiko** [comment]
Thanks alfredwassermann
I will check it with nightbuild. 
Fast looking at the code, it might also fix #142?

**Comment by robotiko** [comment]
Checked and Working. 
Thanks!
