### ISSUE TITLE
Circle, segment and intersect Dump generate incorrect dump with extra quotes in referred element names if board is dumped more than one time

### ISSUE THREAD

**Issue by robotiko** [jsxgraph/jsxgraph#142]
Simple example with all  entities involved:
Everytime we make a  board Dump call (happens with Jessie and Javascript), the referenced element names used creating a circle a segment or an intersection, get added a quote.  
After first call, this generates incorrect code. 
 
var board = JXG.JSXGraph.initBoard('box');

var A = board.create('point', [0.0, 0.0], {name: 'A'});
var B = board.create('point', [5, 0.0], {name: 'B'});
var segment = board.create('segment', [A, B],{name:'Ref'});
var circleA = board.create('circle', [A, 5]);
var circleB = board.create('circle', [B, 3]);
var intersection = board.create('intersection', [circleA, circleB, 1]);

//Single quote
console.log('Jessie:' + JXG.Dump.toJessie(board));
//Double quote
console.log('JS:'+JXG.Dump.toJavaScript(board));
//Three quotes
console.log('Jessie:' + JXG.Dump.toJessie(board));
//Four quotes
console.log('JS:'+JXG.Dump.toJavaScript(board));

Console output: 

Jessie:
// A
s0 = point(0, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'A', id: 'jxgBoard1P1'>> ;
// B
s1 = point(5, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'B', id: 'jxgBoard1P3'>> ;
// Ref
s2 = segment('jxgBoard1P1', 'jxgBoard1P3') <<strokecolor: '#0000ff', highlightstrokecolor: '#888888', fillcolor: 'none', highlightfillcolor: 'none', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, firstarrow: false, lastarrow: false, straightfirst: false, straightlast: false, withticks: false, point1: <<visible: false, withLabel: false, fixed: false, name: ''>> , point2: <<visible: false, withLabel: false, fixed: false, name: ''>> , ticks: <<drawLabels: true, label: <<offset: [4,-9]>> , drawZero: false, insertTicks: false, minTicksDistance: 50, minorHeight: 4, majorHeight: -1, minorTicks: 4, defaultDistance: 1, strokeOpacity: 0.3>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'top', offset: [10,10]>> , snapsizex: 1, snapsizey: 1, touchfirstpoint: false, touchlastpoint: false, name: 'Ref', id: 'jxgBoard1L5'>> ;
// k_{a}
s3 = circle('jxgBoard1P1') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C6', name: 'k_{a}'>> ;
// k_{b}
s4 = circle('jxgBoard1P3') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C7', name: 'k_{b}'>> ;
// C
s5 = intersection('jxgBoard1C6', 'jxgBoard1C7', 1, 0) <<strokecolor: '#ff0000', highlightstrokecolor: '#C3D9FF', fillcolor: '#ff0000', highlightfillcolor: '#EEEEEE', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , style: 5, face: 'o', size: 3, showinfobox: true, infoboxdigits: 'auto', attractorunit: 'user', attractordistance: 0, snapsizex: 1, snapsizey: 1, snaptopoints: false, ignoredsnaptopoints: [], id: 'jxgBoard1P8', name: 'C'>> ;
$board.setBoundingBox([-5,5,5,-5], true);

JS:
board.create("point", [0, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"A","id":"jxgBoard1P1"});
board.create("point", [5, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"B","id":"jxgBoard1P3"});
board.create("segment", [''jxgBoard1P1'', ''jxgBoard1P3''], {"strokecolor":"#0000ff","highlightstrokecolor":"#888888","fillcolor":"none","highlightfillcolor":"none","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"firstarrow":false,"lastarrow":false,"straightfirst":false,"straightlast":false,"withticks":false,"point1":{"visible":false,"withLabel":false,"fixed":false,"name":""},"point2":{"visible":false,"withLabel":false,"fixed":false,"name":""},"ticks":{"drawLabels":true,"label":{"offset":[4,-9]},"drawZero":false,"insertTicks":false,"minTicksDistance":50,"minorHeight":4,"majorHeight":-1,"minorTicks":4,"defaultDistance":1,"strokeOpacity":0.3},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"top","offset":[10,10]},"snapsizex":1,"snapsizey":1,"touchfirstpoint":false,"touchlastpoint":false,"name":"Ref","id":"jxgBoard1L5"});
board.create("circle", [''jxgBoard1P1''], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C6","name":"k_{a}"});
board.create("circle", [''jxgBoard1P3''], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C7","name":"k_{b}"});
board.create("intersection", [''jxgBoard1C6'', ''jxgBoard1C7'', 1, 0], {"strokecolor":"#ff0000","highlightstrokecolor":"#C3D9FF","fillcolor":"#ff0000","highlightfillcolor":"#EEEEEE","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"style":5,"face":"o","size":3,"showinfobox":true,"infoboxdigits":"auto","attractorunit":"user","attractordistance":0,"snapsizex":1,"snapsizey":1,"snaptopoints":false,"ignoredsnaptopoints":[],"id":"jxgBoard1P8","name":"C"});
$board.setBoundingBox([-5,5,5,-5], true);

Jessie:
// A
s0 = point(0, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'A', id: 'jxgBoard1P1'>> ;
// B
s1 = point(5, 0) <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, highlightstrokewidth: 2, fixed: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, scalable: true, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , ignoredsnaptopoints: [], name: 'B', id: 'jxgBoard1P3'>> ;
// Ref
s2 = segment('''jxgBoard1P1''', '''jxgBoard1P3''') <<strokecolor: '#0000ff', highlightstrokecolor: '#888888', fillcolor: 'none', highlightfillcolor: 'none', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, firstarrow: false, lastarrow: false, straightfirst: false, straightlast: false, withticks: false, point1: <<visible: false, withLabel: false, fixed: false, name: ''>> , point2: <<visible: false, withLabel: false, fixed: false, name: ''>> , ticks: <<drawLabels: true, label: <<offset: [4,-9]>> , drawZero: false, insertTicks: false, minTicksDistance: 50, minorHeight: 4, majorHeight: -1, minorTicks: 4, defaultDistance: 1, strokeOpacity: 0.3>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'top', offset: [10,10]>> , snapsizex: 1, snapsizey: 1, touchfirstpoint: false, touchlastpoint: false, name: 'Ref', id: 'jxgBoard1L5'>> ;
// k_{a}
s3 = circle('''jxgBoard1P1''') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C6', name: 'k_{a}'>> ;
// k_{b}
s4 = circle('''jxgBoard1P3''') <<strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: false, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, center: <<visible: false, withLabel: false, fixed: false, name: ''>> , label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , id: 'jxgBoard1C7', name: 'k_{b}'>> ;
// C
s5 = intersection('''jxgBoard1C6''', '''jxgBoard1C7''', 1, 0) <<strokecolor: '#ff0000', highlightstrokecolor: '#C3D9FF', fillcolor: '#ff0000', highlightfillcolor: '#EEEEEE', strokeopacity: 1, highlightstrokeopacity: 1, fillopacity: 1, highlightfillopacity: 1, strokewidth: 2, highlightstrokewidth: 2, fixed: false, withlabel: true, visible: true, priv: false, dash: 0, trace: false, highlight: true, snaptogrid: false, scalable: true, draft: false, islabel: false, label: <<strokeColor: 'black', strokeOpacity: 1, highlightStrokeOpacity: 0.666666, highlightStrokeColor: 'black', fixed: true, position: 'urt', offset: [10,10]>> , style: 5, face: 'o', size: 3, showinfobox: true, infoboxdigits: 'auto', attractorunit: 'user', attractordistance: 0, snapsizex: 1, snapsizey: 1, snaptopoints: false, ignoredsnaptopoints: [], id: 'jxgBoard1P8', name: 'C'>> ;
$board.setBoundingBox([-5,5,5,-5], true);

JS:
board.create("point", [0, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"A","id":"jxgBoard1P1"});
board.create("point", [5, 0], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"highlightstrokewidth":2,"fixed":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"scalable":true,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"ignoredsnaptopoints":[],"name":"B","id":"jxgBoard1P3"});
board.create("segment", [''''jxgBoard1P1'''', ''''jxgBoard1P3''''], {"strokecolor":"#0000ff","highlightstrokecolor":"#888888","fillcolor":"none","highlightfillcolor":"none","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"firstarrow":false,"lastarrow":false,"straightfirst":false,"straightlast":false,"withticks":false,"point1":{"visible":false,"withLabel":false,"fixed":false,"name":""},"point2":{"visible":false,"withLabel":false,"fixed":false,"name":""},"ticks":{"drawLabels":true,"label":{"offset":[4,-9]},"drawZero":false,"insertTicks":false,"minTicksDistance":50,"minorHeight":4,"majorHeight":-1,"minorTicks":4,"defaultDistance":1,"strokeOpacity":0.3},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"top","offset":[10,10]},"snapsizex":1,"snapsizey":1,"touchfirstpoint":false,"touchlastpoint":false,"name":"Ref","id":"jxgBoard1L5"});
board.create("circle", [''''jxgBoard1P1''''], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C6","name":"k_{a}"});
board.create("circle", [''''jxgBoard1P3''''], {"strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":false,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"center":{"visible":false,"withLabel":false,"fixed":false,"name":""},"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"id":"jxgBoard1C7","name":"k_{b}"});
board.create("intersection", [''''jxgBoard1C6'''', ''''jxgBoard1C7'''', 1, 0], {"strokecolor":"#ff0000","highlightstrokecolor":"#C3D9FF","fillcolor":"#ff0000","highlightfillcolor":"#EEEEEE","strokeopacity":1,"highlightstrokeopacity":1,"fillopacity":1,"highlightfillopacity":1,"strokewidth":2,"highlightstrokewidth":2,"fixed":false,"withlabel":true,"visible":true,"priv":false,"dash":0,"trace":false,"highlight":true,"snaptogrid":false,"scalable":true,"draft":false,"islabel":false,"label":{"strokeColor":"black","strokeOpacity":1,"highlightStrokeOpacity":0.666666,"highlightStrokeColor":"black","fixed":true,"position":"urt","offset":[10,10]},"style":5,"face":"o","size":3,"showinfobox":true,"infoboxdigits":"auto","attractorunit":"user","attractordistance":0,"snapsizex":1,"snapsizey":1,"snaptopoints":false,"ignoredsnaptopoints":[],"id":"jxgBoard1P8","name":"C"});
$board.setBoundingBox([-5,5,5,-5], true);

**Comment by alfredwassermann** [comment]
Fixed by commit 7ca60acc3ea18392f2a0fe35c529b08d6e91bd82
