### ISSUE TITLE
Throw error using the JXG.Math.Geometry.signedPolygon method.

### ISSUE THREAD

**Issue by vinimdocarmo** [jsxgraph/jsxgraph#148]
I'm trying to get a area of a polygon, but it throws an error. Check it out the live demo: http://jsbin.com/pamiquhugi/1/edit?js,console,output

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. 
The bug had already been fixed before. Nevertheless, the function signedPolygon() still had another bug and computed only half of the true value. This is fixed now in the next nightly build.
Thank you very much,
Alfred

**Comment by vinimdocarmo** [comment]
The problem keeps happening. 

It seems that the `Expect` param that the [math/geometry](https://github.com/jsxgraph/jsxgraph/blob/master/src/math/geometry.js#L52) module depends on is `undefined`. So, when the method `signedPolygon` try to use the method `Expect.each` it thows a `Uncaught TypeError: Cannot read property 'each' of undefined`.

**Comment by alfredwassermann** [comment]
Indeed! The problem was a cyclic dependency of the modules, see #143.

**Comment by alfredwassermann** [comment]
Fixed by e79ae97

**Comment by vinimdocarmo** [comment]
:grin::v:
