### ISSUE TITLE
How can I prevent some object from selection?

### ISSUE THREAD

**Issue by rhcad** [jsxgraph/jsxgraph#151]
I'm developing a [geometry GUI][GUI] to show properties of the current object via `board.downObjects[0]`. I want to prevent some locked and visible object from selection, but there's a problem as the following.

In `Board.initMoveObject` function, all objects with hasPoint function can be called regardless it's `fixed` property is true, so it's difficult to select only one specific object or prevent some object from selection when multiple objects can be selected via hasPoint. For example:

1. Polygon whose `hasInnerPoints` property is true. It has a priority over the inner lines.
2. Label text when board's `ignoreLabels` property is false. It has a priority over the anchor point.

So, which way is best choice?

1. Add `unhittable` property for geometry element and check it in `Board.initMoveObject` function.

2. Add a filter function parameter for board, so `Board.initMoveObject` can pass each element to user app to prevent some object from selection.

3. Remove some element of `board.downObjects` when `down` event occurs. JSXGraph need't be changed in this way.

Hope to get your agreeement and support.

Best regards!
Zhang Yungui

[GUI]: http://rhcad.github.io/geomedit

**Comment by alfredwassermann** [comment]
Dear Zhang,
first of all, congrats to your application. It looks very promising.

My suggestion is that you do not access strictly `board.downObjects[0]`, but filter the `board.downObjects`array in your application. Are there any obstacles which prevent you for doing this?

Best wishes,
Alfred

**Comment by rhcad** [comment]
The `board.downObjects` array has usually one element after the `down` event occurs, so I do not need to filter the array in my app.

Now, I have used two methods which need not to change JSXGraph:

1. Check the type of object via `board.downObjects[0]` after the `down` event occurs. It's used in the properties page.

2. Implement object scanning function and custom filter function to pick up the ideal element with any coords. It's used in `perpendicular point` and `reflected point` commands.

**Comment by rhcad** [comment]
Thank you for your encouragement and help.
My app' code is [here](https://github.com/rhcad/geomedit). The project is under developing and It's license will be changed as MIT.
