### ISSUE TITLE
Need to change the result type of Board.zoomIn, zoomOut and zoom100.

### ISSUE THREAD

**Issue by rhcad** [jsxgraph/jsxgraph#152]
I noticed the diffrence between the result value (false) and the comment ('Reference to the board') of some functions of Board: zoomIn, zoomOut and zoom100, for example:

        /**...
         * @returns {JXG.Board} Reference to the board
         */
        zoomIn: function (x, y) {
            ...
            this.zoomX *= zX;
            this.zoomY *= zY;
            this.applyZoom();
            return false;
        }

The last two statements may be changed as `return this.applyZoom();` ?

Thanks!
Zhang Yungui

**Comment by migerh** [comment]
I'd suggest changing the documentation. The results were changed to prevent event bubbling in commit 860491cc4841.

**Comment by rhcad** [comment]
How to do for other more buttons? I think preventing event bubbling is view/HTML's task, for example: onclick="board.foobar() && 0".

I don't object to changing the documentation of the three functions.

**Comment by alfredwassermann** [comment]
OK, I agree that event bubbling should be the task of the button. It is changed now in the sources: The seven navigation functions return reference to board now (and bubbling is prevented where the button is created).
