### ISSUE TITLE
JXG.Board.I is undefined

### ISSUE THREAD

**Issue by hipersayanX** [jsxgraph/jsxgraph#153]
The method JXG.Board.I([a, b], f) (compute integral numerically) is documented [here](http://jsxgraph.uni-bayreuth.de/distrib/jsxgraph_refcard.pdf), but is undefined [here](http://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js).

**Comment by alfredwassermann** [comment]
Sorry, the JXG.Board.I() ha been removed with 0.99.7, see the [CHANGELOG](https://github.com/jsxgraph/jsxgraph/blob/master/CHANGELOG.md). The method has been moved to `JXG.Math.Numerics.I()`. 
Unfortunately, the reference card is hopelessly outdated.
