### ISSUE TITLE
Offset on the X axis on Firefox not used

### ISSUE THREAD

**Issue by nadenislamarre** [jsxgraph/jsxgraph#154]
When I create a X axis, the value X is not considered in the code bellow,
which make the label not visible is longer that 1 character.
The bug is visible at the address : http://nadenislamarre.free.fr/jsx/bug1.htm

xaxis = window.board.create('axis',
  	[xAxPt0,xAxPt1], {
  	needsRegularUpdate: false,
  	name:'Time',
  	withLabel: true,
  	label: {position: 'rt', offset: [X, 30]
     }
   })

**Comment by alfredwassermann** [comment]
This bug has already been fixed in the sources, probably with c5286ae3d420ea69226466d52167a929839ba1ff
Additionally, in the above mentioned online example the offset is positive in horizontal direction, but it should be negative (e.g. label: {position: 'rt', offset: [-30, 30]})
