### ISSUE TITLE
Fixed images draggable on Firefox

### ISSUE THREAD

**Issue by nadenislamarre** [jsxgraph/jsxgraph#155]
On Firefox (38.0.5), but not on Internet Explorer (11),

When creating an image such as :
  img = board.create('image',["uccellino.jpg", [0,0], [1,2]], { fixed: true, highlight: false });

The image is draggable while the documentation states that :

"Fixed:
If true the element is fixed and can not be dragged around. The element will be repositioned on zoom and moveOrigin events. "

The bug is in action here :
http://nadenislamarre.free.fr/jsx/bug2.htm

**Comment by alfredwassermann** [comment]
Sorry,but I can not reproduce this bug. Can you please provide more information? Are there any messages in the web console?

**Comment by nadenislamarre** [comment]
Perhaps it is wanted too.

but to reproduce :
- open the page in firefox
- left click on the eyes and keep the button pressed
- go in the url bar
- up the button
=> the image appears completly in firefox : the image has been dragged to the url bar

**Comment by alfredwassermann** [comment]
It looks like this is a feature of firefox, not a bug.
