### ISSUE TITLE
Internet Explorer 11 and mouse wheel

### ISSUE THREAD

**Issue by nadenislamarre** [jsxgraph/jsxgraph#156]
When creating a simple graph, like on http://nadenislamarre.free.fr/jsx/bug3.htm
The mouse wheel works correctly under Firefox.
It doesn't work under Internet Explorer 11.

The problem seems fixed when calling "regularly" addEventHandlers(). I write regularly because sometimes, it doesn't work again...

board = JXG.JSXGraph.initBoard('box', {axis:true,
      zoom: {
	  factorX:1.25,
	  factorY:1.25,
	  wheel:true,
	  needshift:false,
	  eps: 0.1
	 }
  })

**Comment by alfredwassermann** [comment]
This bug is due to the pointer events from Microsoft
