### ISSUE TITLE
How to move both objects which has same point, at the same time?

### ISSUE THREAD

**Issue by dineshi2it** [jsxgraph/jsxgraph#165]
// Created an arrow providing two points.
var A = board.create('point', [4.0, 2.0]);
var B = board.create('point', [1.0, 1.0]);
board.create('arrow', [A, B]);

// Created a line providing two points.
var C = board.create('point', [4.0, 2.0]);
var D = board.create('point', [6.0, 2.0]);
board.create('line', [C, D]);

Now both point A and C are same. When I move it, only C gets moved as it was created at last. Is there any chance of moving both objects(arrow & line) together when the common point(A,C) is moved?

**Comment by alfredwassermann** [comment]
Answered on stackoverflow: http://stackoverflow.com/questions/31964439/how-to-move-both-objects-which-has-same-point-at-the-same-time-in-jsxgraph/31965599#31965599
