### ISSUE TITLE
JSXGraph is not working in IE Edge (Windows 10)

### ISSUE THREAD

**Issue by jack-vo** [jsxgraph/jsxgraph#166]
Hi, I have been a big fan of JSXGraph for a long time and I think the whole library is fantastic. Great work :)

Apparently, after I upgrade my PC to Windows 10, I discover that JSXGraph is not working properly in IE Edge. I can see all the components like board, axis... rendered correctly but all the interactions like drag, drop, draw line, add point... are not working.

It would be great if you  can be address these issues as more and more people are upgrading to Windows 10.

Thank you very much.

Jack

**Comment by alfredwassermann** [comment]
Dear Jack,
thank you very much for reporting the problems with edge.
Is your screen a touch-device?
Best wishes,
Alfred

**Comment by alfredwassermann** [comment]
Dear Jack,
a quick test with a Windows 10 PC in our department showed no problems with JSXGraph and edge. Did you already try the construction on the JSXGraph homepage (http://jsxgraph.org)?
Best wishes,
Alfred

**Comment by jack-vo** [comment]
Thanks for the quick reply, Alfred. I really appreciate that.
After testing on http://jsxgraph.org I am very happy that jsxgraph works perfectly on Edge so it looks like the problem is on our end so thank you very much.
Really appreciate your support.

Best regards,
Jack
