### ISSUE TITLE
Axis labels are not at the right point

### ISSUE THREAD

**Issue by torbenz** [jsxgraph/jsxgraph#169]
Hi,

is it possible to fix the axis labels at the right place? (On the y-axis they are slightly below the the true value and on the x-axis they are slightly to the right of the the true value).

I want them to be directly on the grid.

Cheers!

**Comment by alfredwassermann** [comment]
You can use the attribute ticks.label.offset to fine tune the position of rhe axis ticks.
Here is an example:

    var xax = board.create('axis', [[0, 0], [1, 0]], { ticks: { label: { offset: [-2, -10] } } });
    var yax = board.create('axis', [[0, 0], [0, 1]], { ticks: { label: { offset: [10, -2] } } });
