### ISSUE TITLE
Moodle plugin, issue with Moodle quiz.

### ISSUE THREAD

**Issue by aharjula** [jsxgraph/jsxgraph#171]
Hi,

An issue appeared with the Moodle (version 2) filter plugin when used in question text. If such a question is added to a quiz one cannot add any more questions to that same quiz as the filter generates scripts that break Moodles own scripts on the page.

Basically, Moodle renders the question texts of all the questions that are part of the quiz and then throws away everything that is not visible text and picks a short textual presentation from that. Thus throwing away the div that the filter generated script expects to use for the graph and when that div can't be found all the scripts on the page fail, breaking most of Moodles UI at the same time.

To reproduce:
 0. Firefox & Moodle with a theme meant for computers, not a mobile theme.
 1. Create a question of some type with a JSXGraph in its question text, the graph must use the filter mechanism.
 2. Have some other questions without a graph.
 3. Create a quiz and add that question with a graph to it, then try adding more questions.
 4. The re-ordering functionality of the quiz edit-page should still work but changing total points or adding questions do not.

Maybe the filter should generate a simple if around the script to check if the div exists before trying to build a graph using it?

-Matti Harjula

**Comment by aharjula** [comment]
As extra information:

In some themes you can add questions but can't change the category from which to add those questions.

**Comment by alfredwassermann** [comment]
Now, it is tested if the hosting div element exists. Please give me feedback if it works for you now. (I just changed the file filter.php)
But the whole plug-in needs an overhaul...

**Comment by aharjula** [comment]
Thank you that works, the themes that broke do not fail with this version. And thank you also for the dimensions.
