### ISSUE TITLE
Problem with circle drawing - tangent circles intersect

### ISSUE THREAD

**Issue by kenwessen** [jsxgraph/jsxgraph#174]
I tried doing a visualisation of Ford Circles with JSXGraph but had to revert to vanilla canvas since unfortunately I was getting too many inaccuracies in the circle rendering.  The important thing about Ford Circles is they never intersect, and so I can't afford a visualisation has them intersecting.  With the minimal code below you can see it just happening, but if you zoom in it becomes clear.  When I rewrote it without JSXGraph I did not have the problem.

	<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

	<html>
	<head>
	  <meta http-equiv="content-type" content="text/html; charset=utf-8">
	  <title>Circle Drawing Bug</title>
		<link rel='stylesheet' type='text/css' href='http://jsxgraph.uni-bayreuth.de/distrib/jsxgraph.css' media='screen' />
		<script type='text/javascript' src='http://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js'></script>
	</head>

	<body>
	  <div id="jsxbox" class="jxgbox" style="width: 800px; height: 500px;"></div>
	  <script type="text/javascript">	
		var board = JXG.JSXGraph.initBoard('jsxbox', {boundingbox: [-0.1, 0.6, 1, -0.1],axis: true});
		var n = 0;
		var d = 1;
		var r = 1 / (2 * d * d);
		var p = board.createElement('point', [n / d, r], {visible: false}); 
		var c = board.createElement('circle', [r, p], {strokeColor:'blue', strokeWidth:0.5});
		n = 1;
		d = 6;
		r = 1 / (2 * d * d);
		p = board.createElement('point', [n / d, r], {visible: false}); 
		c = board.createElement('circle', [r, p], {strokeColor:'blue', strokeWidth:0.5});
	  </script>
	</body>
	</html>

**Comment by alfredwassermann** [comment]
Indeed! This is a subtle bug which exists since the early days of JSXGraph: The width of the border had been included to the canvasWidth, which resulted in a slightly wrong ratio between height and width of the user coordinate system. This is fixed now. Thank you very much!!!
