### ISSUE TITLE
How to build in windows or get the unminified version

### ISSUE THREAD

**Issue by nitinsurana** [jsxgraph/jsxgraph#175]
I just wanted the unminified version to figure out why polygon drag wasn't working in a particular scenario.
Did little research and found that only way to get unminified version is "make core". Executed the following steps :

1. Cloned the repo
2. Ran "npm install", gave a couple of unimportant errors
3. Ran "make core" didn't worked, there is no such command. Therefore, installed mingw on windows and through the installation manager installed "mingw32-make" and added it to path
4. Now when I ran "mingw32-make.exe core" - it gives the following error  :

PS C:\Users\Nitin\Documents\jsxgraph> mingw32-make.exe core
mkdir -p build/bin
./node_modules/.bin/r.js -o build/core.build.json
'.' is not recognized as an internal or external command,
operable program or batch file.
Makefile:56: recipe for target 'core' failed
mingw32-make: *** [core] Error 1

Need a little help either in building in windows or getting the unminified version.

**Comment by alfredwassermann** [comment]
The recommended way to use the unminified version is to download the sources and include in the HTML document the file `loadjsxgraph.js` from the src directory instead of `jsxgraphcore.js`. Then all source files are loaded individually and you get a detailed error log.
