### ISSUE TITLE
IE bug about array head

### ISSUE THREAD

**Issue by rhcad** [jsxgraph/jsxgraph#181]
IE 9.0~11.0 will crash caused by NULL pointer when a line has 'lastarrow' or 'firstarrow' property.

It can be fixed in `makeArrows` function in `src/renderer/svg.js` (L530):

            if (el.visProp.firstarrow) {
                ...
                    if (!this.isIE) {
                      el.rendNode.setAttributeNS(null, 'marker-start', 'url(#' + this.container.id + '_' + el.id + 'TriangleEnd)');
                    }

            if (el.visProp.lastarrow) {
                ...
                    if (!this.isIE) {
                      el.rendNode.setAttributeNS(null, 'marker-end', 'url(#' + this.container.id + '_' + el.id + 'TriangleStart)');
                    }

See [the fix commit][fix-commit] in [my branch][fix-branch].

But I don't known the real problem about 'marker-start' or 'marker-end'.

[fix-branch]: https://github.com/rhcad/jsxgraph/tree/fix-ie-arrowhead
[fix-commit]: https://github.com/rhcad/jsxgraph/commit/a1aa89febdbbc3a0bca8b269eb369b8ab2e7c16e

**Comment by rhcad** [comment]
I have tested it in my geometry editor project. 

View [the site](http://rhcad.com/geometry_err) which will crash at makeArrows() in IE.
View [source code](https://github.com/rhcad/geomedit/tree/0.0.2) (v0.0.2).

**Comment by alfredwassermann** [comment]
Very nice project!

I tested this issue with this code

    var p1 = board.create('point',[-5,3], {withLabel:true, name:'A', size:10});
    var p2 = board.create('point',[5,3], {name:'B',size:10});
    var li = board.createElement('segment',['A','B'], 
        {strokeColor:'#000000',
         strokeWidth:10,
         lastArrow:true, touchLastPoint: true,
         firstArrow:true
        });    

and it worked for IE9-11. Your above mentioned site crashed in IE 9 and 10 during loading, but worked without problems (including arrows) in IE11.
Can you test the above code?

**Comment by rhcad** [comment]
Your code works for IE9-11.

I created the board via the param `{..., axis: { lastArrow: false}}`, then it works for IE9-10. But the problem will occur when changing the array head of a line. You can see the site and source code again.

**Comment by rhcad** [comment]
I changed the SVG content from `url("#jxgbox_0jxgBoard1L1TriangleStart")` to `url("#jxgbox_jxgBoard1L1TriangleStart")`, then IE crashed. So, it may be SVG problem of IE.

![](https://raw.githubusercontent.com/rhcad/geomedit/crash/doc/crash.png)

**Comment by rhcad** [comment]
[The editor site](http://rhcad.com/geometry_err) works for IE11 (IE9-10 will crash), so let's ignore the IE issue.
