### ISSUE TITLE
navigation buttons in l-system example do not display properly

### ISSUE THREAD

**Issue by r-a-v-a-s** [jsxgraph/jsxgraph#185]
Greetings :sunglasses: :v: 

The navigation buttons in the l-system example do not display properly.
http://jsxgraph.uni-bayreuth.de/showcase/lindenmayer.html

![jsxgraph_bug_00_01](https://cloud.githubusercontent.com/assets/12013378/12544195/84d2d884-c2ec-11e5-96a1-2b8fff75d5e6.png)

**Comment by alfredwassermann** [comment]
Thanks for pointing it out. The page has to be delivered as utf-8 encoded file.
