### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by maitbayev** [jsxgraph/jsxgraph#194]
Could I install jsxgraph using npm ? 
I would like to able to install it using npm.

**Comment by alfredwassermann** [comment]
There is project https://www.npmjs.com/package/angular-jsx-graph . But you are right, having a jsxgraph in npm would be great. I will try to do that.

**Comment by migerh** [comment]
With the preparations I just made we should be able to publish jsxgraph on the npm registry with the next version 0.99.5.

**Comment by maitbayev** [comment]
@migerh, nice thank you very much.

**Comment by kasperpeulen** [comment]
@migerh I could not find it on npm, any update on this?

**Comment by migerh** [comment]
It's there: https://www.npmjs.com/package/jsxgraph
