### ISSUE TITLE
Exceptions during npm install in windows system

### ISSUE THREAD

**Issue by yingdi11** [jsxgraph/jsxgraph#197]
c:\users\diying\desktop\jsxgraph-master\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\Canvas.cc) [C:\Users\DiYing\Desktop\jsxgraph-master\node_modules\canvas\build\canvas.vcxproj]
...
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

npm version is 2.11.2

**Comment by migerh** [comment]
node-canvas is an optional dependency. You need it only if you want to render bitmaps in a nodejs environment. If you do not want to do that, you can ignore this.

If you need this please you need to set up a few things first. Please follow the instructions of the package maintainer to do so: https://www.npmjs.com/package/canvas
