### ISSUE TITLE
Arrow heads for curves

### ISSUE THREAD

**Issue by alfredwassermann** [jsxgraph/jsxgraph#199]
Arrow heads for curves (and therefore arcs) are not yet implemented in canvas renderer

**Comment by soegaard** [comment]
FWIW I can recommend the paper "Blocks and Arrows with MetaPost".
It features some nice arrow heads.

https://www.ntg.nl/maps/36/19.pdf

**Comment by alfredwassermann** [comment]
Good suggestion. I'll try to pick that up.
