### ISSUE TITLE
Point infobox showing negative zero (-0.00)

### ISSUE THREAD

**Issue by uttampankajsingh** [jsxgraph/jsxgraph#202]
Hi,
I am using this library , and i draw a point like balow.

var point = board.create('point', [-0.0001,-0.0001], {
	infoboxDigits : 2
});

Now when i hover on this point it shows (-0.00, -0.00) in infobox.

jsfiddle Link : https://jsfiddle.net/uttampankajsingh/kfkypnek/

For an end user -0.00 has no meaning. It should be 0.00 for end user. 
Is this a bug?

**Comment by uttampankajsingh** [comment]
My Findings:

In function "updateInfobox" we are checking for the infoboxDigits parameter and based on that rounding of the values using toFixed(t.visProp.infoboxdigits).

So when the coordinate is small negative number( [-0.0001,-0.0001]) that rounded of to zero it get rounded to negative zero(-0.00, -0.00) .

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. The fix will be available in the next nightly build.
Best wishes,
Alfred

**Comment by uttampankajsingh** [comment]
Hi,
This issue is fixed for line now. But its still happening for circle and polygon.
Fiddle Links,
Polygon: https://jsfiddle.net/uttampankajsingh/tbgnax7u/8/
Circle: https://jsfiddle.net/uttampankajsingh/tbgnax7u/9/
