### ISSUE TITLE
COORDS_BY_USER for point size and attractor distance

### ISSUE THREAD

**Issue by alfredwassermann** [jsxgraph/jsxgraph#204]
it would be great, if it was possible to define the size of a point with `COORDS_BY_USER` instead of pixels only. Same as it is possible with `attractorDistance` (method defined in attractorUnit). Then we could make sure, that the points always have the same size on different devices.

See https://groups.google.com/forum/#!topic/jsxgraph/74Z19nzqaos

**Comment by robotiko** [comment]
+1

**Comment by alfredwassermann** [comment]
Here is a first implementation. The new attribute is named `sizeUnit` and takes values `'screen'` (default) and `user`. Here is an example:

    var p = board.create('point', [0,0], {sizeUnit:'user', size:2, strokeColor:'black', zoom:true});
