### ISSUE TITLE
How to use jsxgraph with webpack ? 

### ISSUE THREAD

**Issue by rbokel** [jsxgraph/jsxgraph#207]
When i try to compile my project, which uses jsxgraph with webpack, it fails at the shebang of requirejs/bin/r.js 

I'm using jsxgraph like so: require('jsxgraph') 

Is there anything i can do, to make it work?

**Comment by alfredwassermann** [comment]
Maybe, the discussion at google groups is helpful:
https://groups.google.com/forum/#!topic/jsxgraph/Sq-tezdMdu8

Best wishes,
Alfred

**Comment by rbokel** [comment]
That did help. Thanks Alfred.
