### ISSUE TITLE
line segment with two arrow heads has some white space between arrow and line

### ISSUE THREAD

**Issue by kasperpeulen** [jsxgraph/jsxgraph#208]
line segment with two arrow heads has some white space between arrow and line

see the following image:
<img src="https://cloud.githubusercontent.com/assets/1035299/20667985/955440c6-b56c-11e6-84e5-5988f485833b.png" width="75%">

my code is like this:
```
  board.create('segment', [[number1, 1.1], [number1+ number2, 1.1]], {
    strokeColor: Color.purple,
    strokeWidth: 1,
    firstArrow: true,
    lastArrow: true,
    withLabel: true,
    name: tex('\\frac{3}{4}'),
    label: {
      strokeColor: Color.purple,
      offset: [-5, 17]
    }
  });
```

**Comment by alfredwassermann** [comment]
Thanks for pointing this out.
