### ISSUE TITLE
making square with polygon constructor has 'gaps' in corners

### ISSUE THREAD

**Issue by kasperpeulen** [jsxgraph/jsxgraph#209]
![image](https://cloud.githubusercontent.com/assets/1035299/20794704/d9eaa442-b7cd-11e6-91e2-d6d59dfd9183.png)

This is my code:
```javascript
  const circle = board.create('polygon',[[0,1],[1,1],[1,2],[0,2]], {
    vertices: {
      visible: false
    },
    borders: {
      strokeWidth: 3
    }
  });
```

**Comment by alfredwassermann** [comment]
Very good suggestion. Thank you very  much.
In your example you can specify now

    circle = board.create('polygon',[[0,1],[1,1],[1,2],[0,2]], {
         vertices: {
         visible: false
     },
     borders: {
         strokeWidth: 3,
         lineCap: 'round'
     }
    });

Possible values: 'butt', 'round' or  'square'.

Best wishes,
Alfred
