### ISSUE TITLE
Regression with setting opacity to zero

### ISSUE THREAD

**Issue by kasperpeulen** [jsxgraph/jsxgraph#211]
I often try to hide elements on the board at startup:

```
  const image = board.create('text', [15,28, `<img width="350" src="${img}"/>`], {
    opacity: 0
  });
```

I set the opacity to 0. Later on, I will set the opacity to 1. 

However, I notice that on the latest master this doesn't work nicely anymore. The first 100/200 ms the element will be visible, and after that it will be hidden.

You can see it in this gif. I reloaded the browser in this gif, and for a very short period the "hidden" image is visible when starting up the board:
![](http://g.recordit.co/YpjIPizP68.gif)
http://imgur.com/a/ISZVn#Cp4TmO2

**Comment by alfredwassermann** [comment]
This should work now.  Thank you for  pointing it out.

**Comment by kasperpeulen** [comment]
Thanks 👍
