### ISSUE TITLE
String need to be escaped two times?

### ISSUE THREAD

**Issue by kasperpeulen** [jsxgraph/jsxgraph#212]
I try to escape backslashes with es6 String.raw template strings.

```javascript
board.create('text', [1.0, 1.1, String.raw`
    \begin{array}{rclcl} 
    2x + 5 &=& 4x -3 &&\\
    2x + 5 - 4x &=& 4x -3 - 4x &&\\
    -2x +5 &=& -3 &&\\
    -2x  &=& -8&&\\
     x  &=& {4}&&
     \end{array} 
`];
```

However, this doesn't seem to work with JSX graphs. It seems to need 4 backslashes, for every back slash. This does work:

```javascript
board.create('text', [1.0, 1.1, `
    \\\\begin{array}{rclcl} 
    2x + 5 &=& 4x -3 &&\\\\\\\\
    2x + 5 - 4x &=& 4x -3 - 4x &&\\\\\\\\
    -2x +5 &=& -3 &&\\\\\\\\
    -2x  &=& -8&&\\\\\\\\
     x  &=& {4}&&
     \end{array} 
`];
```

Is there a way around this? We got some none technical mathematicians that write the texts. We would like that they can provide the texts for the animations without needing to know much about javascript.

**Comment by alfredwassermann** [comment]
The above es6 example works with `parse:false`:

    board.create('text', [1.0, 1.1, String.raw`
        \begin{array}{rclcl} 
        2x + 5 &=& 4x -3 &&\\
        2x + 5 - 4x &=& 4x -3 - 4x &&\\
        -2x +5 &=& -3 &&\\
        -2x  &=& -8&&\\
         x  &=& {4}&&
         \end{array} 
    `], {parse:false};

**Comment by kasperpeulen** [comment]
@alfredwassermann thanks 👍
