### ISSUE TITLE
function "pow()" is undefined

### ISSUE THREAD

**Issue by Badatos** [jsxgraph/jsxgraph#215]
Hello,
I found an issue in "JXG.GeonextParser.replacePow" function (from parser/geonext.js file)

The problems comes from lines 152-153 : 

```
                //te = te.replace(expr, 'JXG.Math.pow($1,$2)');
                te = te.replace(expr, 'pow($1,$2)');
```

it cause an error "**pow undefined**", and it's true : there is no "pow" function defined.

To correct this, I suggest using the function "_JXG.Math.pow_", which is still defined (I wonder why the code is commented)
Or you can also just use the standard javascript "_Math.pow_", which will work too.

This error can be raised if you call this for a simple sample : 

` eval(JXG.GeonextParser.geonext2JS('x^2-y'));`

and if you want a more "real life case" sample, i attached an html file so you can test
[issue_jsxgraph_test.html.zip](https://github.com/jsxgraph/jsxgraph/files/713966/issue_jsxgraph_test.html.zip)

**Comment by alfredwassermann** [comment]
Thank you very much for pointing it out. 
In JSXGraph, Geonext2JS as a parser of math syntax has been replaced since some years by our own language *JessieCode*, which comes with JSXGraph. See https://github.com/jsxgraph/JessieCode.
That means, meanwhile Geonext2JS ouputs JessieCode code, therefore `pow()`. 

For your application that means you should use `board.jc.snippet`, see http://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.JessieCode.html#snippet . It gives you back a JavaScript function which then can be
executed. JessieCode is much more powerful than the old GEONExT syntax. You can define functions, loops, ... As a side effect, a direct call of `eval` is avoided. This prevents execution of user provided JavaScript code which may be dangerous.

Here is your example:

    var f = board.jc.snippet('x^2-y', true, 'x, y');
    // f is the following function:
    console.log(f.toString());

    // Evaluate it:
    console.log(f(3, 1));
    // The same can be done directly:
    console.log((board.jc.snippet('x^2-y', true, 'x,y'))(3,1));

**Comment by Badatos** [comment]
Thank you for your fast answer !
I think I understood the general idea. I tried to apply it in my "real life case" sample (cf zip), but i don't really find how to do it.

I replaced the line 35 :
`var txt2 = JXG.GeonextParser.geonext2JS('x^2-y');`

by this : 
`var txt2 = brd.jc.snippet('x^2-y', true, 'x, y').toString();`

...and I have no more javascript error, but i still displays nothing at all ! :/

Can you give us more hint on how to change our code to make it work ?

**Comment by Badatos** [comment]
Maybe it will helpful : 

You must be still using Geonext2JS on the page here : 

http://jsxgraph.uni-bayreuth.de/wiki/index.php/Differential_equations

Because if you put "x^2" it will no more work, too :/

**Comment by bperrinriou** [comment]
And also 
http://jsxgraph.uni-bayreuth.de/wiki/index.php/Systems_of_differential_equations

**Comment by Badatos** [comment]
It's me again ;)

I think i found a way to solve our problem.

I replaced our old code : 

```
  var txt1 = JXG.GeonextParser.geonext2JS('-x-y');
  var f1_3 = new Function("x", "yy", "var x = yy[0]; var y = yy[1]; var z = " + txt1 + "; return [z];");

  var txt2 = JXG.GeonextParser.geonext2JS('x^2-y');
  var f2_3 = new Function("x", "yy", "var x = yy[0]; var y = yy[1]; var z = " + txt2 + "; return [z];");

  var f_3 = new Function('t', 'yy', 'var x = yy[0], y = yy[1];  var z1 = ' + txt1 + '; var z2 = ' + txt2 + '; return [z1,z2];');
```

... by this one : 

```
  var snip1 = brd.jc.snippet('-x-y', true, 'x, y');
  var f1_3 = new Function("x", "yy", "return [snip1(yy[0], yy[1])];");

  var snip2 = brd.jc.snippet('x^2-y', true, 'x, y');
  var f2_3 = new Function("x", "yy", "return [snip2(yy[0], yy[1])];");

  var f_3 = new Function('t', 'yy', "return [snip1(yy[0], yy[1]), snip2(yy[0], yy[1])];");

```

Do you think it's a clean way to do ?

**Comment by migerh** [comment]
No, not a clean way. `brd.jc.snippet()` returns a simple function you can call with two parameters. You do not need the `new Function()` construction. This should work:

```JavaScript
  var snip1 = brd.jc.snippet('-x-y', true, 'x, y');
  var f1_3 = function (x, yy) {
      return [snip1(yy[0], yy[1])];
  }

  var snip2 = brd.jc.snippet('x^2-y', true, 'x, y');
  var f2_3 = function (x, yy) {
      return [snip2(yy[0], yy[1])];
  }

  var f_3 = function (t, yy) {
      return [snip1(yy[0], yy[1]), snip2(yy[0], yy[1])];
  }
```

**Comment by Badatos** [comment]
Thanks a lot !
Your correction is really better : it's work, it's simpler, and it's more secure... what else ? ;D

Now it only remains the bug on the samples on your wiki (when you put an "x^2") : 
- http://jsxgraph.uni-bayreuth.de/wiki/index.php/Differential_equations
- http://jsxgraph.uni-bayreuth.de/wiki/index.php/Systems_of_differential_equations

Have a nice day !

**Comment by bperrinriou** [comment]
What about a slider in the expresion as
var snip = brd5.jc.snippet(c1.Value() + '*x+y',true,'x,y');
I do not succeed (it changes nothing).

Thanks !

**Comment by alfredwassermann** [comment]
Thank you very much for sending the out-dated links. Using sliders in a function term is as easy as it can get: Just give the slider a name and use this name in the function term. The page http://jsxgraph.uni-bayreuth.de/wiki/index.php/Differential_equations has now been updated and uses a slider.

Best wishes,
Alfred

**Comment by bperrinriou** [comment]
Thanks a lot. Much more simple than before (no need taking Values ...) !
Everything works now. We use jsxgraph and in particular codes adapting from the differential equations in the software WIMS. Thanks again !

**Comment by bperrinriou** [comment]
Just about Geonext
It seems to me that
http://jsxgraph.uni-bayreuth.de/wiki/index.php/Displaying_GEONExT_constructions
does not work no more.
