### ISSUE TITLE
Create repository for Moodle JSXgraph filter

### ISSUE THREAD

**Issue by leac** [jsxgraph/jsxgraph#219]
Hi

Could you please add a GitHub repository for the Moodle JSXgraph filter? We are using git to manage our Moodle servers, and such a repository would help us keep up to date with any changes to your filter.

Kindly
Lea
Ort Israel

**Comment by leac** [comment]
@nadavkav

**Comment by alfredwassermann** [comment]
OK, done:  https://github.com/jsxgraph/moodle-jsxgraph-plugin
Thank you very much for this suggestion.
Best wishes,
Alfred
