### ISSUE TITLE
Request: Suffix/Unit Label for Slider

### ISSUE THREAD

**Issue by Haumed** [jsxgraph/jsxgraph#229]
Hello,

First off thanks everyone for a great library!

Second, a small feature I'd like: Sliders allow for a Label, which appears before the Value and is of course handy. I would like to also be able to add some text that appears after the Value which I can use to add units. This would be extremely handy and easy to implement. (For those of us doing physics and not just pure math, units are everything.)

Names could be: SuffixLabel, UnitLabel, PostLabel. I believe the first is the most self-explanatory.

Given a little guidance on your conventions I could help add the feature myself.

Let me know!

**Comment by alfredwassermann** [comment]
Good suggestion. Is now implemented.
