### ISSUE TITLE
Wrong Axes labeling

### ISSUE THREAD

**Issue by jobstdavid** [jsxgraph/jsxgraph#233]
Using this code: 

<DOCTYPE html>
  <html>
<head>
  <link rel="stylesheet" type="text/css" href="https://jsxgraph.uni-bayreuth.de/distrib/jsxgraph.css" />
  <script type="text/javascript" src="https://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js"></script>
</head>
<body>
  <div id="jxgbox" class="jxgbox" style="width:500px; height:500px;"></div>
  <script type="text/javascript">
  var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox:[-5,10,5,-2], axis:true});
  </script>
</body>
</html>

![1](https://user-images.githubusercontent.com/31279210/29615929-f85292b0-880f-11e7-9f00-5562148f59e5.jpeg)

I get a wrong representation of the negative axes and the scaling options. 
What can I do to change this?
Thank you very much!

**Comment by alfredwassermann** [comment]
You can try

     <meta charset="utf-8">
     <script charset="utf-8" type="text/javascript" src="https://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js"></script>
     <script charset="utf-8"  type="text/javascript"> var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox:[-5,10,5,-2], axis:true}); </script> 

Best wishes,
Alfred

**Comment by apio1** [comment]
Hi Alfred, I've got the same problem. I tried your suggestion but it did not work for me.
Thank you very much!
apio1

**Comment by alfredwassermann** [comment]
Can you please give me the browser name, version, operating system and possibly the head-part of the HTML file?
Best wishes,
Alfred

**Comment by apio1** [comment]
I now figured out what the problem was. I have been using a local copy of jsxgraphcore.js. Although v0.99.6, as your online version, for some reason, my copy started to produce the error. I replaced my copy with the version available at the uni-beureuth server. Now, everything is ok. Thank you for your help!
Best regards,
apio1
