### ISSUE TITLE
unicode minus not working

### ISSUE THREAD

**Issue by ribrdb** [jsxgraph/jsxgraph#238]
In formatLabelText at https://jsxgraph.uni-bayreuth.de/docs/symbols/src/src_base_ticks.js.html it says:
```
             if (Type.evaluate(this.visProp.useunicodeminus)) {
                 labelText = labelText.replace(/-/g, '\u2212');
             }
```
However in http://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js this is compiled as:
```
    n.evaluate(this.visProp.useunicodeminus)&&(e=e.replace(/-/g,"âˆ’"))
```

I'm using chrome 60 on mac.

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. This was a faulty setting of our web server. We changed the default charset of javascript files now to utf-8 and it seems to solve the problem.
Nevertheless, it is a good idea to import `jsxgraphcore.js` with

    <script src="//jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js" charset="UTF-8"></script> 

Best wishes,
Alfred
