### ISSUE TITLE
Curve bug

### ISSUE THREAD

**Issue by hudakh** [jsxgraph/jsxgraph#245]
I am plotting a parametric curve using jsxgraph. I found that when setting the bounding box to focus on specific parts of the plot, a line is created as part of the curve that should not be part of my original curve. See this [jsfiddle](https://jsfiddle.net/f3pbvaja/2/) for example. If you zoom out, the line disappears.

Unfortunately, I am unsure why this is happening and whether it is specific to parametric curves. If I change the interval for plotting to` 0, 2*Math.PI`, or even , `2*Math.PI/3, 2*Math.PI`, it's all good.

**Comment by StephanvandenBerkmortel** [comment]
Might be related to #587 , therefore updated jsfiddle for the reference problem: https://jsfiddle.net/g4cuxpe7/
