### ISSUE TITLE
Bounding Box Empty

### ISSUE THREAD

**Issue by apio1** [jsxgraph/jsxgraph#248]
My webpage uses jsxgraph and it is great! I'm now trying to make it more mobile device-friendly when showing jsxgraph by setting the style of my bounding box to

&lt;div class="jxgbox" style="max-width:500px; width:100%; height:500px;"></div>

instead of  

&lt;div class="jxgbox" style="width:500px; height:500px;"></div>

This seems to cause problems when rendering the box. When my page is loaded via normal page navigation, the bounding box remains empty. When it is loaded via ajax, it renders correctly. I figured out that I can solve the problem by setting the "width" to a fixed number of pixels (e.g. 500px) again, but this is not what I wanted for mobile devices. Of course, I could also load my page via ajax all the time, but this is not optimal for the SEO performance of my page. 

Do you have any suggestions, how to solve this problem?

**Comment by alfredwassermann** [comment]
Sorry for the delay. Unfortunately, I can not reproduce this behaviour, see https://jsfiddle.net/aekd06go/ .
Is it possible that you are loading some JavaScript files with the async attribute and the code is not available during initial loading? Is there any output in the JavaScript console?

Best wishes,
Alfred

**Comment by apio1** [comment]
Sorry for the delay also and thank you for your answer. Unfortunately, I have no idea about the async attribute. 

This is the console message. 

jsxgraphcore.js:76 Uncaught TypeError: Cannot read property 'length' of undefined
    at t.Ticks.updateRendererLabels (jsxgraphcore.js:76)
    at t.Ticks.updateRenderer (jsxgraphcore.js:76)
    at t.Ticks.fullUpdate (jsxgraphcore.js:65)
    at Object.t.createTicks [as ticks] (jsxgraphcore.js:76)
    at t.Board.create (jsxgraphcore.js:72)
    at Object.t.createSlider [as slider] (jsxgraphcore.js:76)
    at t.Board.create (jsxgraphcore.js:72)
    at (index):24

If you seek a working example causing this error, please open 

https://www.bookofproofs.org/branches/definition-of-complex-numbers/

The error disappears if you open the same page like this: First, open 

https://www.bookofproofs.org/branches/complex-numbers-1/

then, expand the node "Definition of complex numbers" by clicking the button labeled "216" to the left of this definition. 

I really have no idea what is going on.

**Comment by alfredwassermann** [comment]
The problem in https://www.bookofproofs.org/branches/definition-of-complex-numbers/ is that during initialization of the JSXGraph board the width is not yet known and set zero. You can see this if you take e.g. the DOM inspector of firefox: you'll see that the JSXGraph SVG element has `width=0px`. The width of the SVG element is set during the call JXG.JSXGraph.initBoard(). There, the width of the JSXGraph div element is read and a SVG element of the same width is  created inside of that div element.

It seems to me that in https://www.bookofproofs.org/branches/definition-of-complex-numbers/ the content of the section "Definition of Complex Numbers" is created by JavaScript after loading the page and the JSXGraph code is called *before* the HTML elements of the section have been rendered.

When the DOM is refreshed using ajax, the JSXGraph seems to be executed somewhat later and the div has already been rendered.

Can you postpone the call of the JSXGraph code until all HTML elements have been rendered?

Best wishes,
Alfred

**Comment by apio1** [comment]
Wow! Thank you so much! 

Postponing the call of JSXGraph (after the page is loaded) solved the problem.

**Comment by alfredwassermann** [comment]
This has been now resolved generally since v1.3.1
