### ISSUE TITLE
board.removeObject for the line object does not affect its points

### ISSUE THREAD

**Issue by oceanic71** [jsxgraph/jsxgraph#250]
board.create('line') adds three new elements to the page: line and two hidden ellipses. 
board.removeObject method removes the line element, but not the ellipses.
Please, see https://jsfiddle.net/xibo/gjexce7g/
jsxgraph 0.99.6

**Comment by alfredwassermann** [comment]
For the time being, this has to be considered as *feature*. The reason is, JSXGraph does not distinguish if the line is constructed through existing points or if the points are created during the construction of the line.
Best wishes,
Alfred
