### ISSUE TITLE
Input anchor doesn't work.

### ISSUE THREAD

**Issue by AlexandrTuniev** [jsxgraph/jsxgraph#253]
Hi, I'd like to anchor input with some point/line so it will adjust its position based on point/line position. I have tried to anchoring input element with point, but seems it doesn't working. Is that something known or bug? Is there any workaround, to get desired behavior.  To reproduce issue just create point and some input element, pass {anchor: point} as input creation attribute.

**Comment by alfredwassermann** [comment]
Thank you very much for finding this bug.
