### ISSUE TITLE
Glider snapToGrid

### ISSUE THREAD

**Issue by AlexandrTuniev** [jsxgraph/jsxgraph#254]
Hi, I would like to use snapToGrid option on glider, so its only possible positions will be on the grid crossroads(like usual point with snapToGrid:true) but it looks buggy,  it has some jumps during movement, but with some weird coordinates.  Is this some sort of bug or  normal behavior?
Thanks

**Comment by alfredwassermann** [comment]
For the time being, when dragging a glider coordinates of the pointer device are rounded to be on grid crossroads. From there, the glider is projected orthogonally to its parent objects. For - e.g. - lines which are neither horizontal nor vertical this leads to coordinates which may look surprising.

Can you please send an example? 
Alfred

**Comment by AlexandrTuniev** [comment]
Thanks for quick response, here is a jsfiddle example, http://jsfiddle.net/atuniev/237ujnLf/3/  , basically what I would like is that glider only jumps to grid intersection points, in that example points (3,4), (-1,1), (-5,-2), (-9, -5) and etc. only, is that possible?
Sash

**Comment by alfredwassermann** [comment]
This is a tricky problem. The essence of it is: you have a line of the form `(3, 4) + t(4, 3)` and you want the glider to visit only points on the line which are integer multiples of `t`. My solution is the following, see it at http://jsfiddle.net/237ujnLf/25/ in action:

    var brd = JXG.JSXGraph.initBoard('box', {
            boundingbox: [-10, 10, 10, -10],
            grid: true
         }),
        li = brd.create('line', [[3,4], [7,7]]),
        g = brd.create('point',[3, 4]);
    
    g.on('drag', function() {
   	var proj, t, dir = [4, 3]; // "li.point2 - li.point1"
        
        proj = JXG.Math.Geometry.projectCoordsToSegment(
             this.coords.usrCoords, 
             li.point1.coords.usrCoords,
             li.point2.coords.usrCoords);
              
        t = Math.round(proj[1]);
        this.moveTo([3 + t * dir[0], 4 + t * dir[1]]);
    });

Here, the method `JXG.Math.Geometry.projectCoordsToSegment` computes the projection of a point to the line given by two points `point1` and  `point2`. The return value is an array containing the coordinates of the projection and the value of `t`. Having this, we just have to round `t` and compute the new point 

    point1 + round(t) * (point2 - point1)

Maybe, we should continue this discussion on https://stackoverflow.com

Best wishes,
Alfred

**Comment by AlexandrTuniev** [comment]
Thanks, yep done something similar.
