### ISSUE TITLE
Group with only one translation point issue

### ISSUE THREAD

**Issue by AlexandrTuniev** [jsxgraph/jsxgraph#255]
Hi, I have created group of 3(A,B,C ) points, and excluded 2 (B,C) points from translation points. 
When dragging  A - all moves as expected, but when dragging B(nothing moves except B, as expected) and then dragging C,  the point A suddenly changes its position.
Here is jsfiddle http://jsfiddle.net/atuniev/4vho5hvb/
Thanks,
Sash

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. It is fixed now.

**Comment by AlexandrTuniev** [comment]
Thanks!
