### ISSUE TITLE
Refactor visibility of elements

### ISSUE THREAD

**Issue by migerh** [jsxgraph/jsxgraph#26]
Attributes should not be overruled silently. Right now this affects the 'visible' attribute. An element should be visible only if the user says so (attribute 'visible') and there is a representation in the real plane.

**Comment by alfredwassermann** [comment]
See for example slider.showElement(), slider.hideElement()

**Comment by alfredwassermann** [comment]
Fixed by ceef11f545d51581a9f32ac667fa2386ff139a98
