### ISSUE TITLE
Memory leak issues

### ISSUE THREAD

**Issue by jack-vo** [jsxgraph/jsxgraph#267]
Hi,
First of all, thank you for such a great work! We have been using jsxgraph 0.97.0 for years and would like to upgrade to latest version v0.99, however we spotted that in the new version there is critical memory issue with the library. I have taken the Performance/Memory snapshots for your information.

<img width="550" alt="screen shot 2018-07-05 at 12 22 07 pm" src="https://user-images.githubusercontent.com/9317436/42299946-4f777ee0-8051-11e8-9a99-9949df790d57.png">

<img width="502" alt="screen shot 2018-07-05 at 12 22 28 pm" src="https://user-images.githubusercontent.com/9317436/42299954-577a17ce-8051-11e8-99fe-c97871d49dda.png">

The methods *setCoordinates + _plotRecursive* and some other internal methods are cause huge memory performance so the whole page crashed after we created like 10+ custom shape

<img width="656" alt="screen shot 2018-07-05 at 12 45 04 pm" src="https://user-images.githubusercontent.com/9317436/42299987-79c5d034-8051-11e8-8961-9479ad6b34c6.png">

Cheers

**Comment by jack-vo** [comment]
I did a bit of investigation on my own and realized that the leak is mainly from the method *_plotRecursive*. If i create a *curve*, the *_plotRecursive* will keep calling itself non-stop in the background and eventually crash the browser.

**Comment by alfredwassermann** [comment]
Dear Jack,
thank you very much for finding this problem. I'm a bit alarmed. 
Can you please post the source code of this example?

**Comment by alfredwassermann** [comment]
Dear Jack,
can you please give us a little bit more information about the browser. Can you observe this problem in all browsers? 
What I know about this problem is that especially **Microsoft Edge** has performance issues with JSXGraph. Actually, in IE11 JSXGraph constructions are much faster than in Edge.
On the other hand, Edge seems to have no problems with JSXGraph 0.99.8.
One explanantion could be that Edge has optimization problems if the code contains anonymous functions.

Best wishes, Alfred

**Comment by jack-vo** [comment]
Hi Alfred,
Thank you for your attention on this. I post our old code to generate it here

```
JXG.createSine = function (board, parents, attributes) {
    attributes = JXG.merge(attributes, JXG.Options.sine);

    var rootPoint = parents[0];
    var edgePoint = parents[1];
    var curve = board.create('curve', [
        function (x) {
            return x;
        },
        function (x) {
            var rootCoords = rootPoint.coords.usrCoords;
            var edgeCoords = edgePoint.coords.usrCoords;
            var rootX = rootCoords[1];
            var rootY = rootCoords[2];
            var edgeX = edgeCoords[1];
            var edgeY = edgeCoords[2];
            var amplitude = edgeY - rootY;
            var freq = 1 / (4 * (edgeX - rootX));
            // And here is the expression that maps root and edge coords
            // to the sine curve. Its based on:
            //   f(x) = A sin (2\pi * freq * x) + y0

            return amplitude * Math.sin(2 * Math.PI * freq * (x - rootX)) + rootY;
        }
    ], attributes);

    rootPoint.addChild(curve);
    edgePoint.addChild(curve);
    curve.parents = [rootPoint.id, edgePoint.id];
    curve.rootPoint = rootPoint;
    curve.edgePoint = edgePoint;
    curve.type = JXG.OBJECT_TYPE_CURVE;
    curve.elType = 'sine';

    return curve;
};
```
Hope it helps.

Cheers
Jack

**Comment by alfredwassermann** [comment]
Dear Jack,
many thanks for the source code. Can you please also tell me, 
for which browser you got these Performance/Memory snapshots?

In 0.99.7 there are attributes to lower the recursion depth for function plotting. This is easily possible for your sine example, since the result is a smooth curve. 
So, here is your code again, which is much faster:

    JXG.createSine = function (board, parents, attributes) {
        attributes = JXG.merge(attributes, JXG.Options.sine);

        var rootPoint = parents[0];
        var edgePoint = parents[1];

        var funcX = function (x) {
                return x;
            };
        var funcY = function (x) {
                var rootCoords = rootPoint.coords.usrCoords,
                    edgeCoords = edgePoint.coords.usrCoords,
                    rootX = rootCoords[1],
                    rootY = rootCoords[2],
                    edgeX = edgeCoords[1],
                    edgeY = edgeCoords[2],
                    amplitude = edgeY - rootY,
                    freq = 1 / (4 * (edgeX - rootX));

                // And here is the expression that maps root and edge coords
                // to the sine curve. Its based on:
                //   f(x) = A sin (2\pi * freq * x) + y0
                return amplitude * Math.sin(2 * Math.PI * freq * (x - rootX)) + rootY;
            };

        var curve = board.create('curve', [funcX, funcY], attributes);

        rootPoint.addChild(curve);
        edgePoint.addChild(curve);
        curve.parents = [rootPoint.id, edgePoint.id];
        curve.rootPoint = rootPoint;
        curve.edgePoint = edgePoint;
        curve.type = JXG.OBJECT_TYPE_CURVE;
        curve.elType = 'sine';

        return curve;
    };
    JXG.registerElement('sine', JXG.createSine);

    var board = JXG.JSXGraph.initBoard("jxgbox", {
                    boundingbox: [-5, 5, 5, -5],
                    axis: true,
                    zoom: {
                        wheel: true
                    },
                    pan: {
                        needTwoFingers: true
                    }
                });

    var p1 = board.create('point', [-1, 1]);
    var p2 = board.create('point', [ 1, 2]);
    var cur = board.create('sine', [p1, p2], {recursionDepthHigh: 13, recursionDepthLow: 8});

Best wishes,
Alfred

**Comment by jack-vo** [comment]
Hi Alfred,
That's great, thanks a lot for your code example and your lightning reply  :) I will give it a try and let you know the result.
FYI, the snapshots were taken from Chrome 67.0.3396.99 (Official Build)

Cheers,
Jack

**Comment by jack-vo** [comment]
Hi Alfred,
Sorry for being so late to reply, the code example you provided has helped us to solve the performance issue. 
We really appreciate your help and please keep up with your great work :)

Cheers,
Jack
