### ISSUE TITLE
Can I use jsxgraph to extract points?

### ISSUE THREAD

**Issue by sriram15690** [jsxgraph/jsxgraph#268]
Can I use jsxgraph only to extract co-ordinates from a function over a certain range? My application has many custom UI requirements like the size of axis, the size of the visual-grid etc. Hence, I want to use another graph/chart library for drawing the chart.

**Comment by alfredwassermann** [comment]
Yes, you can use the 'no'-renderer. 
Here is a working example, see https://jsfiddle.net/vcL7aepo/698/:

HTML code of an invisible JSXGraph box:

    <div id="jxgbox" style="width:0px; height:0px"></div>
    <input type="text" id="out">

JavaScript code:

    const board = JXG.JSXGraph.initBoard('jxgbox', {
				renderer: 'no',
    				boundingbox: [-5, 5, 5, -5],
                                axis: true
              });
     
    var c = board.create('circle', [[0, 0], 3]);
    // Access the JSXGraph circle:
    document.getElementById('out').value = c.Radius();

Best wishes,
Alfred
