### ISSUE TITLE
can not create or clone Line with same parent?

### ISSUE THREAD

**Issue by sonygod** [jsxgraph/jsxgraph#274]
can not create or instance  Line with same parent?

```
var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox:[-1, 4, 4, -1], axis: true, grid: true, keepaspectratio: true, showcopyright: false, zoom: true, pan: true}),
        out = document.getElementById('out');



    var p1 = board.create('point', [4.5, 2.0]);
    var p2 = board.create('point', [1.0, 1.0]);
    var line1 = board.create('line', [p1, p2]);

    var line2 = board.create('line', [p1, p2],{ straightFirst: false, straightLast: true, lastArrow: true, name: "line2" });

//I want to clone line1,but only one line draw on board?
```

**Comment by alfredwassermann** [comment]
I'm not sure if I understand the question right. But your example indeed contains two lines. Since they have the same color and width they can not be distinguished.
Here (https://jsfiddle.net/vcL7aepo/1027/) is your example with different values for `strokeWidth` and `strokeColor`:

    var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox:[-1, 6, 4, -1], axis: true, grid: true,  
                                keepaspectratio: true, showcopyright: false, zoom: true, pan: true}),

    var p1 = board.create('point', [4.5, 2.0]);
    var p2 = board.create('point', [1.0, 1.0]);
    var line1 = board.create('line', [p1, p2], { strokeColor: 'black'});

    var line2 = board.create('line', [p1, p2],{ straightFirst: false, straightLast: true, lastArrow: true, 
            name: "line2", strokeWidth: 6 });

Best wishes,
Alfred
