### ISSUE TITLE
[request]fill or weld  the joins between two segment?

### ISSUE THREAD

**Issue by sonygod** [jsxgraph/jsxgraph#285]
![image](https://user-images.githubusercontent.com/748320/53632388-c19ebf00-3c4f-11e9-8109-b8c32a900370.png)

to

![image](https://user-images.githubusercontent.com/748320/53632404-ccf1ea80-3c4f-11e9-8410-e2b619716471.png)

?are there any easy way to do ?

![image](https://user-images.githubusercontent.com/748320/53632444-ebf07c80-3c4f-11e9-849c-5daa83acd8f9.png)

**Comment by migerh** [comment]
There's an attribute called `lineCap` that should be what you're looking for. Here's an example on how to use it:

https://jsfiddle.net/migerh/zhncjmgq/

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/53676105-e7bc7180-3cd8-11e9-9a98-0a818af8ec5d.png)

it's seem is not what I want . there are  add extra Gap ..not perfect like smooth.
