### ISSUE TITLE
intersection bug

### ISSUE THREAD

**Issue by sonygod** [jsxgraph/jsxgraph#289]
there are to parallel line ,and create intersection ,and the result is not null?

                                 var line1=board.create("line",[[0,0],[0,1]]);
				 var line2=board.create("line",[[1,0],[1,1]]);

				 var p=board.create("intersection",[line1,line2,1]);

				 console.log(p.X()+""+p.Y());
                                 
                                //and the result is [0 ,1]  //why ?it should be null

**Comment by alfredwassermann** [comment]
Internally, JSXGraph works with homogeneous coordinates. That means, there is a third coordinate `z` which is > 0 if the point is finite and it is zero if the point is infinite. In your case, the coordinates of the intersection points are (z, x, y) = (0, 0, 1). Homogeneous coordinates are a convenient way to avoid case distinctions.
Best wishes,
Alfred
