### ISSUE TITLE
`zoomElements()` includes axes

### ISSUE THREAD

**Issue by tanman-** [jsxgraph/jsxgraph#292]
The issue is most apparent when the subject elements are in quadrant III and far away from the origin. The issue still occurs when `axis` === `false`.

Reproductions:
https://jsfiddle.net/qs0h21c4/1/
https://jsfiddle.net/qs0h21c4/

**Comment by alfredwassermann** [comment]
Thank you very much. An improved version will be in tonight's nightly build.

**Comment by alfredwassermann** [comment]
Thank you very much. An improved version will be in tonight's nightly build.

**Comment by tanman-** [comment]
Thanks!
