### ISSUE TITLE
Page becomes Unresponsive when axis=true and parent size=8px

### ISSUE THREAD

**Issue by dangcuuson** [jsxgraph/jsxgraph#293]
Hi there,

Thank you for this amazing library.
I've found a weird issue when creating a board with `axis:true` with a certain size in the parent element cause the browser to hang.

How to reproduce:
1. [https://jsfiddle.net/fpcwk7t5/2/](https://jsfiddle.net/fpcwk7t5/2/)
2. The preview panel does not render anything and gives unresponsive error after a while
![image](https://user-images.githubusercontent.com/20551609/55864659-3efb0f00-5bc0-11e9-9386-a60e71c2cf54.png)

The issue only happens when `axis=true`, and only when the `width` or `height` is set to `8px`. Similar sizes such as `7px` or `9px` works fine.

I could be happen in bigger sizes as well but that's the only number I could find.

Regards.

**Comment by dangcuuson** [comment]
Update:

Sometimes it does render but page still give unresponsive error after a while.

![image](https://user-images.githubusercontent.com/20551609/55865210-3fe07080-5bc1-11e9-964a-e4a1b8982e87.png)

**Comment by alfredwassermann** [comment]
Thank you for pointing this out. It will be fixed now. A quick workaround is to to set 

    JXG.Options.axis.margin = 0;

before calling `initBoard`. The default value for `margin` is `-4`. Therefore, the problems at exactly 8px.

Best wishes, Alfred
