### ISSUE TITLE
How can I shade inside the curve using JSXgraph?

### ISSUE THREAD

**Issue by Mark2De** [jsxgraph/jsxgraph#299]
I'm currently trying to shade a quadratic inequality. For that I must be able to shade inside and/or outside of the determined curve. I have looked through JSXgraph documentation and I do not seem to see anything helpful to my problem. 

The current code to create the curve:
`function quadraticFunctionClassical(y, symbol, a, b, c, field, color) {
    var graph = board.create('functiongraph', [function (x) { return (a * Math.pow(x, 2) + (b * x) + c); }], { id: field, strokeColor: color, highlightStrokeColor: 'yellow', strokeWidth: 2 });
    graph.on('down', function (e, i) {
        showMaster(this.id);
    });
    graphMap.set(field, graph);
}`

The last example does not seem to work in version 0.99.6
http://jsxgraph.uni-bayreuth.de/~alfred/jsxgraph/distrib/docs/symbols/Inequality.html

Example of inequality that should be working
`
var f = board.create('functiongraph', ['sin(x)', -2*Math.PI, 2*Math.PI]);
var ineq_lower = board.create('inequality', [f]);
var ineq_greater = board.create('inequality', [f], {inverse: true, fillColor: 'yellow'});
`

**Comment by alfredwassermann** [comment]
See the answer at stackoverflow: https://stackoverflow.com/questions/57466942/how-can-i-shade-inside-the-curve-using-jsxgraph/57491240#57491240
