### ISSUE TITLE
How to shade outside a circle in JSXgraph

### ISSUE THREAD

**Issue by Mark2De** [jsxgraph/jsxgraph#301]
I'm currently trying to shade inside and outside a circle in JSXgraph, similar to an inequality.

My current code to create a circle:
` 
var A = board.create('point', [h, k], { name: '', size: 0, fixed: true}),
        B = board.create('point', [h, k+r], { name: '', size: 0, fixed: true}),
        graph = board.create('circle', [A, B], { id: field, size: 0, fixed: true });
    graph.on('down', function (e, i) {
        showMaster(this.id);
    });
    graphMap.set(field, graph);
    inequality(">", field, graph, color);
`

I have found that you can shade inside using these object proprieties:
`{strokeWidth: 2, dash: 2, fillColor: 'red', fillOpacity: 0.3}`

But there is no option to shade the outside, I tried to change board color and overlap fillColor white, we can still see the red. 

Any suggestions?

**Comment by alfredwassermann** [comment]
What about to change board color and overlap fillColor white with fillOpacity: 1.0?

**Comment by Mark2De** [comment]
I have tried, but it removes the board grid.Sent from my Huawei phone-------- Original Message --------Subject: Re: [jsxgraph/jsxgraph] How to shade outside a circle in JSXgraph (#301)From: alfredwassermann To: jsxgraph/jsxgraph CC: Mark2De ,Author What about to change board color and overlap fillColor white with fillOpacity: 1.0?

**Comment by alfredwassermann** [comment]
This can be realized with the new clipping algorithms, see https://groups.google.com/forum/#!topic/jsxgraph/PckP08AuzUA and https://jsfiddle.net/zwmya6dk/1/
