### ISSUE TITLE
Support for MathJax needs to be updated to new MathJax version

### ISSUE THREAD

**Issue by soegaard** [jsxgraph/jsxgraph#306]
MathJax recently introduced version 3. 
The API of MathJax changed, so changes to JSXGraph is required
in order to use the new version of MathJax.

http://docs.mathjax.org/en/latest/upgrading/v2.html

Here is the relevant code of JSXGraph.
https://github.com/jsxgraph/jsxgraph/blob/master/src/renderer/abstract.js#L1002

**Comment by VivaRado** [comment]
bump

**Comment by VivaRado** [comment]
To render with MathJax 3 
in jsxgraph replace:
```
MathJax.Hub.Queue(["Typeset",MathJax.Hub,e.rendNode])
```
with:

```
MathJax.typeset([e.rendNode])
```

**Comment by alfredwassermann** [comment]
Thanks for reminding me. I just added MathJax v3 support in the sources. It will appear in today's nightly build and it is amazing! Interestingly enough, on a Mac it seems to be faster on Safari and Firefox than on Chrome.
Thanks a lot on insisting on that.

**Comment by alfredwassermann** [comment]
I have to correct me: Chrome, Firefox and Safari seem to be on par.

**Comment by VivaRado** [comment]
I tested it with ```if (n.exists(MathJax.typeset)) {``` and  ```if ( MathJax.typeset) {```
The second one is a little faster on update.
