### ISSUE TITLE
update event on (Geometry)Elements not working

### ISSUE THREAD

**Issue by Sjiep** [jsxgraph/jsxgraph#312]
I'm looking for the easiest way to get notified when an element on a board updates itself. 

There is a [wiki example](https://jsxgraph.uni-bayreuth.de/wiki/index.php/Adding_events_2) where you can attach the `update` event to an element, e.g: 

```js
   var p = board.create('point',[1,1]);
   p.on('update', function(e, i){ /* do something ... */);
```

However this does not seem to work when I try it out myself. When checking the [Reference API](https://jsxgraph.uni-bayreuth.de/docs) I can see that the a [`Board`](https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.Board.html#event:update) accepts the event, but a [`GeometryElement`](https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.GeometryElement.html) (like the point in the example) doesn't. 

Is this a feature that got removed? If so what would be the easiest way to get notified when an element updates itself? One way I can think of is to use the `board.on('update', () => {})` and check all elements on the board, but maybe I'm missing something and there is a smarter way to do it.  

In fact there is an issue #100 from 2014 addressing this too, but it has no replies.

**Comment by alfredwassermann** [comment]
Thank you for pointing this out. Indeed, this information is outdated. 
'update' is not triggered for JSXGraph elements, but it is triggered for the coords sub-object.
Therefore, 

    p.coords.on('update', function(e, i){ /* do something ... */);

may be the right event handler for you.

**Comment by Sjiep** [comment]
That works, thank you!
