### ISSUE TITLE
Scatter plot

### ISSUE THREAD

**Issue by tlienart** [jsxgraph/jsxgraph#314]
Hello,

Is there a way to do a scatter plot? I.e. a data plot except only the points are drawn, not the connecting line. The `dash` option seems to only be for the connecting line.

One way I could do it is by having lots of `brd.create('point', ...)` but it didn't seem like a great way to do it. 

Thanks

PS: this package is awesome.

**Comment by alfredwassermann** [comment]
The most lightweight way to construct a scatter plot I can imagine is to (ab)use the JSXGraph curve object like this: each data point is stored twice in the coordinate arrays, followed by NaNs. The NaNs interrupt the stroke line. With `strokeWidth` you can control the size of the points.
The following example creates 100 random points between -4 and 4 (in both directions):

    var i, x, y, 
        x_arr = [], 
        y_arr = [];
    for (i = 0; i < 1000; i++) {
        x = Math.random() * 8 - 4;
        y = Math.random() * 8 - 4;
        x_arr.push(x, x, NaN);
        y_arr.push(y, y, NaN);
     }
    var scatterplot = board.create('curve', [x_arr, y_arr], {strokeWidth: 3});

You can see it live at https://jsfiddle.net/6gk1odam/
