### ISSUE TITLE
Avoid scope leakage for pages with multiple boards

### ISSUE THREAD

**Issue by tlienart** [jsxgraph/jsxgraph#316]
Hello, sorry if  that's a dumb question.

If you have two boards on the same page each with a slider with name "a" (say), how do you make it such that the two don't clash? Or more generally how do you properly ensure that the scope of one of the boards doesn't interfere with the other? I tried wrapping the scope of the board in a function (IIFE) but that didn't work as expected (I'm not very familiar with Javascript) and I ended  up with a board with only some of the objects present on it. 

Thanks!

**Comment by alfredwassermann** [comment]
This is a general JavaScript question and the - well known - solution are so called closures. Have a look at the following piece of code:

    (function(divID) {
        var board = JXG.JSXGraph.initBoard(divID, {/* ... */});
        var a = board.create('point', [0, 0]);
    })('jxgbox');

What you see is an anonymous function which has as parameter - just as an example - the ID of the div element in which the construction is shown.

    function(divID) {
        var board = JXG.JSXGraph.initBoard(divID, {/* ... */});
        var a = board.create('point', [0, 0]);
    }

The parenthesis around that function have the effect that this function is executed immediately. Moreover, the variables inside of the function are local and not visible from outside. Therefore, the two variables `a` in the next example are completely independent from each other.

    (function(divID) {
        var board = JXG.JSXGraph.initBoard(divID, {/* ... */});
        var a = board.create('point', [0, 0]);
    })('jxgbox1');
    (function(divID) {
        var board = JXG.JSXGraph.initBoard(divID, {/* ... */});
        var a = board.create('point', [0, 0]);
    })('jxgbox2');

Best wishes,
Alfred

**Comment by tlienart** [comment]
Thanks a lot

**Comment by tlienart** [comment]
I apologise for reopening the question but there's something I don't get, the following code seems to have leakage between the two sliders. Specifically the first slider doesn't work. If you comment out the second board, then it works as expected. If you rename the sliders to have distinct names, both boards will work fine. 

What am I missing?

Thanks!

##

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="jsxgraph.css">
   <script src="jsxgraphcore.js"></script>
</head>
<body>

  <div id="b1" class="jxgbox" style="width:300px; height:300px"></div>

  <script>
  (function(){
    b1=JXG.JSXGraph.initBoard("b1",{"boundingbox":[-2,2,2,-1]});
    a=b1.create('slider', [[-1.0,1.5],[1.0,1.5],[0.0,1.5,3.0]], {});
    function foo(x){return a.Value()*x*x-1};
    b1.create('functiongraph', [function(t){return foo(t);}, -2, 2]);}
  )();
  </script>

  <div id="b2" class="jxgbox" style="width:300px; height:300px"></div>

  <script>
  (function(){
    b2=JXG.JSXGraph.initBoard("b2",{"boundingbox":[-2,2,2,-1]});
    a=b2.create('slider', [[-1.0,1.5],[1.0,1.5],[0.0,1.5,3.0]], {});
    function foo(x){return -a.Value()*x*x+1};
    b2.create('functiongraph', [function(t){return foo(t);}, -2, 2]);}
  )();
  </script>


</body>
</html>
```

**Comment by tlienart** [comment]
Hmm I solved the issue by adding `var ` in front of the slider definitions... Javascript is a bit of an odd language to me! apologies for the spam.
