### ISSUE TITLE
curve disappears

### ISSUE THREAD

**Issue by gsturr** [jsxgraph/jsxgraph#324]
When my container div has width 600px, height 600px, this curve disappears with slider value k < 639:

var brd = JXG.JSXGraph.initBoard('jxgbox', { axis: true, boundingbox: [0, 5000, 5000, 0] });
var k = brd.create('slider', [[100, 4000], [1000, 4000], [500, 600, 700]]);
var c = brd.create('curve', [
    function (t) { return t; },
    function (t) { return -k.Value() + (t * t) / (4 * k.Value()); },
    -5000, 5000]);

Notes:  
1. Size of div matters. A smaller div needs smaller k to get same behavior. 
2. Changing bounding box to  [-1, 5000, 5000, 0] removes the problem. 
3. Problem occurs with v1.1.0 but not v0.99.7

**Comment by alfredwassermann** [comment]
Many thanks! Your error analysis helped to fix a long standing bug in the root finding algorithm of JSXGraph.
