### ISSUE TITLE
polynomial function cannot be plotted

### ISSUE THREAD

**Issue by nioate** [jsxgraph/jsxgraph#329]
When trying to plot the function f(x)=127.086+68.906x+13.125x^2+0.833x^3 into a board from -10 to 10 in both x and y, the graph does not show up.
When changing the coefficients a bit or changing the range of the board to +-11, the function does show up.
Very strange... maybe some sampling problem?

The code [http://jsfiddle.net/w34vjfbd/1/](http://jsfiddle.net/w34vjfbd/1/):
```
var board = JXG.JSXGraph.initBoard('box', {boundingbox:[-10,10,10,-10], axis:true, grid: true});
var k=[127.086,68.906,13.125,0.833];
board.create("functiongraph", [function(x) { 
  var y=0;
  for (var i=k.length-1; i>=0; i--) y=y*x+k[i];
  return y;
}]);
```

**Comment by alfredwassermann** [comment]
Thank you for pointing this out. Indeed, this is happens in v1.1.0 and before.
Luckily, this issue has already been fixed (by b786850aa19497e4bb1e20f6caccbc10182e77eb ?). Please check a nightly build.
