### ISSUE TITLE
Having trouble with various jessiecode exampels

### ISSUE THREAD

**Issue by jaltekruse** [jsxgraph/jsxgraph#335]
Hello jsxgraph Devs!

I would like to start by saying I'm very excited looking at what is possible with your library.

I am trying to look at getting started, and I was looking at the two options for serializing the state of a jsxgraph for later editing. Jessiecode looks great, but I'm having trouble getting examples working. Happy to help improve the docs, but I'm not quite sure what might have changed in the API to make these demos not work.

This one just doesn't load

![image](https://user-images.githubusercontent.com/365366/102720109-e5fddc80-42b7-11eb-9cc6-b574748015c6.png)

This one shows in the wiki, but when I try to copy the code to jsfiddle it has the same error as above.

![image](https://user-images.githubusercontent.com/365366/102720186-82c07a00-42b8-11eb-8eec-df5274727e53.png)

![image](https://user-images.githubusercontent.com/365366/102720209-a4216600-42b8-11eb-9ff2-e906eb72dfc8.png)

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. Several years ago, we discontinued the development of JessieScript in favor of JessieCode. Therefore, JessieScript is not longer contained in jsxgraphcore.js and you have to load the file jessiescript.js separately, see the updated page https://jsxgraph.org/wiki/index.php/Interactive_JessieScript. 
I also fixed the broken link to the documentation.
