### ISSUE TITLE
Arrow extends beyond end point while hovering over it.

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/jsxgraph#336]
Arrows can be made to only touch the last point with the option `touchLastPoint`. However, if the strokeWidth is greater than 2, the arrow extends beyond the end point when the cursor hovers over the arrow.

This can be seen, for example, in https://moodle.itemspro.eu/mod/quiz/view.php?id=1327

**Comment by alfredwassermann** [comment]
Thank you much for pointing this problem out. Fortunately, this bug is already fixed. Please, check a recent nightly build. 
Best wishes,
Alfred
