### ISSUE TITLE
setDisplayRendNode(val: boolean) broken? showElement(), hideElement() working but deprecated.

### ISSUE THREAD

**Issue by stemcstudio** [jsxgraph/jsxgraph#345]
I'm having trouble replacing the showElement(), hideElement() calls with the corresponding setDisplayRendNode(true or false) calls, which apparently fail. The results appear similar in version 1.1.0 and 1.2.1.

CODE:

    const board = JXG.JSXGraph.initBoard('jxgbox', {
        axis: true,
        boundingBox: [-6, 6, 6, -6],
        showCopyright: true,
        showNavigation: true,
        showFullscreen: true,
        showScreenshot: true
    })

    const A = board.create('point', [0, 0], { color: 'red' })
    const B = board.create('point', [5, 0], { color: 'green' })
    const C = board.create('point', [0, 5], { color: 'blue' })
    
    A.setDisplayRendNode(false) // does not work
    // A.hideElement() // works

    const circle = board.create('circle', [A, B], { dash: 5, strokeWidth: 1, strokeColor: 'purple' })
    // circle.hideElement() // works
    circle.setDisplayRendNode(false) // does not work

    const angle = board.create('angle', [B, A, C], { radius: 3 })
    const slider = board.create('slider', [[-2, 1], [2, 1], [0, Math.PI * 0.5, 2 * Math.PI]])
    slider.setDisplayRendNode(false) // works but value still visible
    // slider.hideElement() // works but some parts still visible

    angle.setAngle(function() {
        return slider.Value()
    })
    angle.setDisplayRendNode(false) // works but alpha label still visible.
    // angle.hideElement() // works

LIVE EXAMPLE ON STEMCSTUDIO

https://stemcstudio.com/gists/a36cfcf8825735ae125b494ae6a5278a

**Comment by alfredwassermann** [comment]
OK, I will remove the deprecation of `hideElement` and `showElement` and introduce shortcuts `hide()` and `show()`. Further, the methods are not longer declared `private`. The private method `setDisplayRendNode()` has a slightly different purpose and is still used internally.
