### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by stefnotch** [jsxgraph/jsxgraph#351]
It'd be really nice if this project had Typescript type definitions, like most modern libraries out there

**Comment by alfredwassermann** [comment]
There is a good chance that Typescript type definitions will be available next week. Then, David Holmes from https://stemcstudio.com/ will contribute his Typescript type definition for JSXGraph.

**Comment by alfredwassermann** [comment]
Typescript type definitions are available in v1.2.3
