### ISSUE TITLE
straightFirst & straightLast on perpendicular leads to weird result

### ISSUE THREAD

**Issue by HenrikFrtz** [jsxgraph/jsxgraph#357]
The perpendicular line has a wrong length and is shown in a pretty wrong place if straightFirst & -Last is set to false.

**See JSFiddle example:**
[http://jsfiddle.net/3w10v8dq/4](http://jsfiddle.net/3w10v8dq/4)

**Comment by alfredwassermann** [comment]
Thank you for pointing this out! However, this is a feature, not a bug.
What you probably want is `perpendicularsegment`, see jsfiddle.net/609rm5uv/ as an update of your example by

    perp1 = board.create('perpendicularsegment', [l1, p3],  {strokeColor:'red'});

The internal algorithms for `perpendicularsegment ` and `perpendicular` are different. The main difference is, that in the latter case, the defining point may also be on the defining line.

Best wishes,
Alfred

**Comment by HenrikFrtz** [comment]
This was exactely what I was looking for, thanks!! Haven't read the doc till this element and found it now 👍🏻
