### ISSUE TITLE
Keyboard interaction

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#359]
It doesn't seem that JSXGraph has any built in means of keyboard interaction for draggable elements. 

A minimum level of interaction would be, when using the SVG renderer, for draggable elements to be focusable with the keyboard, and pressing the arrow keys would move them, either snapping to the grid, or with some acceleration based on how long the key has been pressed.

Has anyone had a go at this? I can hack in the basics of this by adding `tabindex` attributes to SVG elements corresponding to draggable objects, but I don't have the time to look into building this into the renderer.

**Comment by alfredwassermann** [comment]
This is a very valuable suggestion and in fact it is on our TODO list for the next few weeks. 
Best wishes,
Alfred

**Comment by alfredwassermann** [comment]
A first version should work now - starting from d73faa43f0fae146820b094fe096877e520d15af in branch 1.2.4.

- Use arrow keys to move object with focus (selectable by tab)
- Use Shift/Ctrl + arrow keys to alter visible area (i.e. to pan). Shift / Ctrl depends on the configuration of panShift and panCtrl.
- dx, dy are the step widths in pixel (default is 10).

Example:

~~~
<div id="jxgbox" class="jxgbox" tabindex="0" style="width: 600px; height: 600px;"></div>
<script type="text/javascript">
var board = JXG.JSXGraph.initBoard("jxgbox", {
    boundingbox: [-5,5,5,-5], 
    axis: true, 
    keyboard: {
        enabled: true,
        dy: 30,
        zoomShift: true,
        zoomCtrl: false
    }
});
var p = board.create('point', [1,1]);
</script>
~~~

**Comment by christianp** [comment]
That works well, thanks!

**Comment by christianp** [comment]
I came here to close this, now keyboard navigation is in version 1.3, but I've thought of an improvement: it'd be nice if the coordinates of the object being moved were shown during keyboard navigation, like they are when using the mouse.
I think this means that focusing with the keyboard should trigger the 'hover' behaviour, but I don't know enough about how JSXGraph handles that to know is that's the right thing to do.

**Comment by alfredwassermann** [comment]
Good suggestion! I just submitted an implementation of that feature to the master branch.

**Comment by christianp** [comment]
Great! That works. I'll close this, but I'm about to file another keyboard-related issue...
