### ISSUE TITLE
slopetriangle: attribute "toppoint" is misspelled in reference

### ISSUE THREAD

**Issue by mputzi** [jsxgraph/jsxgraph#361]
Dear Alfred and JSXGraph-Team,
In the reference for the slope triangle the attribute referred to as "topPoint" should be spelled "toppoint" (all lower case), because "topPoint" doesn't work. ;-)
Or maybe topPoint and basePoint as well should be in camel case.
Kind regards,
Martin.

**Comment by alfredwassermann** [comment]
Fixed by 2a7d52018d3346a836ec31218a50fd99c4998549

Dear Martin, 
many thanks for the bug report,
Alfred
