### ISSUE TITLE
Problem with Math.Clip.union

### ISSUE THREAD

**Issue by mkraska** [jsxgraph/jsxgraph#362]
Hello, when combining curves using Math.Clip.union() I experience problems when the resulting shape has internal holes.

The following image shows the union of four rectangles, The left one is ok, the right one has the hole filled, which is wrong.

![image](https://user-images.githubusercontent.com/12987918/123298291-a4751500-d518-11eb-8993-9dc39a8ecdce.png)

[Jsfiddle](https://jsfiddle.net/1Lqyghb5/)

Martin

**Comment by alfredwassermann** [comment]
Dear Martin,
interestingly enough, the union path for this example determined by the JSXGraph clipping algorithm is correct. However,  the outcome of subsequent SVG fill algorithm is unexpected. The quick workaround in your example is to use a different fill algorithm for SVG:

        this.b = board.create('curve', JXG.Math.Clip.union( bneu, this.b, board), 
          {opacity: true, fillcolor:'lightgray', 
          strokeWidth: normalStyle.strokeWidth, 
          strokeColor: normalStyle.strokeColor});
          this.b.rendNode.setAttributeNS(null, 'fill-rule', 'evenodd');  // <-- workaround

This even-odd fill rule will also be the new default in the JSXGraph source code.
Best wishes,
Alfred

**Comment by mkraska** [comment]
Great, thanks a lot!
