### ISSUE TITLE
hasPoint not working for Text objects?

### ISSUE THREAD

**Issue by nioate** [jsxgraph/jsxgraph#363]
If I create a Text object at (0,0) and then evaluate hasPoint(0,0) on this object, the result is false.
```
const board = JXG.JSXGraph.initBoard('jxgbox', { 
    boundingbox: [-5, 5, 5, -5], axis:true
});
var t=board.create("text",[0,0,"Hello"]);
alert(t.hasPoint(0,0));
```
Is there anything wrong with my code, or is hasPoint not working for Text objects?

**Comment by alfredwassermann** [comment]
The `hasPoint` method expects screen coordinates as input. So, if e.g. the JSXGraph div has size 500 x 500, the call of

    alert(t.hasPoint(250, 250));

will return `true`.
