### ISSUE TITLE
keep dragging point when finger/mouse goes outside the board

### ISSUE THREAD

**Issue by appeye** [jsxgraph/jsxgraph#365]
Hey, 
When a user is dragging around a point and the finger goes off the edge of the board the point is frozen until the the finger/mouse enter the board again. This makes it a bit hard to interact with smaller graphs, or if sliders are positioned close to the edges. Would it be possible to allow for the user to keep moving the point even with the finger/mouse outside of the board and the point would still follow but along the edge of the board (or line if a glider point).

**Comment by alfredwassermann** [comment]
Commit 4a497ece2499ba621d0dae816048b3408b228c8d in 1.2.4 introduced the board attribute moveTarget.
For example

    moveTarget: document

would solve your request.
Many thanks for the suggestion!
