### ISSUE TITLE
Point Face 'triangleleft' Error with canvasrenderer

### ISSUE THREAD

**Issue by pratheeshrussell** [jsxgraph/jsxgraph#366]
My requirement is to copy the board canvas onto another canvas. For this, I enabled the `renderer:'canvas'` option. However when I draw a point and set the `face:'triangleleft'` I get an error 
`jsxgraphcore.js:78 Uncaught TypeError: this.fill is not a function`  
I don't get this error for any other point face, even `face:'triangleright'` works properly. A minimal example is shown below

```
var board= JXG.JSXGraph.initBoard('jxgbox',{boundingbox:[-10,10,10,-10],axis: true,renderer:'canvas'});
// this will work
var o = board.create('point', [1, 5],{face:'triangleright'}); 
//fails
var p = board.create('point', [1, 3],{face:'triangleleft'});
```

![image](https://user-images.githubusercontent.com/14904051/127025813-2c215f80-95c8-4cbe-8adc-d7efeb9b6e40.png)

**Comment by alfredwassermann** [comment]
Many thanks. Perfect bug report.
