### ISSUE TITLE
Text#cssStyle

### ISSUE THREAD

**Issue by Bejagui** [jsxgraph/jsxgraph#371]
Hi.
(subject 2)
I am trying to create bold (strong) text; but I couln't.
I tried with  strokeWidth but the text doesn't change
          var Per = Plano.create('text', [1, 1, function() {return "Per = "+Pol.Perimeter();}], {fontsize:22, strokeWidth: 3} );
I read the text format can be changed with Text#cssStyle but I could't find the way to use it.  Can you give me an example or a link whera I can see examples, please?

Thanks

**Comment by Bejagui** [comment]
Hi Andreas.

I am not a programmer, I am a teacher making questions in Moodle formulas question type. You helpped me creating an simple basic model or template example. With that, i have created beautifull questions. I am happy wth Moodle, wth formulasQT and now wth JSXGraph.

I usually read documents and examples and I can do some things. But sometimes, i can't understand concepts and i don't have any idea about solutions because i don't unsderstand how is the way. Thats the reason that i apreciate your example and your time.

Thanks

**Comment by Bejagui** [comment]
By the way, the same thing happened to me with
Math.trunc (x) and Math.round (x, 2)

I did not know that that existed. I assume it is Java Script; but i don't know java script. I was looking for something in the JSXGraph documentation and there was nothing about the "round" function.

**Comment by andreas-web** [comment]
Dear Bejagui!

I am very happy that I could help you. If you have any further questions, just contact us! Our JSXGraph conference may also be something for you. A lot of interesting things about JSXGraph are presented there. There are many expert tools involved, but beginners can also learn something from them. The next digital conference will take place from October 5th to 7th, 2021. Further information here:
https://jsxgraph.org/conf2021/
You can find the videos of last year's conference here:
https://www.youtube.com/playlist?list=PLr10cPSXxWJeffIACvr3mdX-KjvoJ8o86

Regards,
Andreas
