### ISSUE TITLE
z-index for images

### ISSUE THREAD

**Issue by Porizm** [jsxgraph/jsxgraph#377]
Hello,

Is there a way to put images above the grid?

![Simulator Screen Shot - iPhone 5s 10 - 2021-09-28 at 16 37 02](https://user-images.githubusercontent.com/2933548/135098306-231f9573-999e-4f55-a8be-39f14ca72826.png)

I went to documentation and couldn't find a setting to do it.

Thank you in advance

**Comment by alfredwassermann** [comment]
Yes, there is. By default images are in layer 0. You can put an image in any of the 20 layer like this:

    var im = board.create('image', [url, coords, size], {layer: 3});

By default, axes are in layer 2.
