### ISSUE TITLE
Points with property fixed:true is still moving

### ISSUE THREAD

**Issue by Porizm** [jsxgraph/jsxgraph#379]
Hello,

I have this strange behavior from points.

Setting point property fixed:true & snapToGrid:true is still making it move on touch when it reaches the edge.

Please see the attached video:

https://user-images.githubusercontent.com/2933548/135443228-187020e5-19c7-4db5-8159-6dd1a6cd8cdc.mov

Here's the script:

    app.board.create('point', [0, 0], { fixed: true, snapSizeX: 1, snapSizeY: 1, snapToGrid: true, size: 8, strokewidth: 5, fillColor: "#09f" })

This behavior also applies to image object with fixed:true & snapToGrid:true

Thank you in advance

**Comment by alfredwassermann** [comment]
Many thanks for pointing this out. It should be fixed with the next commit.
