### ISSUE TITLE
Intersection between circle and ellipse (or any curve)

### ISSUE THREAD

**Issue by Porizm** [jsxgraph/jsxgraph#382]
Hello,

I want to show intersection points between ellipse and circle but it's not working.

I tried with intersection object:

    // ellipse
    var A = app.board.create('point', [0, 4], { visible: false });
    var B = app.board.create('point', [0, -4], { visible: false });
    var C = app.board.create('point', [1, 0], { visible: false });
    var el = app.board.create('ellipse', [A, B, C]);
    
    // circle
    var circle = app.board.create('circle', [[0, 0], [2, 0]]);
    
    // intersection
    var i = app.board.create('intersection', [circle,el, 0])

Here's the output (intersected point is 0,0):
![s1](https://user-images.githubusercontent.com/2933548/135640041-5d4ecb3d-4bd1-454e-ad9d-14c67729c219.png)

Then tried with JXG.Math.Clip.intersection:

    // ellipse
    var A = app.board.create('point', [0, 4], { visible: false });
    var B = app.board.create('point', [0, -4], { visible: false });
    var C = app.board.create('point', [1, 0], { visible: false });
    var el = app.board.create('ellipse', [A, B, C]);
    
    // circle
    var circle = app.board.create('circle', [[0, 0], [2, 0]]);
    
    // intersection
    var clip_path = app.board.create('curve', [[], []], { strokeWidth: 3, fillColor: 'yellow', fillOpacity: 0.3 });
    clip_path.updateDataArray = function() {
        var a = JXG.Math.Clip.intersection(el, circle, this.board);
        this.dataX = a[0];
        this.dataY = a[1];
    };
    app.board.update();

And got this:

![s2](https://user-images.githubusercontent.com/2933548/135640225-33c2523b-b37e-4e43-bef5-aa2df0939ec9.png)

Is there a method to get the intersected points from JXG.Math.Clip.intersection ?

The ellipse contains 380 points, can i get intersected points from them?

Thank you in advance.

**Comment by alfredwassermann** [comment]
Thanks a lot for this bug report!
