### ISSUE TITLE
Issue with intersection points

### ISSUE THREAD

**Issue by Porizm** [jsxgraph/jsxgraph#386]
Hello,

I am trying to catch intersection points between a segment and a circle made using curve.
The points are showing even when using alwaysIntersect:false and the segment is not near the edge of the curve.

Here's the script:

    // Circle
    var p1 = app.board.create("point", [0, 0], { visible: false })
    var p2 = app.board.create("point", [4, 0], { visible: false })
    var c = app.board.create('curve', [
        function(t) {
            return p1.X() + p1.Dist(p2) * Math.cos(t)
        }.bind(this),
        function(t) {
            return p1.Y() + p1.Dist(p2) * Math.sin(t)
        }.bind(this),
        0,
        Math.PI * 2
    ], { fixed: false, strokeColor: "#333" });
    c.setParents([p1, p2])

    // Segment
    var s = app.board.create("segment", [
        [-1, -1],
        [-1, 1]
    ])

    // intersection points
    app.board.create('intersection', [c, s, 0], { alwaysIntersect: false })
    app.board.create('intersection', [c, s, 1], { alwaysIntersect: false })

Here's the output:

![Screen Shot 2021-10-12 at 5 48 41 PM](https://user-images.githubusercontent.com/2933548/136978871-67381749-cac7-4c9d-bb6d-22f57bb1a91f.png)

Thank you in advance.

Edit: jsxgraph nightly is not minifying jsxgraphcore.js in last build

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing it out.
