### ISSUE TITLE
Regression of JSXGraph element 'tangent'.  August 13

### ISSUE THREAD

**Issue by Cleonis** [jsxgraph/jsxgraph#388]
From nightly build 2021-08-12 to nightly build 2021-08-13 there appears to have been a regression of the element 'tangent'.

https://jsfiddle.net/Cleonis/2rmq51gh/
Uses:
https://jsxgraph.uni-bayreuth.de/~michael/jsxgraph-nightly/2021-08-12.2000/jsxgraphcore.js
Build 2021-08-12 updates both position and angle of the line as the glider is moved along the curve.

https://jsfiddle.net/Cleonis/76rnot8e/
Uses:
https://jsxgraph.uni-bayreuth.de/~michael/jsxgraph-nightly/2021-08-13.2000/jsxgraphcore.js
Build 2021-08-13: the *position* of the line is updated, showing that the repositoning of the glider is processed, but the *angle* of the line is not updated

**Comment by alfredwassermann** [comment]
Many thanks for the bug report. It should work now - hopefully without introducing new regressions. Gliders are complex objects...
