### ISSUE TITLE
I am confused   about oficial source code

### ISSUE THREAD

**Issue by Bejagui** [jsxgraph/jsxgraph#389]
Hi. I am a beeginer using jsxGraph in web pages.  I am reading and I found 2 links to work with that:

 1)   script type="text/javascript" src="https://jsxgraph.uni-bayreuth.de/distrib/jsxgraphcore.js"></script>

 2)  script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraphcore.js" type="text/javascript" charset="UTF-8"></script>

Is there a oficial link?  Thanks

**Comment by alfredwassermann** [comment]
If you want to have JSXGraph in your web page you have to incldue jsxgraphcore.js and jsxgraph.css. For this you have the following possibilities:

- Use local copies of these two files
- Use a CDN. At least two CDNs are hosting jsxgraph.
- Include the files from https://jsxgraph.org/distrib

Recommended are the first two options. For more details see https://jsxgraph.org/wp/download/index.html
