### ISSUE TITLE
Improve the maximum zoom-in/zoom-out

### ISSUE THREAD

**Issue by natelastname** [jsxgraph/jsxgraph#390]
Currently, how far it is possible to zoom-in/zoom-out in JSXGraph is determined by the following constants:
```
  // https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.Board.html#zoom
  min: 0.001        // minimal values of JXG.Board#zoomX and JXG.Board#zoomY, limits zoomOut
  max: 1000.0       // maximal values of JXG.Board#zoomX and JXG.Board#zoomY, limits zoomIn
```
Could these constants be adjusted so that it is possible to zoom out farther and zoom in closer?

**Comment by natelastname** [comment]
These limits on the maximum zoom-in/zoom-out are very small compared to what I suspect floating point is capable of handling. The maximum double is ~1.8×10^308.

**Comment by alfredwassermann** [comment]
The bounds on zooming can be supplied as attributes of the board. Here is an example with the default values:

    JXG.JSXGraph.initBoard('box', {
            zoom: {
                enabled: true,
                factorX: 1.25,
                factorY: 1.25,
                wheel: true,
                needShift: true,
                min: 0.0001,
                max: 10000.0,
                pinchHorizontal: true,
                pinchVertical: true,
                pinchSensitivity: 7
            },
            boundingbox: [-5,5,5,-5]
    }
