### ISSUE TITLE
Resize handling code occasionally freezes

### ISSUE THREAD

**Issue by natelastname** [jsxgraph/jsxgraph#392]
JSXGraph tends to freeze when the dimensions of the container are controlled by JavaScript and subject to rapid changes (e.g., when the size is changed in response to dragging the mouse.)

**JSFiddle**:   https://jsfiddle.net/natelastname/9zfuj6qp/34/

To reproduce this bug in this JSFiddle, randomly pan/zoom inside of JSXGraph and rapidly drag the slider to resize the window until the app freezes.

**Comment by alfredwassermann** [comment]
This is probably caused by the same problem as #393
