### ISSUE TITLE
Bounding box is corrupted on window resize

### ISSUE THREAD

**Issue by natelastname** [jsxgraph/jsxgraph#393]
When the size of the JSXGraph window changes, the bounding box does not change intuitively. 

JSFiddle: **https://jsfiddle.net/natelastname/fo0mhywv/3/**

This effect seems to be non-linear with respect to the coordinates of the point labeled "A" before the resize occurs.

To reproduce:
1. Zoom out and pan so that the user coordinates of the point A are around (500, 500)
2. Slightly move the slider to change the size of the JSXGraph window.
3. Observe that the coordinates of the point "A" have jumped by hundreds of millions of units.

**Comment by alfredwassermann** [comment]
Thanks a lot!
