### ISSUE TITLE
Problem with RegularPolygon

### ISSUE THREAD

**Issue by Porizm** [jsxgraph/jsxgraph#394]
Hello,

I am creating a square using RegularPolygon but there's a problem with point D, please see the video:

https://user-images.githubusercontent.com/2933548/140659026-92d0ba97-2493-4ff3-9575-61165e29a13e.mov

And here's the script:

        // points
        var p1 = app.board.create('point', [-2, 0]),
            p2 = app.board.create('point', [-2, 0]),
            p3 = app.board.create('point', [2, 0]),
            p4 = app.board.create('point', [2, 0], { fixed: false })

        // object
        app.board.create('regularpolygon', [p1, p2, p3, p4], {});

        // update
        app.board.update()

Also the same issue is happening with point D in JSXGraph Reference (first example):

https://jsxgraph.org/docs/symbols/RegularPolygon.html

One more thing,  JSXGraph is not being minified:
https://jsxgraph.uni-bayreuth.de/~michael/jsxgraph-nightly/2021-11-06.2100/

Is there another link for minified? I don't know where to get it or how to minify it! :(

Thank you in advance

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing this out. The problem is a regression introduced with setAngle.
Let's see how we can solve this...

The nightlöy builds should work again. Thanks!

**Comment by Porizm** [comment]
Hello,

Point C and D are not draggable anymore.

I think last 2 points are always fixed.

Is that how it's supposed to be or the issue still exists ?

Thank you

**Comment by alfredwassermann** [comment]
Yes, this is the intended behaviour, see versions 1.2.4--. It would be interesting to make the other points draggable, too.

**Comment by Porizm** [comment]
OK thank you.

I wish there's a feature to lock point with another point, I needed that in many places. Like for example dragging a point will make JSX act like am dragging another point.

**Comment by alfredwassermann** [comment]
Is this what you are searching for:

    var b = JXG.JSXGraph.initBoard('jxgbox', {boundingbox: [-1, 2.5, 14, -2.5]});
    var free = b.create('point',[0,0], {name:'A', size:3});
    var dep = b.create('point',[function(){ return free.X();}, 1], {name:'B', face:'[]', size:3});

See https://jsxgraph.org/wiki/index.php?title=Point#Dependent_points

**Comment by Porizm** [comment]
It's half the solution because I want both points to be draggable.

Your solution will link point dep with point free, but point dep will be fixed.
I want both points to be draggable and linked to each other at same time.

I tried to use event ondrag to manually update the other point using setPositionDirectly, but it wasn't giving me accurate coords.

**Comment by alfredwassermann** [comment]
Interesting idea! You can do something like this:

const board = JXG.JSXGraph.initBoard('jxgbox', { 
    boundingbox: [-5, 5, 5, -5], axis: true
});

    var A = board.create('point', [2, 2]);
    var B = board.create('point', [2, 1]);
    A.coords.on('update', function() {
        B.moveTo([A.X(), A.Y() - 1]);
    });
    B.coords.on('update', function() {
        A.moveTo([B.X(), B.Y() + 1]);
    });

It seems to me that this difficult to provide in general, because the functions have to be inverse to each other.

**Comment by Porizm** [comment]
yes, this will do what i need, I tested it, it's accurate.
Thank you very much
