### ISSUE TITLE
canvas dependency

### ISSUE THREAD

**Issue by hpb-htw** [jsxgraph/jsxgraph#396]
In version 1.3.2 I can use parcel to bundeln JSXGraph with other JavaScript files using `import`:

```javascript
import * as JSX from "jsxgraph";
```

After update to version 1.4.0 I got an error from parcel:

```
@parcel/core: Failed to resolve 'canvas' from './node_modules/jsxgraph/distrib/jsxgraphcore.js'
```

I just have a question: Binding canvas to JSXGraph is now the intension? If so, why is the package `canvas` not a dependency of JSXGraph in `package.json`?

System-Information:

```
JSPGraph 1.3.2 / 1.4.0
     NPM 8.1.0
  Parcel 2.0.0
```

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out!
A quick fix is to install canvas with `npm install --save-dev canvas`.

Actually, canvas is not really needed to use JSXGraph. However, before version 1.4.0 the canvas package has been bundled automatically to the JSXGraph npm package. We had needed it for unit testing with nodejs, where a headless canvas has been used. Starting with 1.4.0, we switched to karma / jasmine for unit testing and (mainly) use a headless chrome browser.

At the moment, if JSXGraph is included via nodejs, canvas is required, regardless if a canvas element is needed or not.
I have to check if this  line of code can be removed.

**Comment by hpb-htw** [comment]
`npm install --save-dev canvas` fixes the problem for my usecase. Thank your for the fast replay :)
