### ISSUE TITLE
setBoundingBox centers incorrectly when board aspect ratio is not one 

### ISSUE THREAD

**Issue by natelastname** [jsxgraph/jsxgraph#397]
The function `setBoundingBox` behaves awkwardly when the aspect ratio of the desired bounding box and the JSXGraph window are not compatible. In particular, `setBoundingBox` tends to arbitrarily offset the axes rather than prioritize centering.

JSFiddle: https://jsfiddle.net/natelastname/q6kzfx8s/30/

Steps to reproduce: 
1. Before doing anything, notice that the axes are not centered in the JSXGraph window immediately after start-up.  
2. Click the first button to trigger a call to `board.setBoundingBox([-10, 10, 10, -10], true);`. Notice that this does not put the origin in the center of the JSXGraph window. 
3. Click the second button to see the expected behavior. 

You can also use the slider to resize the window and observe that this problem is effected by the aspect ratio.

**Comment by alfredwassermann** [comment]
OK, there is now a fix in the sources. Would you be so nice to check today's nightly build or test it from the sources? 
Many thanks, Alfred

**Comment by natelastname** [comment]
Thank you so much for fixing this. I'd test this fix out in my project, but it will be some time before I have a chance to figure out how to use the nightly build instead of the npm package.

**Comment by alfredwassermann** [comment]
Using the nightly build together with the npm package is easy:
Just replace the files jsxgraphcore.js and jsxgraph.css in "node_modules/jsxgraph/distrib" with the files from the nightly build.

**Comment by natelastname** [comment]
> Using the nightly build together with the npm package is easy: Just replace the files jsxgraphcore.js and jsxgraph.css in "node_modules/jsxgraph/distrib" with the files from the nightly build.

Ok, thank you for the help. I have managed to set up the 2021-11-30.2100 nightly build. It looks like this issue (setBoundingBox not being centered) has been fixed. This is a great improvement, but it creates a different problem:

When the size of the window changes, JSXGraph centers the viewport on whatever location it was centered on when the board was created while preserving the aspect ratio of the axes. The way that it preserves the aspect ratio is perfect, but perhaps it is not desirable that the viewport's offset is lost. 

So, if the user pans the JSXGraph window, it should center on the location that they have panned to, not whatever it was when the board was created.

**Comment by alfredwassermann** [comment]
Thank you very much for your feedback. This issue should be fixed now. I hope this fix did not open up a new problem elsewhere... Could you please be so kind and test today's nightly build (will be created at 10pm CET), too?
Best wishes,
Alfred
