### ISSUE TITLE
Nested indexing fails - loop over array of index elements not executed properly

### ISSUE THREAD

**Issue by hwesterholt** [jsxgraph/jsxgraph#399]
Im trying to draw a directed graph, consisting of vertices and arcs.

First, I draw all the vertices. Their coordinates are given as an array of arrays; this may not be the cleanest way to do this, but coordinate calculation happens elsewhere (in `maxima`) where association lists are useful.

```js
const board = JXG.JSXGraph.initBoard('jxgbox', { boundingbox: [-5, 5, 5, -5], axis:true});
const coordinates = [[0, [- 2.83, - 2.83]], [1, [- 4.0, 0.0]], [2, [- 2.83, 2.83]], [3, [0.0, 4.0]],
                     [4, [2.83, 2.83]], [5, [4.0, 0.0]], [6, [2.83, - 2.83]], [7, [0.0, - 4.0]]];
var boardCoordinates = [];
const coordinatesLength = coordinates.length;
var i;
for (i = 0; i < coordinatesLength; i++) {
  boardCoordinates.push(board.create('point', coordinates[i][1]));
}
```
This part works like a charm:
![Screenshot from 2021-12-25 11-17-12](https://user-images.githubusercontent.com/62615938/147382915-753f8aea-cce9-4d7b-af2f-af0d5a8ad9b1.png)

Next, I would like to draw anti-parallel arcs between some pairs of vertices. I would like to loop over the given array of node pairs, *look up the coordinates of each node* and then draw a JSXgraph `arc` with an arrow tip at its end. The "looking up coordinates" part is where my code seems to fail. I would expect the following simple snippet to redraw all vertices that are the starting point of a directed arc (i.e. `0, 2, 4, 5, 6, 7`) - obviously, that is not what I want to do in the long run, but it is a useful example, I think:

```js
const antiParallelArcs = [[0, 5], [2, 4], [4, 2], [5, 0], [6, 7], [7, 6]];
var boardAntiParallelArcs = [];
const antiParallelArcsLength = antiParallelArcs.length;
var p1;
var i;
for (i = 0; i < antiParallelArcsLength; i++) {
  p1 = board.create("point", boardCoordinates[antiParallelArcs[(function(ii) {return () => ii;})(i)][0]]);
}
```

I tried to include closures for the index that I loop over (instead of using `boardCoordinates[antiParallelArcs[i][0]`) which is recommended in this [workshop document](https://jsxgraph.uni-bayreuth.de/webinar/advanced.pdf) (I think?). So far, this has not helped.

**Comment by alfredwassermann** [comment]
The problem with your code is that in 

     p1 = board.create("point", boardCoordinates[antiParallelArcs[(function(ii) {return () => ii;})(i)][0]]);

you try to extract coordinates to create the point(s) `p1`, but  the elements of the array `boardCoordinates` are JSXGraph points. Drawing (straight) edges between the points is quite easy - you just have to supply references to the start and end point. Then you can even drag the points around and the edges adapt. Here is the complete code:

    const board = JXG.JSXGraph.initBoard('jxgbox', { 
        boundingbox: [-5, 5, 5, -5], axis:true
    });

    const coordinates = [[0, [- 2.83, - 2.83]], [1, [- 4.0, 0.0]], [2, [- 2.83, 2.83]], [3, [0.0, 4.0]],
                         [4, [2.83, 2.83]], [5, [4.0, 0.0]], [6, [2.83, - 2.83]], [7, [0.0, - 4.0]]];
    var boardCoordinates = [];
    const coordinatesLength = coordinates.length;
    var i;
    for (i = 0; i < coordinatesLength; i++) {
      boardCoordinates.push(board.create('point', coordinates[i][1]));
    }

    const antiParallelArcs = [[0, 5], [2, 4], [4, 2], [5, 0], [6, 7], [7, 6]];
    var boardAntiParallelArcs = [];
    const antiParallelArcsLength = antiParallelArcs.length;
    for (let i = 0; i < antiParallelArcsLength; i++) {
      let edge = antiParallelArcs[i];
      board.create("segment", [
      	boardCoordinates[edge[0]], 
        boardCoordinates[edge[1]]],
        {
        	lastArrow: true
        });
    }

See it live at https://jsfiddle.net/pu64152a/ 

Best wishes, Alfred

**Comment by hwesterholt** [comment]
Huh! Thanks for pointing out that `boardCoordinates` contains JSXGraph points, **not** coordinates - I got fooled by my very own variable names.

I’m 99.9% certain that this solves my issue and will close this issue as soon as I’ve implemented the needed fix.

Thank you very much and merry Christmas :)

Hermann
