### ISSUE TITLE
Points can't be dragged (v1.4.x, iOS Safari 12)

### ISSUE THREAD

**Issue by YDX-2147483647** [jsxgraph/jsxgraph#415]
Points can't be dragged on iOS Safari 12.

[v1.2.1](http://jsxgraph.uni-bayreuth.de/wiki/index.php?title=Restrict_points_to_limited_area), v1.3.1/2 works, but v1.4.0/1 don't.

Detail: The whole scene can be moved. When dragging a point, the point's color will change as expected.

Minimal example:

```javascript
const board = JXG.JSXGraph.initBoard('graph', { boundingbox: [-5, 5, 5, -5], axis: true })
const A = board.create('point', [-1, -1], {
  name: 'A',
  fixed: false, // this is default -- only to show it's not because of that.
})
```

---

The console says `r.Zstart.push(n[s][0]);` breaks because `r` doesn't have `Zstart`.
```
jsxgraphcore.js TypeError: undefined is not an object (evaluating 'r.Zstart.push')
- saveStartPos @ jsxgraphcore.js
- touchStartListener @ jsxgraphcore.js
```
(Note: I pretty-printed `jsxgraphcore.js`, so line numbers represent nothing and are removed. I didn't know `jsxgraphsrc.js` then.)

`console.log(r)`:

```
GeometryElement {needsUpdate: false, isDraggable: true, isReal: true, childElements: {…}, hasLabel: true, …}
No properties
```

On Edge latest (98), `r` is a simple JSON object, not [GeometryElement](https://jsxgraph.org/docs/symbols/JXG.GeometryElement.html):
```
{
    "num": 1,
    "X": 221, "Y": 236,
    "Xprev": null, "Yprev": null,
    "Xstart": [ -1 ], "Ystart": [ -1 ], "Zstart": [ -1 ]
}
```

iOS Safari 12 [doesn't support `PointerEvent`](https://caniuse.com/mdn-api_pointerevent). In `addEventHandlers`(`src/base/board.js`), the fallback depends on [`TouchEvent`, which isn't supported either](https://caniuse.com/mdn-api_touchevent).

```javascript
if (Env.supportsPointerEvents()) {
    this.addPointerEventHandlers();
} else {
    this.addMouseEventHandlers();
    this.addTouchEventHandlers();
}
```

(I've checked that latest Edge/Safari goes to `if`, but Safari 12 goes to `else`.)

Since everything works in v1.3.x, I guess there's something broken when migrating to `PointerEvent` in v1.4.x.

---

Besides, _Features_ on [website](https://jsxgraph.org/wp/index.html) said “Backward compatible down to IE 6”, which can become a burden nowadays. Maybe it's time to drop support for old browsers. This issue is just another reason for me to buy a new phone.

(Nonetheless, this project is really fantastic!)

**Comment by YDX-2147483647** [comment]
https://github.com/jsxgraph/jsxgraph/commit/f4dcc0a763c3f11e1b65735e681548988a2c132f commented in `src/base/board.js`:
> Since iOS 13, touch events were abandoned in favour of pointer events

I may check commits around that time later.

**Comment by YDX-2147483647** [comment]
The issue appears from https://github.com/jsxgraph/jsxgraph/commit/f9ecc3d9ea0b35211118b32d6d9b55b7ccbfc1ee . (I do a bisection on `distrib/jsxgraphsrc.js`)

**Comment by alfredwassermann** [comment]
Many thanks for the bug report! It is fixed now and will appear in today's nightly build. We will soon publish 1.4.2 to make JSXGraph usable on old iOS versions again.
Best wishes, Alfred

**Comment by YDX-2147483647** [comment]
It seems that I fix it in https://github.com/jsxgraph/jsxgraph/commit/f9ecc3d9ea0b35211118b32d6d9b55b7ccbfc1ee by changing `targets = [target_obj];` to `targets = [target];` (`touchStartListener` in `board.js`).

There's no `target_obj` there, maybe a typo.

**Comment by YDX-2147483647** [comment]
Oh… Anyway, the bug is fixed.  😃
