### ISSUE TITLE
JXG.Dump.toJessie produces invalid code for a slider

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#416]
[Here's a codepen demonstrating this problem](https://codepen.io/christianp/pen/NWwjgZN).

I added a slider to a board with the following JessieCode:

```
slider([0,0], [2,0], [1,1,12]);
```

When I dump the board to JessieCode, with `JXG.Dump.toJessie`, I get a very long line `s0 = slider(0, 0, "jxgBoard1L3") <<...`, and then another line creating a text element:

```
s1 = text(1, 2.1, 0, function(){return o.sanitizeHTML(t())}) <<...>> ;
```

I think this is the label of the slider. Its text is a function, referring to a function`t()` that doesn't exist. I assume that some internal function has been automatically serialized, and `t` was in an outer scope.

The first line with the call to `slider` is wrong, too: it seems to give `0` for the start and end points, instead of coordinates.

I haven't had time to look into the dump code myself yet to see how easy this would be to fix.

**Comment by alfredwassermann** [comment]
Yes, this is a bug. We will try to fix it soon.

**Comment by christianp** [comment]
Thanks!
