### ISSUE TITLE
Composition.add(what, element) throws "TypeError: i.on is not a function" when element is a Composition

### ISSUE THREAD

**Issue by geometryzen** [jsxgraph/jsxgraph#420]
The Composition add method claims to accept either a GeometryElement or a Composition. However, Composition does not support an on method. I'm not sure whether the correct solution is to have Composition gain the on method (presumably through the EventEmitter mix-in), or to guard the line "element.on('attribute:name', this.nameListener, this);" in Composition add with perhaps an if (element instanceof GeometryElement).

**Comment by stemcstudio** [comment]
Upon further investigation I am inclined to believe that the code in jsxgraph/extensions/square.js is not a working example. It appears to be too permissive by allowing the Composition constructor to take a map that may have values that are arrays of GeometryElement(s). Accordingly, I will be restricting the Composition constructor and the registerElement function in index.d.ts to only refer to GeometryElement or Composition. This issue may be closed if this assumption is correct.
