### ISSUE TITLE
is it possible to use JXG.Math.Numerics in JessieCode?

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#423]
A Numbas user has asked if it's possible to create a bezier curve in JessieCode. [The example in the wiki](https://jsxgraph.uni-bayreuth.de/wiki/index.php/Bezier_curves) uses `JXG.Math.Numerics`, but as far as I can see that isn't exposed in JessieCode.

Is there a plan for how to expose the numerics functions in JessieCode? Looking at the source, it seems that the built-in JS `Math` functions are special-cased, so is it just that nobody has got round to doing the same thing for JXG's math functions?

**Comment by alfredwassermann** [comment]
Yes, it is possible with the import function of Jessieode. Here is a working example for Bezier curves:

    num = import('Math/Numerics');
    A = point(3, 1);
    B = point(1, 1);
    C = point(1, 3);
    D = point(-1, 2);

    arr = num.bezier([A, B, C, D]);
    path = curve(arr[0], arr[1], arr[2]);

The problem is that num.bezier returns an array [X, Y, range], its members have to be given as parameters to the function curve().

**Comment by christianp** [comment]
Thank you very much!
