### ISSUE TITLE
Maybe use KaTeX instead of MathJax ?

### ISSUE THREAD

**Issue by holgerengels** [jsxgraph/jsxgraph#432]
Hi,

did you ever consider replacing mathjax with katex? Katex is a lot faster and smaler in size ..

https://www.intmath.com/cg5/katex-mathjax-comparison.php
https://github.com/KaTeX/KaTeX

Regards, Holger

**Comment by alfredwassermann** [comment]
JSXGraph already supports KaTeX, see https://jsxgraph.org/docs/symbols/Text.html#useKatex.
