### ISSUE TITLE
'o' letter is not working in input element

### ISSUE THREAD

**Issue by RKukharchuk** [jsxgraph/jsxgraph#437]
Typing 'o' letter in input element doing nothing.

**Comment by RKukharchuk** [comment]
Thank you very much @alfredwassermann.
I need keyboard navigation between elements, so after digging into the source code I found this solution:

`keyboard: {
        enabled: true,
        panShift: false,
        panCtrl: false
      }
`

**Comment by alfredwassermann** [comment]
You bug report made me rethink the logic. Now
- panning of the construction is done with arrow keys if the pan key (`shift` or `ctrl` - depending on the board attributes) is pressed.
- zooming is triggered with the keys `+`,` o`, `-`, if the pan key (`shift` or `ctrl` - depending on the board attributes) is pressed.
- keyboard control (move, pan or zoom) is disabled if an HTML element of type input or textarea has received focus.

Do you agree with it?
