### ISSUE TITLE
Bug: Slider outside range with snapWidth

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/jsxgraph#440]
I think there is a small bug with sliders when a snapWidth is set. When one presses the mouse button in order to move the slider and lets go outside the range of the slider, say farther to the right, the point gets dropped at the mouse's position. Only after clicking somewhere else on the canvas does the slider point get repositioned inside its original range.

See here: https://jsfiddle.net/FLeupold/61Lkxb23/154/

**Comment by alfredwassermann** [comment]
Many thanks for pointing this out!
This bug is caused by the same regression as bug #439. Luckily, the fix of #439 also fixes this problem.
