### ISSUE TITLE
JSON 2D Graphics interface for JSXGraph

### ISSUE THREAD

**Issue by axkr** [jsxgraph/jsxgraph#448]
## Proposal for a JSON `Graphics` interface for JSXGraph.

An example for a JavaScript library for rendering [Mathics](https://mathics.org/), [Symja](https://github.com/axkr/symja_android_library) (and eventually Wolfram Language) [Graphics3D](https://reference.wolfram.com/language/ref/Graphics3D.html) objects, can be found here:
https://github.com/Mathics3/mathics-threejs-backend

I would like to suggest creating a similar interface for rendering [Mathics](https://mathics.org/), [Symja](https://github.com/axkr/symja_android_library)  and [Wolfram Language 2D Graphics](https://reference.wolfram.com/language/ref/Graphics.html) primitive objects with JSXGraph as the basic library.

In the same sense as described here: [mathics-threejs-backend/issues/3](https://github.com/Mathics3/mathics-threejs-backend/issues/3)

For example the graphics primitive

```mma
Graphics[Line[{{0, 0}, {1, 1}, {0, 1}, {1, 0}}]]
```

can be exported to JSON format:

```mma
ExportString[Graphics[Line[{{0, 0}, {1, 1}, {0, 1}, {1, 0}}]],"ExpressionJSON"]
```
 
```json
[
 "Graphics",
 [
  "Line",
  [
   "List",
   [
    "List",
    0,
    0
   ],
   [
    "List",
    1,
    1
   ],
   [
    "List",
    0,
    1
   ],
   [
    "List",
    1,
    0
   ]
  ]
 ]
] 
```

**Comment by rocky** [comment]
I have been meaning to comment on this, but I haven't had time until now (after a long overdue Mathics suite release).

A slight correction on what has been presented so far.

We would _like_ to support as an option something like an S-expression of the WMA Graphics3D or Graphics expression as a possible input format to mathics-threejs-backend. However, this is not what we currently have now. 

Instead of a "long" format JSON or S-expression JSON, we have a "compact" version of this.

For example, the 3D analog to a line is ["tube"](https://mathics3.github.io/mathics-threejs-backend/primitives/tube) which as the compact representation:

```
{
    "type": "tube",
    "color": [1, 1, 1],
    "coords": [
        [[0, 0, 0]],
        [[1, 1, 1]]
    ]
}
```

We would like to have a translator on the javascript side to convert the S-expression to this compact form.

This  I don't believe is hard to do, I think I could write such a thing myself even though I am not a Javascript expert. It just hasn't been done.

**Comment by Haspeldor** [comment]
Thank you for bringing up this issue!

I'll be working on such a 2D Graphics interface for JSXGraph.
I've already read some of the documentation about the Graphics primitives, but I still have some questions.

Where can the ExportString function be called, and is there a recommendation for software that can be used to generate graphic objects for testing purposes?
Does symja already use these internally?

**Comment by axkr** [comment]
> Where can the ExportString function be called, and is there a recommendation for software that can be used to generate graphic objects for testing purposes?
> Does symja already use these internally?

Yes there is such an example for Graphics3D:
https://github.com/axkr/symja_android_library/blob/87cb8d7fa9a463513475d0ac31a109bb7a86c43f/symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/others/ExportImportFunctionsJUnit.java#L116

But I would like to recommend starting with static HTML pages and the simplest `Point` and `Line`  objects which should be rendered by a new JSXGraph function `drawGraphics2d`:

```mma
Graphics[Point[{{0, 0}, {1, 1}, {2, 2}, {3, 3}}]]
```

which Symja or Mathics will translate in an `iframe` with the following structure

```html
<!DOCTYPE html>
<html lang="en-US">

<head>
...
<!--  import JSXGraph library here -->
...
</head>

<body>
...
<div class="center" id="graphics-container"></div>

<script>
   drawGraphics2d(
        document.getElementById('graphics-container'),
        {
            elements: [
                {
                    type: 'point',
                    color: [0.5, 0.5, 0.5],
                    coords: [
                        [[0, 0]],
                        [[1, 1]],
                        [[2, 2]],
                        [[3, 3]]
                    ],
                    pointSize: 0.02
                }
            ] 
        }
    );
</script>

 
</body>

</html>
```

See the corresponding 3D pages:
* https://mathics3.github.io/mathics-threejs-backend/primitives/point
* https://mathics3.github.io/mathics-threejs-backend/primitives/line

**Comment by axkr** [comment]
See discussion on discord:
* https://discord.com/channels/869895703718166529/1037403598788775996

**Comment by axkr** [comment]
See github project:
* https://github.com/jsxgraph/json2D_JSXGraph
