### ISSUE TITLE
Reflection of function graph is not displayed properly when translated

### ISSUE THREAD

**Issue by sylee957** [jsxgraph/jsxgraph#449]
I have an example of drawing `y = x^2` graph and its reflection with respect to `y = x` line.
If both graphs are present in one screen, there is no problem

<img width="507" src="https://user-images.githubusercontent.com/34944973/181407648-949870ea-0c5c-49ad-a5df-0fc32744d45a.png">

but if translated to the right, it doesn't seem like JSXGraph recognizes that the graph exists in the specific range.

<img width="508" src="https://user-images.githubusercontent.com/34944973/181407664-2bd6c819-6227-4a72-925f-692f6b4c5647.png">

```HTML
<head>
    <link rel="stylesheet" type="text/css" href="https://jsxgraph.org/distrib/jsxgraph.css" />
    <script type="text/javascript" src="https://jsxgraph.org/distrib/jsxgraphcore.js"></script>
</head>
<div id="box" class="jxgbox" style="width:500px; height:500px;"></div>
<script type="text/javascript">
    var board = JXG.JSXGraph.initBoard('box', {boundingbox: [-10, 10, 10, -10], axis: true});
    var graph = board.create('functiongraph', [function(x){ return x*x;}]);
    var diagonal = board.create('line', [0, 1, -1]);
    var reflection = board.create('reflection', [graph, diagonal]);
</script>
```

**Comment by alfredwassermann** [comment]
The full parameter set to generate a function graph in the interval $[l, r]$ is 

    board.create('functiongraph', [func, l, r]);

In case the interval borders are not given, they are set to be a little bit outside of the visible area. This leads to the error you noticed. However, if you supply interval borders, the reflected curve should be OK. Here is a working example:

    var board = JXG.JSXGraph.initBoard('box', {boundingbox: [-10, 10, 10, -10], axis: true});
    var graph = board.create('functiongraph', [function(x){ return x*x;}, -5, 5]);
    var diagonal = board.create('line', [0, 1, -1]);
    var reflection = board.create('reflection', [graph, diagonal]);

Please, note that the reflection takes all points of the original curve and applies the transformation to them, no methods from calculus are used.
