### ISSUE TITLE
shadow issue

### ISSUE THREAD

**Issue by qurbi** [jsxgraph/jsxgraph#450]
Hi
If there are multiple jsxgraphs on a page, the "shadow" feature does not render properly on all - arbritarily, some rendering is lost. Please browse to https://www.i-learn.in/jsxgraph_shadow_issue.html, and scroll-down, scroll-up once or twice to observe.
This issue is in firefox only.
Looking forward to a resolution.
Thanks

**Comment by alfredwassermann** [comment]
Indeed, we can reproduce this issue with firefox in Linux. Unfortunately, it seems to be a problem in the browser's SVG engine and outside of the scope of JSXGraph. 

In some forums, people mention that SVG rendering problems in Firefox can be solved by tinkering with gfx.webrender in about:config. It did not help in my configuration, but I did not spend much time on it.

A very dirty hack - which solves the problem for me - would be to use an `IntersectionObserver` and set the visibility of the div's to 'hidden' for a short period of time. This forces the browser to render the construction again. The complete code, added at the end of your page, looks like:

~~~{.javascript}
let options = {
  rootMargin: '0px',
  threshold: 1.0
}

for (let i=1; i<11; i++) {
    let target = document.querySelector('#jxgbox_tr' + i);
    let callback = (entries, observer) => {
      entries.forEach((entry) => {
        entry.target.style.visibility = 'hidden';
        setTimeout(() => entry.target.style.visibility = 'visible', 5);
    });
  };
  let observer = new IntersectionObserver(callback, options);
  observer.observe(target);
}
~~~

**Comment by qurbi** [comment]
Appreciate your prompt response, Alfred.
Well, as for the hack, it would work on an html page, but since I have hundreds of questions (in moodle), this would not be feasible. Well then, the best to do, is to inform students not to use firefox :)
Thanks a lot.
