### ISSUE TITLE
[Feature request] Allow minor ticks to be labelled as well

### ISSUE THREAD

**Issue by wlewis-formative** [jsxgraph/jsxgraph#451]
Would you be interested in exposing an attribute that allows minor ticks to be labelled (alongside major ticks)? I'd be happy to work on the required changes if so. At the same time, I understand that this is a bit of a strange feature to add.

My reason for asking is that I'm trying to produce the following look:

<img width="418" alt="Screen Shot 2022-08-09 at 9 26 58 AM" src="https://user-images.githubusercontent.com/91909230/183658611-c2bea859-c6ff-4414-be3f-17de0a012f73.png">

Is there already a way to achieve this with the existing axis options?

**Comment by alfredwassermann** [comment]
This is a good suggestion and it was quick to implement. Today's nightly build will have the new ticks attribute `ticksPerLabel`. Here is an example. The only restriction at the moment is that label positions have to coincide with a tick (minor or major) position.
This is in contrast to your picture.

~~~
const board = JXG.JSXGraph.initBoard('jxgbox', {
    boundingbox: [-4, 4, 4, -4],
    axis: true,
    defaultAxes: {
        x: {
            ticks: {
                drawZero: true,
                minorTicks: 7,
                ticksPerLabel: 4,
                majorHeight: -1,
                minorHeight: 20,
                label: {
                    fontsize: 16
                }
            }
        },
        y: { 
            ticks: {
                drawZero: false,
                minorTicks: 3,
                ticksPerLabel: 2,
                majorHeight: -1,
                minorHeight: 20,
                label: {
                    fontsize: 16
                }
            }
        }
    },
    zoom: {
        wheel: true
    }
});
~~~

However, I'm not sure that `ticksPerLabel` is a good attribute name. If you have a better suggestion I would be happy.

**Comment by wlewis-formative** [comment]
@alfredwassermann thank you!

**Comment by alfredwassermann** [comment]
You mean, we keep the attribute name `ticksPerLabel`?

**Comment by wlewis-formative** [comment]
Yeah, I think `ticksPerLabel` is a fine name for it.

**Comment by wlewis-formative** [comment]
Thanks again, @alfredwassermann !
