### ISSUE TITLE
Integrals of Logarithmic Functions

### ISSUE THREAD

**Issue by davidf628** [jsxgraph/jsxgraph#458]
I tried to create an integral of the function ln(x), but it doesn't seem to be working. I created a minimal jsfiddle with the issue:
[https://jsfiddle.net/mqxfwtLe/](https://jsfiddle.net/mqxfwtLe/)

This seems to affect builds of 1.3.0 or newer, if you use a build earlier than that, then the ln(x) integral works as expected. Can you look into this and see what the issue might be?

**Comment by alfredwassermann** [comment]
Thanks a lot. The report was very helpful.
