### ISSUE TITLE
JSXGraph "touchstart" event and page scrolling on mobile issue

### ISSUE THREAD

**Issue by Chrisb0606** [jsxgraph/jsxgraph#461]
Hello,
I'm facing a ergonomic issue on mobile phone. I have several JSXGraph boards included in webpage (a kind of an article) with  text, images and many other standard web elements. When I read this article on a mobile phone and I want to scroll it with a finger it works excepting when I touch the JSXGraph board. It seems that the jsxboard catched the "touchstart" event and don't share it with the browser, thus the page doesn't scroll in this case anymore and the user doesn't get any visual feedback that explains this behavior.

To reproduce this issue, try to scroll the page by touching the board :  http://media-eleda.ouvaton.org/test/jsxgraph.html

Is there a mean to solve that ergonomic issue ?
Thanks
Chris

**Comment by alfredwassermann** [comment]
I just pushed an experimental solution with the new board attribute `browserPan`. You might try it out with today's nightly build. Here is an example:

```javascript
const board = JXG.JSXGraph.initBoard('jxgbox', {
    boundingbox: [-5, 5, 5, -5], axis: true,
    pan: {
        enabled: true,
        needTwoFingers: true,
    },
    browserPan: true,
    zoom: {
        enabled: false
    }
});
   
var p1 = board.create('point', [1, -1]);
var p2 = board.create('point', [2.5, -2]);
var li1 = board.create('line', [p1, p2]);
```
**Some remarks:**

- It needs a double tap on the board to be activated
- It only works with pointer touch devices - not with mouse, pen or old iOS touch.
- It only works if `browserPan:true`
- One finger action by the setting `pan.enabled: true` and `pan.needTwoFingers: false` has priority

One drawback is that browser pan,  JSXGraph pan and JSXGraph zoom are not possible simultaneously.

Please, give us feedback if it works good enough.

**Comment by alfredwassermann** [comment]
Implemented in b949d442ae70755b4369446aea7186b857e833d9

**Comment by Chrisb0606** [comment]
Thank you Alfred, I'll test it in a couple of weeks and feedback you.
Kind regards
Chris.

**Comment by Chrisb0606** [comment]
Sorry for the delay to test this experimental feature.
After a deep testing session, I think it's a really acceptable behavior. In a first reading I didn't understand what do you mean by It needs a double tap on the board to be activated. After several tests, I understood that I have to tap one time on the board then I can definitly move the html page by taping & sliding my finger on the board. 

In the end, I can browse/slide the whole html page both from outside the board and from inside the board.
More over it seems that there is no side effect on OS with a mouse.
Thanks a lot.
Chris
