### ISSUE TITLE
Proposal: ES6 Module Conversion?

### ISSUE THREAD

**Issue by sritchie** [jsxgraph/jsxgraph#464]
Hello!
I'm currently working on an integration between the [sicmutils](https://github.com/sicmutils/sicmutils) computer algebra system, written in Clojurescript, and JSXGraph.

Clojurescript pulls in javascript dependencies via NPM and processes them using Google's [Closure Compiler](https://developers.google.com/closure/compiler). The trouble is that this pipeline doesn't support AMD-style modules; this means that I'm unable to build code that references JSXGraph.

JSXGraph works beautifully if we convert all of the files from AMD style modules that use `define` over to proper ES6 modules, using an `import` statement in place of each dependency declared with `define`.

This is what the files look like after conversion: https://github.com/sritchie/jsxgraph/blob/amd_convert/src/math/clip.js#L44

In fact, I accidentally put up a PR converting the full project, if you want to take a look over at https://github.com/jsxgraph/jsxgraph/pull/463.

**To do this right would involve**

- converting the project to ES6 modules
- using webpack or some other bundler that you prefer to generate the files that currently live in `distrib`
- potentially adding a linter like Prettier with a paired Github Action enforcing its rules, to systematically undo all of the indentation that will be left over from the requirejs style.

**Concretely, my questions are:**

- What do you think of this idea?
- Would you take a PR making the conversion, or a few PRs sequencing this up?

A larger change that this would make possible would be converting many of the files to proper ES6 classes, but that's a bigger change outside the scope of this proposal.

I'd be thrilled to work on this, so please let me know what you think!

**Comment by sritchie** [comment]
There is a lovely project in the Clojure community called Clerk (https://github.com/nextjournal/clerk) that lets you drive computational notebooks, Jupyter style, from a source file; change anything inside the file and the notebook automatically re-renders, with intelligent caching etc.

After converting to ES6 modules I was able to embed an instance of JSXGraph into the rendered notebook:

![2022-10-11 15 42 43](https://user-images.githubusercontent.com/69635/195413441-bc25c22f-16bc-4fc7-9049-7867311d76f8.gif)

Just for some fun background, the next steps for this project are

- integrate with the computer algebra system I mentioned, so that we can write equations live in the browser and have the system respond, vs having to write Javascript
- integrate with the Mathlive equation editor: https://cortexjs.io/compute-engine/demo/
- Integrate with the Mathbox 3d rendering system, so that it becomes possible to write jsxgraph/mathbox visualizations like this: https://sam.zhang.fyi/2020/10/29/curve-shortening/, but that are interactive in the browser.

**Comment by alfredwassermann** [comment]
Thank you very much for your great work!!! 
It is definitely the right step into the future to transfer JSXGraph from AMD to ES6 and I'm very open to it. Moreover, you convinced me that using AMD is a showstopper for some project already now.

My suggestion is to pull your PRs into a new branch and test it there. The goal should be to release these patches in v1.5.0.

**Comment by sritchie** [comment]
Excellent, I'll redirect them now! Would you mind making a new branch for me to point to? I'll keep going and stage an ES6 branch now, so we can take a look at it together.

Thank you for being open to this!

**Comment by alfredwassermann** [comment]
OK, now there is a new branch "es6".

**Comment by sritchie** [comment]
Awesome, and thanks for merging! I'm close to pushing a proper ES6 branch now, give me a few minutes.

**Comment by alfredwassermann** [comment]
Great, first tests are very promising! Indeed awesome!
What I still have to check is if loading jsxgraphcore with requirejs still works in the various environments I'm aware of. Will take some time because of other commitments.-

Up to now only the following issues are a slightly annoying:

- First: in my development environment (i.e. a folder outside of the JSXGraph folder), there are files of the (new) form:

~~~
...
<div id="jxgbox" class="jxgbox" style="width: 600px; height: 600px;"> </div>
<script type="module">
import JXG from '../jsxgraph/src/index.js';
const board = JXG.JSXGraph.initBoard('jxgbox', {});
...
~~~

If I load these files from the web server, the imports of the form

~~~
import $__canvas from "canvas";
~~~

in canvas.js, env.js and jessiecode.js throw errors.  Can this be fixed without installing any node module in the development folder? Fact is, these imports should only be done if jsxgraphcore is called in a node environment.

- Second: it would be nice if the above file could be loaded directly from the file system. I know this is a CORS issue. But I'm surprised that this seems to be widely accepted by the community of JavaScript developers.

**Comment by sritchie** [comment]
@alfredwassermann hey, thanks for taking a look! \

## Your Questions

I'll see what I can do about the first issue, since of course we want to be able to use the library as a module within the browser if possible.

Another option for local development is to do what I did for the examples, and have them point directly at the generated `jsxgraphsrc.js`. This gets past the problem of loading files locally as well, AND the development experience is great since source maps still point you back toward the original files.

I can add a webpack task that watches the files and rebuilds `jsxgraphsrc.js` whenever a file changes' That should make things pretty seamless. What do you think?

About the second thing, I struggled with this on a previous project for a long time, and I think that the only solution that works is to add a node plugin that will start up a small local web server. That will get past the CORS issue and let us publish examples that use the module style.

### Remaining Tasks

- [ ] Lint errors. I didn't introduce anything new here, but it would be nice to get this build step passing by cleaning up the lint errors. I am happy to take a pass, but I would want a careful review here, as many of the errors trigger on mutable variables in some of the low level algorithms. Definitely don't want to break anything.
- [ ] Port the other builds, like JSXCompressor, over to webpack. This is easy and I can take a pass.
- [ ] Convert the "extensions" over to ES6 modules. Are these included in any builds right now? I don't see that they are... what we could do is move them into the source tree, OR just add them to the npm artifact. That way if someone pulls in the library via npm they can still depend on the ES6 module version and bundle the extensions up in their own code.
- [ ] Right now I don't produce any files that end up in `update_cdnjs`. What goes there? Is there some work to do?
- [ ] One thing that was broken by the Prettier formatter is this section of the Makefile:

```
# Filelists - required for docs, linters, and to build the readers
FILELIST=$(shell cat src/loadjsxgraph.js | grep "baseFiles\s*=\s*'\(\w*,\)\+" | awk -F \' '{ print $$2 }' | sed 's/,/.js src\//g')
```

I can either exclude that file from the code formatter, so that this still works, OR we can remove this pattern and lint everything in the src directory? Let me know what you think.

I think that will cover it. I'm also happy to add some info into the README, or some DEVELOPING file, about how to get the local web server running if we end up adding that. Let me know what you think about the above and I'll take a crack at the next steps here.

I'm also happy to jump on a voice or video call if that would be easier for wrapping this up. Thank you again for your support here on these changes!!

**Comment by alfredwassermann** [comment]
Many thanks for considering my beginner's questions on modules.

Regarding the remaining tasks:

- Lint errors: should be gone now. The only errors that are thrown are static boolean values like `if (false) {` used to comment out parts of the code.
- Port of jsxcompressor would be a nice thing to have! 
- Extensions: these are considered to be templates how to write new JSXGraph elements. These are not part of jsxgraphcore.js. Of course, a port to es6 would be good and probably easy to do. We would be very grateful if you could do this.
- `update_cdnjs` contains the latest release of jsxgraphcore.js and is updated whenever a new release is published, i.e. this folder is not affected by the es6 port. Actually, I'm not sure if this is still the right way to update cdnjs. 
- Makefile: It was good that you took out loadjsxgraph.js from being treated by prettier. Now this line of code works again. However, loadjsxgraph.js (which is our own prehistoric way to load - aka import - a list of javascript files, done in 2007) is going to be retired with the port to es6. Probably, the new index.js is a better source to get a list of all involved javascript files.

If it would suit you we could chat on video sometimes next week (starting from Tuesday).

**Comment by sritchie** [comment]
Next week sounds great, I can do anytime next Tuesday after 10am MST (I'm in Boulder, Colorado). My email is sam@mentat.org, want to pick a time and send me an invite whenever you're free?

I've taken care of most of the issues above in this PR: https://github.com/jsxgraph/jsxgraph/pull/469

Here are the lint errors and warnings I'm still seeing: https://github.com/jsxgraph/jsxgraph/actions/runs/3251273217/jobs/5336050610

I'm happy to do one more PR to clean those up and add flags to ignore the `no-constant-condition` that you mentioned.

Let me know if I can take on anything else; also please let me know if I can document anything for us in some new `DEVELOPING.md` file, or anything like that.

Cheers!

**Comment by sritchie** [comment]
@alfredwassermann , I'm around today for the next few hours if this time still works, let me know!

**Comment by alfredwassermann** [comment]
Sorry, yesterday I was too busy. What about today at 4:30 pm (CEST)? Can you send me a private email to  alfred.wassermann@uni-bayreuth.de ?

**Comment by alfredwassermann** [comment]
@sritchie, I would like to agree. I just tried to sync the two branches which turned out to be really difficult. But nevertheless, I'm afraid we still need a little bit more time to do the switch to es6.

**Comment by sritchie** [comment]
I think the thing to do, which I am happy to do, is to write a PR that applies by hand all changes that have made it into master (Vs trying for an automated merge). I can put this up in the next day or two.

**Comment by alfredwassermann** [comment]
If I made no errors (which can not be excluded at all) the two branches should be in sync now. But if you could check it too, it would be great.

**Comment by alfredwassermann** [comment]
Today some progress was made: with a small patch the output of webpack is running on IE11. In particular, I added `target: ['web', 'es5'],` to the file `webpack.config.js` and correct some minor issues with `patchForIE11.sh`. 

@sritchie Is it a problem for you if jsxgraphcore.js is es5 compatible?

@sritchie: It turns out to be very problematic to merge patches from the master branch to the es6 branch. The different code formatting  confuses git-diff. Could we stop auto-formatting of the code until es6 becomes master? Today, I had to take the whole file options.js from master and convert it to the es6 branch, because of this problem.

**Comment by sritchie** [comment]
@alfredwassermann that's fine with me! I think that makes great sense, to turn off auto formatting until the merge.

I think that's fine if we're es5 compatible; my code only pulls in the source files from the npm package, so the webpack build settings won't affect my project.

**Comment by alfredwassermann** [comment]
@sritchie The webpack output of the es6 branch now works perfectly (as far as I could test) in web browsers down to IE11. Very good! However, I want to enable JSXGraph also as a server module (again). 
The output of the master branch can be started on a server with the command

```nodejs test.js```

with `test.js`:

```
// Run JSXGraph on node:
// `nodejs test.js`
// master branch: both methods, import and require, do work
// es6 branch: both methods fail
import { JXG } from 'jsxgraph';
//JXG = require("jsxgraph");

console.log('version', JXG.version);
console.log("JXG.Math:", JXG.Math.gcd(9, 24));
```

and `package.json`:

```
{
  "name": "test",
  "description": "jsxgraph in node",
  "dependencies": {
    "canvas": "^2.10.2",
    "jsxgraph": "^1.4.6"
  },
  "type": "module",
  "engines": {
    "node": ">=0.6.0"
  }
```

I'm sure that there will be problems with `canvas` which can be probably solved. 
However, on the es6 branch, I can not even get `JXG` initialized - even if all the occurrences of `canvas` and  `$__canvas` are commented out.

The webpack config script of the es6 branch contains an experimental setting for node output, but it does not work.
Do you have some experience, how to solve this issue?

**Comment by sritchie** [comment]
@alfredwassermann I think I can help! The key here is that the modules in the `es6` branch are using the `export default` style:

https://github.com/jsxgraph/jsxgraph/blob/es6/src/index.js#L97

This means that the correct syntax for importing is (note no curly braces around `JXG`):

```js
import JXG from 'jsxgraph';
```

Here is some more detail: https://javascript.info/import-export#export-default

Give that a try and let me know if it works. I have been using the es6 branch from a server, so this definitely works.

Exciting stuff!

**Comment by alfredwassermann** [comment]
@sritchie Thank you very much, this was quite helpful. Indeed, the webpack config for the web browser works also in node. The following code successfully imports JSXGraph:

```
import $__jxg from '...../jsxgraphcore.js';
const JXG = $__jxg.default;
```

Is this the best possible solutions or are there abbreviations possible?

**Comment by sritchie** [comment]
Huh, I really would have imagined that `import JXG from "jsxgraph"` would work, since `package.json` declares `main` and `module`. Was that failing?

https://github.com/jsxgraph/jsxgraph/blob/es6/package.json#L6-L7

Let me know if you have a repro and I can test it out!

**Comment by alfredwassermann** [comment]
The compatibility patches for the es6 branch are nearly complete now. Meanwhile, JSXGraph can be used in

- web browser with `<script>` back to IE10
- as AMD module with `requirejs()`
- in nodejs (even with canvas plugin)
- with `import` (however it seems to be included as commonjs module)
- as webworker script

The main compatibility problem was that the webpack output of `export default JXG` in `index.js` is not compatible to previous JSXGraph versions for AMD and nodejs. The script `patchWebpackOutput.sh` handles these problems - at least for the unminified file `jsxgraphsrc.js`.  However, it introduces two new problems: 

1. patching the minified file  `jsxgraphcore.js` is fragile and should be avoided
2. It is a UNIX script using `sed` and excludes development on Windows (without the Linux subsystem)

@sritchie Can you recommend solutions

1. to execute this script `patchWebpackOutput.sh`  in webpack only on `jsxgraphsrc.js` before minifying?
2. to make the script platform independent?

**Comment by alfredwassermann** [comment]
Next step: `replace-in-file-webpack-plugin` does the job. 
Still unsolved: execute this plugin before optimization

**Comment by sritchie** [comment]
I should have time this morning to give this a look! I think I have some prior art on how we can wire this plug-in in before the minimization step.

**Comment by sritchie** [comment]
@alfredwassermann , here's the webpack plugin; I think this is working before minimization, correct, or am I wrong? https://github.com/jsxgraph/jsxgraph/pull/486/

If not let me know and I will try and see if we can add the terserplugin so it comes AFTER the first plugin.

**Comment by sritchie** [comment]
I ran a test where I put the plug-in explicitly inside the minimization step before Tercer, and the output file had no difference. I think we're good here, but I'm happy to push that change if we want to be really explicit and careful.

**Comment by alfredwassermann** [comment]
It may be that this plug-in isn't necessary at all anymore: I could express all but one patches as options in `webpack.config.js`. The only remaining patch is to replace `root['jsxgraphcore'] = factory(root["canvas"])` by `root['jsxgraphcore'] = factory()`. But I do not know if this patch is necessary at all. 

The goal is to make reduce JSXGraph's dependency on the canvas plug-in to the case when JSXGraph runs in nodejs.

**Comment by alfredwassermann** [comment]
All looks very good! It seems that the output of webpack works now in all configurations I'm aware of:

- browser using `<script>`
- AMD with `requirejs`
- nodejs with `import` (`.js`)
- nodejs with `require` (`.cjs`)
- webworker
- module in browser (`<script type='module'>` importing `index.js`) 

@sritchie There is only one variant remaining on my wish list. However it is more of an issue for the future: Is it possible to bundle JSXGraph as a pure ES6 module, maybe in a file called `jsxgraphcore_es6.js`? I added my attempt to `webpack.config.js`, but the browser complains with `ambiguous indirect export: default`.

My test file looks like this:

```html
<div id="jxgbox" class="jxgbox" style="width: 600px; height: 600px;"> </div>
<script type="module">
    import JXG from '.... /jsxgraph/distrib/jsxgraphsrc_es6.js';

    const board = JXG.JSXGraph.initBoard('jxgbox', { 
        boundingbox: [-5, 5, 5, -5], axis:true
    });

    let relation = board.jc.snippet("ln(x)", true, 'x', false);
    let curve = board.create('functiongraph', [relation]);
    let integral = board.create('integral', [[2, 4], curve]); 
</script>
```

**Comment by sritchie** [comment]
I think this will do it, @alfredwassermann : https://github.com/jsxgraph/jsxgraph/pull/488

I changed the output name to `jsxgraphsrc.mjs` and `jsxgraphcore.mjs`, and it looks like things are working here.

Amazing stuff!

**Comment by sritchie** [comment]
Congratulations!
