### ISSUE TITLE
Suggestion: Slider ticks at meaningful positions

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/jsxgraph#470]
At the moment, slider ticks seem to be placed at fixed distances between the end points, irrespective of the slider value at their positions. It would, however, be nice to have ticks at meaningful positions.

For example, if the slider values run for -2 to +2, major ticks should be placed at integer values (given there is enough space).

I hope this brief description is understandable. Please ask if not. – And anyways, thanks for considering!

**Comment by alfredwassermann** [comment]
See #471

**Comment by alfredwassermann** [comment]
Fixed in 9e4a5732bfcb36950db4faef33d268fc6ace4933
