### ISSUE TITLE
Request: the ability to add a listener when a point (or other object) is moved via the keyboard

### ISSUE THREAD

**Issue by dqnykamp** [jsxgraph/jsxgraph#478]
That's great that JSXgraph can now be manipulated with a keyboard so that we can make the constructions accessible to those who are navigating via keyboard!

My request is for the ability to add listeners to these move events (in the same way we can add listeners to the 'drag', and similar events).  I don't want to replace the keyDownListener in board.js, but instead suggest that keyDownListener, in the case where it is moving the object (line 3313 of board.js), calls this.triggerEventHandlers() with an appropriate event name that we can then bind a listener to.

In my application using JSXgraph, we need to adjust other variables when an object is moved.  But, at present, moving an object with a keyboard breaks the correspondence between what is displayed on the graph and our variables because we can't listen to these changes.

**Comment by alfredwassermann** [comment]
Added the events
    
- keymove for board
- keydrag for elements
    
Dragging elements by pressing arrow keys on the keyboard will fire the following events:
    
- `board.on('move')`
- ` board.on('keymove')`
- `el.on('drag')`
- `el.on('keydrag')`
    
If an element gets the focus by keyboard navigation, the 'hit' event is fired.
