### ISSUE TITLE
different behaviour when displayning point's name

### ISSUE THREAD

**Issue by Chrisb0606** [jsxgraph/jsxgraph#490]
Hi,
I've observed a different behavior with nightly jsxgraph build comparing to the 1.4.6 version. It concerns point's name displaying.
Code that behaves differently:
board.create("point",[2,2], {
        name: new String("my point"),
        label: {
          useMathJax: true
}})

In 1.4.6 it displays "my point", whereas in nightly it displays [Object].
I know that new String() is not really often used but I find it useful to keep a consistency coding style toward all my JS objects.
Thanks
Chris

**Comment by alfredwassermann** [comment]
Thank you very much! This was very helpful since we are close to a new release.

The problem was that  `typeof new String(...)` outputs `object` whereas 'typeof 'my point'` outputs `string`.
