### ISSUE TITLE
Adding CSS to GeometryElement

### ISSUE THREAD

**Issue by Abhimanyu-Jha** [jsxgraph/jsxgraph#495]
Is there any way to add custom CSS to a GeometryElement?

I would like to add custom CSS to a point P which current looks like this 
![image](https://user-images.githubusercontent.com/32863175/208485743-eb2e20e5-98e8-41b4-811c-01424f12cf02.png)

to make it look like this (subtle shadow)
![image](https://user-images.githubusercontent.com/32863175/208485851-9672d748-9040-481c-b345-a8dc1d37c6e4.png)

**Comment by alfredwassermann** [comment]
There is a more general answer, less focusing on shadows at [Google groups](https://groups.google.com/g/jsxgraph/c/MSMWGYgo8ps).

JSXGraph v1.5.0 will come with custom shadows, see an example with v1.5.0-rc1 at https://jsfiddle.net/Lfgexbs9/, here is the source code:

```javascript
var p = board.create('point', [1, 1], {
  strokeColor: '#eeeeee',
  fillColor: 'orange',
  size: 5,
  shadow: {
    enabled: true,
    color: '#555555',
    offset: [2, 2],
    opacity: 1,
    blur: 2
  }
});
```

If you nevertheless want to add CSS to the SVG element, you get access via the `rendNode` subobject:

```
p.rendNode
```

**Comment by Abhimanyu-Jha** [comment]
rendNode got the job done thanks!
