### ISSUE TITLE
ES6 module is not working with last version 1.5.0

### ISSUE THREAD

**Issue by MiltonCobo** [jsxgraph/jsxgraph#505]
The following simple example is not working, as jsxgraphcore.js does not provide an export named default. I download the last version of jsxgraph.

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JsxGraph Modules</title>

  <link rel="stylesheet" type="text/css" href="./libraries/jsxgraph.css" />
  <!-- <script type="text/javascript" src="./libraries/jsxgraphcore.js"></script> -->

</head>

<body>
  <div id="jxgbox" class="jxgbox" style="width:600px; height:600px;"> </div>
  <script type="module">
    import JXG from './libraries/jsxgraphcore.js';

    const board = JXG.JSXGraph.initBoard('jxgbox', {
      boundingbox: [-5, 5, 5, -5], axis: true
    });
    var curve = board.create('functiongraph', ['ln(x)']);
  </script>

</body>

</html>
```

**Comment by alfredwassermann** [comment]
In the 1.5.0 release we did not manage to support all kind of exports in one file. The foremost use of JSXGraph seems to be as UMD module. That is, in 1.5.0, the call of

```
import JXG from './libraries/jsxgraphcore.js';
```

will work in nodejs, since there JXG is imported as CommonJS module. This seems to be incompatible to ES6 imports. If you want to use ES6 imports, please use `jsxgraphcore.mjs`, i.e.

```
import JXG from 'https://cdn.jsdelivr.net/npm/jsxgraph/distrib/jsxgraphcore.mjs';
``` 

should work in version 1.5.0. See 4) in https://jsxgraph.org/wp/2023-01-27-release-of-version-1.5.0/.

**Comment by alfredwassermann** [comment]
A working example can be found at https://jsxgraph.org/share/example/import-jsxgraph-as-es6-module

**Comment by MiltonCobo** [comment]
oh thanks! I thought .mjs was a mistype.

Can we download the jsxgraphcore.mjs file?

Milton.

**Comment by alfredwassermann** [comment]
Now it is available at https://jsxgraph.org/distrib/jsxgraphcore.mjs. It should be available at the CDNs, too

**Comment by MiltonCobo** [comment]
Thanks!

**Comment by alfredwassermann** [comment]
Thanks a lot for this bug report. 
Can you please check the import from https://jsxgraph.org/distrib/jsxgraphcore.mjs again?

Best wishes,
Alfred

**Comment by MiltonCobo** [comment]
Yes, this import above is running well, the misprint has been corrected.
Milton.

**Comment by MiltonCobo** [comment]
Hi, I just want to report the following. I was playing with the latest
Shadow feature of jsxgraph. I imagine this feature is not supposed to be
used with functionGraphs, but anyway, I notice that when I plot Log(x) and
a free Triangle (both with shadows), for example, dragging the triangle
becomes very laggy in Ipad IOS (not in windows), however when the plot is
Cos(x) this doesn't happen, the triangle moves normal when it is dragged
with touch (and with shadows).

Would this feature be available for 'canvas' in the near future?

Milton.

**Comment by alfredwassermann** [comment]
Can you please try if setting the attribute `doAdvancedPlot:false` for $log(x)$ is helpful?
