### ISSUE TITLE
Bug: Parameter tickEndings only affects minor ticks

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/jsxgraph#506]
It seems like the parameter `tickEndings` is not being respected by major ticks anymore. Minor ticks are drawn according to the values that `tickEndings` is set to, but major ticks are always drawn in both directions.

Please see the example in this JSFiddle:
https://jsfiddle.net/FLeupold/1h5kogdu/4/

**Comment by alfredwassermann** [comment]
This is an API change: in v1.5.0 major ticks received their own property `majorTickEndings`, i.e. your example has to be expanded to

```
brd0.create('axis', [[0, 0], [43.9, 0]], {
	straightFirst: false, straightLast: false,
	withLabel: true, name: 'r (10^6 m)',
	label: { position: 'rt', offset: [3, 15], anchorX: 'right', parse: true, fontSize: 12 },
	ticks: {
		drawZero: false, insertTicks: false, 
                tickEndings: [0, 1],  
                majorTickEndings: [0, 1],                     // <---- new
		ticksDistance: 10, majorHeight: () => 100 * 2 * brd0.unitY, 
		minorTicks: 4, minorHeight:  () => 100 * 2 * brd0.unitY,
		label: { visible: true, anchorX: 'middle', anchorY: 'top', offset: [0, -4] }
	}
});
```

Sorry about this, Alfred

**Comment by FloMiLe** [comment]
Thanks, Alfred, for the quick reply!
