### ISSUE TITLE
Suggestion: Scaling for custom set ticks

### ISSUE THREAD

**Issue by Haspeldor** [jsxgraph/jsxgraph#519]
When custom ticks are being created by a "generateLabelText" function, the created ticks do not scale correctly when zooming in or out.
While the gap size between the automically set ticks increases or decreases, it stays the same for custom ticks.
Is it possible to give the same treatment to custom ticks?

An example of what I mean can be seen here: 
https://jsfiddle.net/4nbajsch/5/
Taken from this thread:
https://stackoverflow.com/questions/63670056/it-is-possible-to-make-bode-plot-with-jsxgraph/63689274#63689274

**Comment by alfredwassermann** [comment]
In this example, there is just the attribute `insertTicks:true` missing. See it live at https://jsfiddle.net/7s1qrhfv/
