### ISSUE TITLE
[QUESTION] How to pass macro to KaTeX renderer?

### ISSUE THREAD

**Issue by harleylara** [jsxgraph/jsxgraph#523]
Hi

I have a set of macros, and I would like to know how to pass them to `katex.render` [code here](https://github.com/jsxgraph/jsxgraph/blob/19288f95ba1fc581e988fb5f45586ecd7c5599d9/src/renderer/abstract.js#L1242), I was checking the source code and there doesn't seem to be an option to pass macros as arguments.

At the moment I can render a JSXGraph text using Katex, but when I add interaction to the board and refresh the text values the macros are not applied.

```js
import katex from 'katex';

const notation = {
  // definitions of macros here
}

// JSXGraph stuff here

katex.render(jsxgraphText.htmlStr,  jsxgraphText.rendNode, { macros: notation });
```

In case there is currently no workaround to do this, is there a possibility to add this functionality (maybe I could open a PR)?

**Comment by alfredwassermann** [comment]
I just commit a the possibility to supply KaTeX macros as an attribute.

~~~.javascript
var p = board.create('text', [1, 0, 'Hello'], { katexMacros: {} });
~~~

The value of `katexMacros` is an object or a function returning an object. Could you please test if it works?
Best wishes,
Alfred

**Comment by harleylara** [comment]
Hi @alfredwassermann  thanks for your kind answer, I just open a PR to fix it. 😄 

Thank you for maintaining this project 👍 

Best regards
- Harley Lara
