### ISSUE TITLE
point3d Z coordinate not updating on drag

### ISSUE THREAD

**Issue by holgerengels** [jsxgraph/jsxgraph#525]
Hi ..

I just encountered an error:
```
    var board = JXG.JSXGraph.initBoard('board', { boundingbox: [-8, 8, 8, -8], keepaspectratio: false, axis: false, showNavigation: false, showZoom: false, showCopyright: false, pan: { enabled: false} });
    let box = [-5, 5];
    var view = board.create('view3d',
        [
            [-6, -3], [8, 8], // 2D box of view
            [box, box, box]   // 3D bounding cube
        ],
        {});

    var pa = view.create('point3d', [-2, -2, -2], { visible: true, name: '', snapSizeX: .5, snapSizeY: .5, size: 5, color: '#D55E00' });
    var pb = view.create('point3d', [2, 1, 1], { visible: true, name: '', snapSizeX: .5, snapSizeY: .5, size: 5, color: '#D55E00' });
    var va = view.create('line3d', [pb, pa], { straightFirst: false, straightLast: false, dash: 2 });

    var text = board.create('text', [-5, 5, () => {
        const dx = pb.X()-pa.X(); const dxf = dx.toFixed(1);
        const dy = pb.Y()-pa.Y(); const dyf = dy.toFixed(1);
        const dz = pb.Z()-pa.Z(); const dzf = dz.toFixed(1);
        return `\\Bigg|\\begin{pmatrix} ${dxf} \\\\ ${dyf} \\\\ ${dzf} \\end{pmatrix}\\Bigg| = \\sqrt{${dx >= 0 ? dxf : '(' + dxf + ')'}^2 + ${dy >= 0 ? dyf : '(' + dyf + ')'}^2 + ${+(dz >= 0 ? dzf : '(' + dzf + ')')}^2 } \\approx ${Math.sqrt(dx ** 2 + dy ** 2 + dz ** 2).toFixed(1)}`
    }], { fontSize: 1, fontUnit: 'em', color: '#D55E00', useKatex: true, cssClass: 'term' });
```

`const dz = pb.Z()-pa.Z();` stays at the initial value, as `pa.Z()` and `pb.Z()` do. They should update, shouldn't they? X and Y do!

Thanks in advance!

Holger

**Comment by alfredwassermann** [comment]
At the time being, i.e. v1.5.0, it is only possible to drag a 3D point in its $xy$ plane. That means by dragging the $z$ coordinate of the point does not change. We hope to change this very soon: e.g. the $z$-coordinate is changed if the shift-key is pressed. However, it is not yet clear, how to realize this on a touch device.

**Comment by holgerengels** [comment]
ah .. ok .. some ideas:

1. always constrain the movement along one axis, choose the axis, to which
the drag direction is most similar (this is, what I thought, it did already
.. but now i realized, that in fact it were the views bounds, that
constrained the movement)
2. double tap and drag for z-axis
3. when focused, show arrows that tell the current degrees of freedom. on
tap switch the degrees of freedom between x+y and z .. somewhat like
geogebra does it

greets
