### ISSUE TITLE
JXG.Dump.toJessie does something wrong with functiongraph when there is an x axis

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#536]
Here's a minimal example that demonstrates the problem:

```
/* We'll create a board with axes, and add a functiongraph to it.
*/
const board1 = JXG.JSXGraph.initBoard('board1', {axis: true});

board1.create(
  'functiongraph', 
  [function(t) { return t*t; }]
);

board1.update();

/* Then dump the contents of the board to JessieCode, and load that code in a second board.
*/
const code = JXG.Dump.toJessie(board1);
console.log(code);

const board2 = JXG.JSXGraph.initBoard('board2');
board2.jc.parse(code);
```

[This example on codepen](https://codepen.io/christianp/pen/wvYRqzX)

There's an error because the x axis is named 'x', and the functiongraph sets its x parameter as 'x', so I think that the reference gets resolved to the id of the x axis.

The dumped JessieCode is (I've omitted the styling attributes):

```
s0 = point(0, 0) <<name: '', id: 'jxgBoard1P1'>> ;

s1 = point(1, 0) <<name: '', id: 'jxgBoard1P2'>> ;

// x
s2 = axis("jxgBoard1P1", "jxgBoard1P2") <<name: 'x', id: 'jxgBoard1L3'>> ;

s3 = point(0, 0) <<name: '', id: 'jxgBoard1P13'>> ;

s4 = point(0, 1) <<name: '', id: 'jxgBoard1P14'>> ;

// y
s5 = axis("jxgBoard1P13", "jxgBoard1P14") <<name: 'y', id: 'jxgBoard1L15'>> ;

// s_{a}
s6 = curve("jxgBoard1L3") <<id: 'jxgBoard1G25', name: 's_{a}'>> ;
```

I don't know if the automatically-created x axis should be given a different name so it doesn't conflict, or if there's a bug in serialising the functiongraph which could be fixed so it doesn't resolve to the id of the x axis.

If you set `{axis: false}` when initialising the first board, the dumped JessieCode is correct (again I'm omitting styling attributes):

```
s0 = curve("x", function (t) {return t * t;}, -6, 6) <<id: 'jxgBoard1G1', name: 's_{a}'>> ;
```

**Comment by alfredwassermann** [comment]
Many thanks for posting this bug. Indeed, the axis name `x` is the show stopper here. Renaming the axes, like in the  following code, solves the problem:

~~~
const board1 = JXG.JSXGraph.initBoard('board1', {
    axis: true,
    defaultAxes: {
        x: {name:'x-axis'},
        y: {name:'y-axis'}
    }
});

board1.create(
  'functiongraph', 
  [function(t) { return t*t; }]
);

board1.update();

/* Then dump the contents of the board to JessieCode, and load that code in a second board.
*/
const code = JXG.Dump.toJessie(board1);
console.log(code);

const board2 = JXG.JSXGraph.initBoard('board2', {axis: false});
board2.jc.parse(code);
~~~

Now, the question is  how to fix this without breaking backward compatibility.

**Comment by christianp** [comment]
Is there still a problem even if you fix the axes? This bug would happen if any object has the name `'x'`. The `functiongraph` shouldn't be using a code path that could ever lead to resolving the name `'x'` to something else.

**Comment by alfredwassermann** [comment]
That's true. We must tell the interpreter that this 'x' is a variable name, i.e. a string.
