### ISSUE TITLE
Comma as a decimal separator on axis

### ISSUE THREAD

**Issue by sowiso** [jsxgraph/jsxgraph#540]
Hello! Is it possible to format the labels of the ticks on the axes with a comma as a decimal separator instead of a dot?

**Comment by alfredwassermann** [comment]
This is a very good suggestion. In the last weeks we took this suggestion up and worked on internationalization. This will allow language specific decimal separators (and more). Documentation is still missing, otherwise it basically works. Details will follow soon.

**Comment by sowiso** [comment]
Thanks! If you're taking it up more broader, maybe you're already aware, but another place where this is relevant is the highlightInfobox. Also see #552

**Comment by alfredwassermann** [comment]
Formatting of numbers should be now pretty complete. It will be available in v1.6.0. 

Before releasing v1.6.0, a beta version can be tested from <https://jsxgraph.org/beta/jsxgraphcore.js> and <https://jsxgraph.org/beta/jsxgraph.css>. The updated documentation is at <https://jsxgraph.org/beta/docs>, where internationalization is described at <https://jsxgraph.org/beta/docs/symbols/JXG.Board.html#intl>.

Please, give us feedback.
