### ISSUE TITLE
automatic scaling of ticks opaque

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#548]
The automatic scaling of ticks (insertTicks: true) is a bit opaque. If one and the same board is represented once with bounding box [-5,5,5,-5] and once with [-10,10,10,-10], the ticks are in intervals 1 in the first case, in in the second case intervals 5 (instead of 2).
Is there a way to adjust these distances?
See: https://jsfiddle.net/bx1eo09z/

**Comment by alfredwassermann** [comment]
Fixed by 552a94d457b25f4232ab7796fea312e60315fc5d
