### ISSUE TITLE
last ticks of axes

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#549]
The last tick of the axes is shown, although it is after the arrowhead. This isn't normally visible, but if you make the ticks a bit thicker, you can see it quite clearly:
https://jsfiddle.net/xhq4tp6y/
![image](https://github.com/jsxgraph/jsxgraph/assets/30598361/bf5a8be5-e9b5-4a44-8c97-c78ad458631c)
This setting is useful when using the ticks as a grid (majorHeight: -1), so that the last grid tick isn't hidden if the arrowhead is too big.
For normal ticks, however, the last tick should not be drawn.

**Comment by alfredwassermann** [comment]
Fixed by 1fc7024aceddfc9432e3a85eb225544e7b686557
