### ISSUE TITLE
fun.toString is not working for JessieCode

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#550]
This issue affects JessieCode.

To read the radius of a circle that was set by a function (e.g. `object.setRadius(function() { return (1*(PI)); });` the following call is made: `'' + object.updateRadius` .
In other words: the function `fun.toString`, defined in line 698 of the jsxgraph/src/parser/jessiecode.js file, is ultimately called (https://github.com/jsxgraph/JessieCode/blob/4da74fe6a11829dfe0bb7e7109d43e2ec82baa23/src/interpreter.js#L698). This in turn calls the function JXG.JessieCode.prototype.compile (from line 1599, [/src/parser/jessiecode.js#L1599](https://github.com/jsxgraph/jsxgraph/blob/313c233fd5b9607bad8ca383f5c2bc947948a394/src/parser/jessiecode.js#L1599)), where only the first parameter is occupied. This will default the second parameter `js` to `false`.
This in turn causes the else case to be selected in line 1907 ff. In this case, however, it is incorrect. It causes the radius PI to be returned as a `function() << return PI; >>`.
In fact, it should be: `function() { return (1*(PI)); }` or just `function() { return PI; }`

**Comment by alfredwassermann** [comment]
Fixed by 1cc6d149d0a3f9ba2a8b54c3af9afdaf8500a321
