### ISSUE TITLE
highlightStrokeColor bug (?)

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#561]
If you set the strokeColor for a line, the highlightStrokeColor is apparently also set automatically. This means that in my case the dynamic function is overwritten: https://jsfiddle.net/0pnL51a7/
Is that intentional or a bug?

**Comment by alfredwassermann** [comment]
From the jsfiddle example above, it seems that strokeWidth and highlightStrokeWidth are affected.

This is a feature and can be be turned off by calling

    delete JXG.Options.shortcuts.strokeWidth;

before initializing the board.
