### ISSUE TITLE
Problems with slopetriangle

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#563]
The attributes borders.ids are lost in line https://github.com/jsxgraph/jsxgraph/blob/32af31def8857869d495402508e564d14c9e718a/src/element/slopetriangle.js#L186

**Comment by alfredwassermann** [comment]
Despite the slightly misleading name of the (undocumented) attribute `borders`, the element `slopetriangle` is not of class `polygon` but of of class `line`. The id's of the sub-elements 

    el.glider
    el.basepoint
    el.baseline
    el.toppoint
    el.label

have to be set individually.
