### ISSUE TITLE
new angle types

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#565]
It would be very nice, if there would be added some new angle types and orthoTypes:
- [ ] arc (not a shape, just a curve)
- [ ] sector without the legs (like arc, but filled)
- [ ] angle field (the whole area is coloured, till the end of the boundingbox)

All of them should be possible with a dot.

**Comment by alfredwassermann** [comment]
These features are now possible since 61b1a5546beb4e0f5466710c8b7347ded4cc6cec.

An *angle field* can be achieved by setting a large enough radius
