### ISSUE TITLE
Feature request: in 3D view, drag anywhere within the viewport for azimuth and elevation

### ISSUE THREAD

**Issue by Cleonis** [jsxgraph/jsxgraph#573]
In 3D viewers it is customary that azimuth and elevation is implemented as follows: dragging the mouse horizontally adjusts the azimuth, and dragging the mouse vertically adjusts the elevation. 

Currently: in the (in development) 3D view of JSXGraph azimuth and elevation are implemented in the form of 2D elements. Within the viewport there is a slider for azimuth and a slider for elevation. 

Feature request: to make an option available such that dragging anywhere within the viewport adjusts azimuth-elevation, removing the need (and possibility) of placing sliders within the viewport.

**Comment by alfredwassermann** [comment]
Done in v1.8.0
