### ISSUE TITLE
Error when working with ForeignObject

### ISSUE THREAD

**Issue by jonaslache** [jsxgraph/jsxgraph#583]
Hello everyone,

I have a problem concerning the object type `ForeignObject`. When I create a JSXGraph graphic with such an object type, the object is indeed displayed correctly. However, there is an error message in the browser console (Firefox): 

```
Uncaught TypeError: u is undefined
```

When using Microsoft Edge, there is a similar error message:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
```
In both browsers there is a reference to `jsxgraphcore.js:55:15235`

The error has the consequence that all objects defined later in the code are no longer displayed. I tried it in JSXGraph version 1.6.0.

By the way, the error message does not only appear when I create my own object or copy one of the examples from the API reference. Even if I open the [corresponding page in the API reference](https://jsxgraph.org/docs/symbols/ForeignObject.html) for the object type `ForeignObject` in the browser, there is the error message in the browser console three times (once for each of the examples there).

Thanks for your help!
Jonas

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. It will be fixed immediately. As a temporary bug fix you can set

```
JXG.Options.foreignobject.attractors = [];
```

before initializing the board, or add `attractors:[]` to the attributes of the `foreignobject` element.
