### ISSUE TITLE
Let initBoard accept div reference

### ISSUE THREAD

**Issue by alfredwassermann** [jsxgraph/jsxgraph#584]
See https://groups.google.com/g/jsxgraph/c/8zqDOdBBkTg

**Comment by christianp** [comment]
Yes please! This has been a minor annoyance for years.

**Comment by alfredwassermann** [comment]
There is now a version *v1.6.2 beta* at https://jsxgraph.org/beta/jsxgraphcore.js with this feature enabled. I would be very  happy if you could test it in your environment and give me feedback.

**Comment by alfredwassermann** [comment]
Fixed in v1.6.2
