### ISSUE TITLE
Some requests for intersections, and polynomial solvers

### ISSUE THREAD

**Issue by amca01** [jsxgraph/jsxgraph#599]
Here are some ideas for future enhancements which would be of help to me, at least!

1. Extend `otherintersection` so that it works for lines intersecting any conic section.  (I've already had a little discussion about this on stackoverflow.com)
2. Add some functionality that returns all numerical roots of a polynomial.  Currently I've done this by importing the math.js library and computing the eigenvalues of the polynomial's companion matrix.   But you could also use the Durand-Kerner or Aberth methods... (I've tried implementing these in Javascript and failed!  But they should be straightforward for a better programmer. ) 

I'm not sure about the protocol of feature requests, given that this is an open-source project and everybody is putting in whatever time they have... so I guess I should also ask - how can I help?

**Comment by alfredwassermann** [comment]
The best help is to give us feedback on errors or suggestions for improvements in the code, but also in the API documentation and in the general ecosystem.
Also, we would be happy if you send us examples which might be useful for other users and which we can put in our API reference (very short examples), our wiki, or the examples database (at https://jsxgraph.org/share). These examples should be 
- helpful for other users (and not be a showcase what can be done with JavaScript / JSXGraph)
- reasonably small such the code can be understand,
- restricted to one or very few features.

I could not resist to take up your suggestion and implement the Aberth-Ehrlich iteration. I'm very impressed how good the approximations are and how fast it is. It was a joy to do this implementation. Thus, the upcoming version 1.7.0 will have a method `JXG.Math.Numerics.polzeros` which expects an array of coefficients (real or complex) of the polynomial and returns the roots of the polynomial.

Best wishes,
Alfred

**Comment by amca01** [comment]
Yes, the Aberth-Erlich method improves on the better known Durand-Kerner method by having cubic convergence instead of quadratic convergence.  The difficulty is choosing appropriate starting values, so some work may be required before the algorithm can run.  Thank you for suggestions about examples.  There are many places in the API description where a small example may be helpful (certainly to a beginner like me) - is this the sort of thing you had in mind?
