### ISSUE TITLE
Labelled bar chart not working

### ISSUE THREAD

**Issue by Aljumaily** [jsxgraph/jsxgraph#609]
The following code snippet is copied from the [Chart](https://jsxgraph.org/docs/symbols/Chart.html) element documentation. I tried executing and seems that the labels are not shown on screen and an error is thrown. To bypass the error, the property `labels: f` needs to be removed. Also, when increasing the `width` property to more than `1`, the bars overlap. The error is
`
TypeError: t.replace is not a function. (In 't.replace(/&#x(\w+);/g,function(t,e){return String.fromCharCode(parseInt(e,16))})', 't.replace' is undefined)
`
The code is found below.

```
board = JXG.JSXGraph.initBoard(
  'jxgbox',
  {
    boundingbox: [-0.5, 8, 9, -2],
    axis: true
  }
);

var f = [4, 2, -1, 3, 6, 7, 2];
var chart = board.create(
  'chart',
  f,
  {
    chartStyle: 'bar',
    width: 0.8,
    labels: f,
    colorArray:
      [
        '#8E1B77', '#BE1679', '#DC1765', '#DA2130', '#DB311B', '#DF4917',
        '#E36317', '#E87F1A', '#F1B112', '#FCF302', '#C1E212'
      ],
    label: {
      fontSize: 30,
      display: 'internal',
      anchorX: 'left',
      rotate: 90
    }
  }
);
```

**Comment by Aljumaily** [comment]
Thank you, @tom-berend, for your reply. I am using PreTeXt and seems that the jsxgraph version isn't up to date. Using the 1.7.0 version worked! I kindly ask if there is a way to make the bars have a width greater than 1 and not overlap.

**Comment by tom-berend** [comment]
A simple way to double the width of bars and not overlap is to put a 'zero' bar between each datapoint, and use different arrays for data and labels.   Is this what you had in mind?


```
var f = [4, 0, -1, 0, 6, 0, 2];
var f2 = [4, '', -1, '', 6, '', 2];     // second array with labels, every second is blank.  
var chart = board.create(
  'chart',
  f,
  {
    chartStyle: 'bar',
    width: 1.8,
    labels: f2,       // take the labels from the second array
    colorArray:
      [
        '#8E1B77', '#BE1679', '#DC1765', '#DA2130', '#DB311B', '#DF4917',
        '#E36317', '#E87F1A', '#F1B112', '#FCF302', '#C1E212'
      ],
    label: {
      fontSize: 30,
      display: 'internal',
      anchorX: 'left',
      rotate: 90
    }
  }
``` 
![ch](https://github.com/jsxgraph/jsxgraph/assets/11073753/5395425d-2af4-4cd9-84cc-e6c3ad1fbe96)

**Comment by Aljumaily** [comment]
@tom-berend Thank you for the clever solution.
