### ISSUE TITLE
Request: Event 'dblclick'

### ISSUE THREAD

**Issue by Mat-Ge** [jsxgraph/jsxgraph#613]
An event "dblclick" would be very welcome. Specifically, I need an object that can exist in two states. However, the state should not change when the object is moved or just clicked. A "dblclick" event would be perfect for switching between the states.

**Comment by alfredwassermann** [comment]
Good suggestion!
I just added `click` and `dblclick` events to JSXGraph in the `develop`  branch. This works in desktop browsers, but not on mobile browsers. For the latter, the outcome is completely weird (if the browser is webkit based). I'm not sure if this can be resolved.
