### ISSUE TITLE
Dedicated Sphere3d entity

### ISSUE THREAD

**Issue by gwhitney** [jsxgraph/jsxgraph#616]
While it is possible to draw a sphere with the ParametricSurface3D entity, the resulting grid lines on the surface tend to obscure geometry interior to the sphere. We propose a dedicated Sphere3D entity to take advantage of the fact that the projection of a sphere in any orientation is a disk, and use radial transparency and hue gradients in svg to simulate the sort of rendering one might obtain in an OpenGL rendering of a semitransparent sphere. The appearance should correspond to the current appearance of Point3D entities, but with transparency allowing visibility of interior geometry.

A Sphere3D should be constructible from a center Point3D and either a numerical radius or an additional Point3D through which it must pass.

We will be happy to provide a PR if this feature would be welcome.

**Comment by alfredwassermann** [comment]
This would be a very helpful addition!
