### ISSUE TITLE
Intersection of two planes

### ISSUE THREAD

**Issue by Vectornaut** [jsxgraph/jsxgraph#618]
While gearing up for #616, I implemented a 3D intersection line element, which can be created by taking the intersection of two planes. Is that worth a pull request?

**Comment by alfredwassermann** [comment]
Of course it is!

**Comment by alfredwassermann** [comment]
Please direct pull requests with new feature to the branch `develop`. Only bug fixes should land in the branch `main`.
Thanks, Alfred

**Comment by Vectornaut** [comment]
Done: #624. There are a lot of loose ends, but I figure the quickest to find out what needs to be improved is to get a minimal implementation under review.
