### ISSUE TITLE
Tapemeasure ticks detach

### ISSUE THREAD

**Issue by DylanHojnoski** [jsxgraph/jsxgraph#623]
[https://jsfiddle.net/uxozLv6e/](https://jsfiddle.net/uxozLv6e/)

When moving around the points of the tape measure the ticks detach from the line.

![20240307_13h44m29s_grim](https://github.com/jsxgraph/jsxgraph/assets/68570349/b7420e92-4fb3-4477-8d6f-5e95f64fcef5)

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing this out!
