### ISSUE TITLE
V1.8 - grid-without-axis missing axis lines

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#625]
```
  let maxX = 10
  let maxY = 10
  let B = JXG.JSXGraph.initBoard('html26', { boundingbox: [-maxX, maxY, maxX, -maxY], grid: true });
```

![grid](https://github.com/jsxgraph/jsxgraph/assets/11073753/2f1f439d-b0b4-43b7-80d7-02957fbec030)

**Comment by andreas-web** [comment]
Dear Tom,
please have a look at <https://jsxgraph.uni-bayreuth.de/docs/symbols/Grid.html#major_drawZero>. The following code should work:
```
let B = JXG.JSXGraph.initBoard('html26', { boundingbox: [-maxX, maxY, maxX, -maxY], grid: {drawZero: true} });
```
Best regards,
Andreas

**Comment by tom-berend** [comment]
You are right, and I discovered at it after I posted.  There is no attribute listed for 'drawZero', but the example shows it correctly.
