### ISSUE TITLE
V1.8:  Grid drawZero issue

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#626]
The 'extreme fancy grid' example does not show the minor grids when the major grid has 'drawZero' set.   To demonstrate, comment out 'drawZero'  as follows:

```
     // let board = JXG.JSXGraph.initBoard('html26', { boundingbox: [-maxX, maxY, maxX, -maxY], grid:true, major:{ drawZero:true}})
            let board = JXG.JSXGraph.initBoard('html26')

            // extreme fancy grid
            var grid = board.create('grid', [], {
                major: {
                    face: 'regularPolygon',
                    size: 10,
                    strokeColor: 'blue',
                    fillColor: 'orange',
                    strokeOpacity: 1,
                    // drawZero: true,                   // commented out
                },
                minor: {
                    face: 'diamond',
                    size: 3,
                    strokeColor: 'green',
                    fillColor: 'lightgrey',
                    drawZero: true,
                },
                minorElements: 1,
                includeBoundaries: false,
            });

```
![grid](https://github.com/jsxgraph/jsxgraph/assets/11073753/5b153009-4bec-44b7-a8a1-511b21fa09f5)

**Comment by tom-berend** [comment]
let me suggest that the default for 'drawZero' should be `true`, not `false`.

because
1) `false` breaks compatibility with older releases (eg: https://jsxgraph.uni-bayreuth.de/wiki/index.php?title=Rectangles)
2) `false` seems strange, geometers expect a full grid with `initboard('html',{grid:true})`
3) snapToGrid snaps to zero locations even if the grid is drawn without `drawZero`
3) there is little downside; `true` has no visible effect when a default axis is also drawn

**Comment by alfredwassermann** [comment]
Agreed!

**Comment by alfredwassermann** [comment]
OK, the bug is fixed: "size: 3" for the diamond had been considered as user unit, not as pixel value.

**Comment by andreas-web** [comment]
@alfredwassermann has also set the default of `minor.drawZero` to `true`. So if I am not mistaken, this issue should be fixed in the next version. Please reopen, if there are still any errors.

As you already noted in #625, instead of 
```
{
   ...
   minor: {
      drawZero: true
   }, 
   major: {
      drawZero: true
   },
}
```

the following code can be written:
```
{
   ...
   drawZero: true
}
```

I will open a PR that adds these shortcuts to the documentation.
