### ISSUE TITLE
Axis: drawZero does not work when line point is at [0,0]

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/jsxgraph#630]
`drawZero` does not show the zero tick if the first line point is at `[0,0]`. The zero is only shown when the line point is on the negative side, see example below.

```
var xAxis = brd0.create('axis', [[-0.00001, 0], [45, 0]], {
	straightFirst: false, straightLast: false,
	withLabel: true, name: 'U (V)',
	label: { position: 'rt', offset: [0, 15], anchorX: 'right', parse: false, fontSize: 12 },
	ticks: { drawZero: true, insertTicks: false,
		ticksDistance: 10, majorHeight: () => 40 * 2 * brd0.unitY, majorTickEndings: [1, 0],
		minorTicks: 1, minorHeight:  () => 40 * 2 * brd0.unitY, tickEndings: [1, 0],
		label: { visible: true, anchorX: 'middle', anchorY: 'top', offset: [0, -7] }
	}
});
```

**Comment by alfredwassermann** [comment]
This is by purpose, but can be controlled by the attribute `includeBoundaries`. The following code should work:

        var xAxis = brd0.create('axis', [[0, 0], [45, 0]], {
            straightFirst: false,
            straightLast: false,
            withLabel: true,
            name: 'U (V)',
            label: { position: 'rt', offset: [0, 15], anchorX: 'right', parse: false, fontSize: 12 },
            ticks: {
                drawZero: true,
                includeBoundaries: true,
                insertTicks: false,
                ticksDistance: 10,
                majorHeight: () => 40 * 2 * brd0.unitY,
                majorTickEndings: [1, 0],
                minorTicks: 1,
                minorHeight: () => 40 * 2 * brd0.unitY,
                tickEndings: [1, 0],
                label: { visible: true, anchorX: 'middle', anchorY: 'top', offset: [0, -7] }
            }
        });
