### ISSUE TITLE
Add 3D circle element

### ISSUE THREAD

**Issue by Vectornaut** [jsxgraph/jsxgraph#634]
[This example](https://jsxgraph.uni-bayreuth.de/~alfred/jsxdev/3D/drag.html) (for as long as it's posted) shows how useful it is to draw circles in 3D space. Drawing circles on a sphere can help provide depth cues, which are badly needed, because the current implementation of `Sphere3D` has few depth cues built in. Circles would also be nice building blocks for future cone and cylinder elements.

I'd like to add a `Circle3D` element constructed from:

* A point – the center of the circle
* A vector – a normal to the plane the circle lies in
* A number or function – the radius of the circle

This construction method is tailored to the applications described above.

Does this seem reasonable? If so, is there anything I should keep in mind while implementing it?

**Comment by alfredwassermann** [comment]
Absolutely! A circle3d element would be a very valuable extension.

**Comment by Vectornaut** [comment]
To do this, I'd want to rename the current `updateEllipse` function to `updateCircle`, and write a more general `updateEllipse` function that allows independent major and minor radii, and rotation. May I go ahead and do this?

Adjusting the rotation angle for boards where `unitX != unitY` would be a pain. Would it be okay to just implement the `unitX = unitY` case for to start with?

**Comment by Vectornaut** [comment]
On second thought, I just noticed that the `Circle` element is internally represented as an `Ellipse` whose focal points coincide. I can implement `Circle3D` the same way, without adding any new rendering primitives.

**Comment by alfredwassermann** [comment]
Hmm, did you think about implementing Circle3D as a Curve3D as in the above example? The advantage would be that later on intersections with Circle3D could be handled by a Curve3D intersection algorithm.

**Comment by Vectornaut** [comment]
> did you think about implementing Circle3D as a Curve3D as in the above example?

I hadn't thought of that! I guess it would be consistent with the way `Circle` is currently implemented.

**Comment by alfredwassermann** [comment]
The Circle element is using indeed the SVG ellipse element. But meanwhile this is more of a restriction than a help. In fact, all SVG elements are just a higher level version of the path element. It would make not much difference to implement this extra level. Moreover, in JSXGraph we have to work with an object mathematically (intersections, ...), where the path implementation is sometimes handy.

**Comment by alfredwassermann** [comment]
Done in 61cf6d99e618a3764a075b7c226e14b7f0f178e9
