### ISSUE TITLE
Riemannsum type as string

### ISSUE THREAD

**Issue by DylanHojnoski** [jsxgraph/jsxgraph#635]
When you define the riemannsum type with  a string it does not actually change the type and instead uses the default. This is not the case when you use a function instead. If you wrap it in a second set of escaped quotes like `'\'trapezoidal\''` it does work properly. The following jsfiddle has a riemannsum with type defined as trapezoidal but the used type is the default (left).

[https://jsfiddle.net/8f4ako76/](https://jsfiddle.net/8f4ako76/)

**Comment by DylanHojnoski** [comment]
The issue seems to be when it is getting parsed into jessieCode it is being turned into a variable named `trapezoidal` instead of a string `'trapezoidal'`.

**Comment by alfredwassermann** [comment]
Fixed in 89885c2dd969624451f4e190be9406a16d931c1d
