### ISSUE TITLE
Grid lines thick and a bit obtrusive with 1.8.0

### ISSUE THREAD

**Issue by drgrice1** [jsxgraph/jsxgraph#638]
With the changes to the grid in version 1.8.0, the grid lines have become considerably thicker than before, and are rather obtrusive.  Aside from the lack of visual appeal, the grid can obscure other elements, primarily text labels on the axis.  I noticed that if I zoom in with the browser (Ctrl-+), the grid lines suddenly go back to looking thin like they did before with previous versions of jsxgraph.  Am I missing a new setting that can fix this?   I tried many combinations of the new themes and other settings, and nothing helped.

Here are some screenshots demonstrating the difference.  These were taken with Firefox, but I see the same behavior in Google Chrome.

The first screenshot is with 1.8.0 at the default zoom level:
![grid-1 8 0](https://github.com/jsxgraph/jsxgraph/assets/47527406/d023b5d2-2d03-44a2-8d59-15e60cd75352)

The next is with 1.8.0 at a zoom of 120%:
![grid-zoomed-1 8 0](https://github.com/jsxgraph/jsxgraph/assets/47527406/980088d8-8870-408c-ae66-c793ee7b80c8)

The next is with 1.7.0 at the default zoom level:
![grid-1 7 0](https://github.com/jsxgraph/jsxgraph/assets/47527406/4a3f3a36-3f92-4ba6-9823-d55ecffd26bb)

Finally, with 1.7.0 at 120% zoom:
![grid-zoomed-1 7 0](https://github.com/jsxgraph/jsxgraph/assets/47527406/cf2f95ba-dfd6-4628-8e3d-1ea69ac02d2e)

Here is the minimal code used for these (of course the version changed for the 1.7.0 screenshots):
```html
<html>
	<head>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jsxgraph@1.8.0/distrib/jsxgraph.css" />
		<script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.8.0/distrib/jsxgraphcore.js"></script>
		<style>
			#box {
				width: 200px;
				height: 200px;
			}
		</style>
	</head>

	<body>
		<div id="box" class="jxgbox"></div>
		<script>
			JXG.JSXGraph.initBoard('box', {
				boundingBox: [-10, 10, 10, -10],
				axis: false,
				grid: { majorStep: [1, 1] }
			});
		</script>
	</body>
</html>
```

**Comment by alfredwassermann** [comment]
This is very strange. First, I can not reproduce it on my computer (also with Firefox). Second, in 1.8.0, out of the box we use exactly the same color, opacity and stroke width as in 1.7.0. 
Could you set up a jsfiddle, so that more people can test it? Which OS and screen resolution did you use? It might also be some ant-aliasing thing.

**Comment by alfredwassermann** [comment]
*Update*: now, I can reproduce it. On my computer the problems starts with zoom level $\leq$ 80. Indeed, it looks like an anti-aliasing problem. We will work on it.

**Comment by drgrice1** [comment]
Interesting.  So it just happens that with my settings it happens one zoom level higher than for most others.  That explains why there were no issues on this.

It does seem like an anti-aliasing issue.

I am not sure if this is still needed, but here is a jsfiddle: https://jsfiddle.net/drgrice1/1fL45apq/4/

Thanks for looking into this.

**Comment by drgrice1** [comment]
I can confirm that the issue is fixed with the develop branch.  Thanks.
