### ISSUE TITLE
view3D elements will run, but they won't hide ;-)

### ISSUE THREAD

**Issue by gwhitney** [jsxgraph/jsxgraph#647]
Or in more mundane language, even after calling hide(), a view3D GeometryElement is still visible, unlike, say, a point.

Minimal fiddle: https://jsfiddle.net/w13fjkL2/

Would you like us to investigate and try to create a PR to fix?

**Comment by alfredwassermann** [comment]
This is implemented in the `develop` branch with 8144d1bbb54d46c79d7b9b6d766d4bf84c9d139e, but deserves more testing.

**Comment by gwhitney** [comment]
Great, we will take a look as we incorporate JSXgraph into our Joyce Euclid plug-in. Thanks!
