### ISSUE TITLE
Overlay div with transparent background not working

### ISSUE THREAD

**Issue by rwmorton** [jsxgraph/jsxgraph#654]
If I put a transparent div on top of a JXG.Board the board doesn't render.

`backgroundColor: 'rgba(0, 0, 0, 0)'`

**Comment by alfredwassermann** [comment]
Can you please give a minimal example? At <https://jsfiddle.net/9aLyc4bv/> is a jsfiddle to get things started. Since this example works, I assume you somehow create the div vi a JSXGraph's `text` or `foreignobject`.

**Comment by rwmorton** [comment]
Thank you for your response and the fiddle! I ended up using the renderer `dumpToCanvas` method to workaround it.

My CSS is not very good.

**Comment by alfredwassermann** [comment]
Do you considered the problem as solved?

**Comment by rwmorton** [comment]
Yes thank you very much Alfred! :pray:

**Comment by alfredwassermann** [comment]
You're welcome.
All the best, Alfred
