### ISSUE TITLE
resize before print

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#660]
When I do a call like `window.print()` there is no resize before.   
So the board has the wrong size, if the `div`'s dimensions are set automatically (`width: 100%; aspect-ration: 1/1;`):

![image](https://github.com/jsxgraph/jsxgraph/assets/30598361/138a3ac6-0790-4b92-ba30-82732a13ba86)

**Comment by alfredwassermann** [comment]
This problem also appears if the JSXGraph div is resized by CSS with `@media print`.
Unfortunately, it seems that there is no way to determine the size of the JSXGraph div on the printed page. There are the events `beforeprint` and `afterprint`. However, while the event `beforeprint` is triggered, the size of the JSXGraph div is still the size set by `@media screen`.

If someone knows a solution it would be much appreciated.

**Comment by andreas-web** [comment]
I added a PR #672 which should solve the problem.
