### ISSUE TITLE
Question: preferred/best way to handle board titles?

### ISSUE THREAD

**Issue by gwhitney** [jsxgraph/jsxgraph#661]
The java applet geometric constructions we are reviving by means of JSXGraph generally have titles, which were displayed in grey overlays at the lower-left corner of the diagram. (I.e, in a way similar to the JSXGraph version and copyright message on JSXGraph boards, except for positioning.)

On the other hand, JSXGraph Boards do have a title attribute, but it is only placed in an invisible div before the board itself. I realize this title is primarily for ARIA accessibility purposes, but it is the current nominal title attribute of a board.

What would your recommended/preferred way to handle titles for boards that wish to display their titles within the confines of the board's display itself? Would you prefer an attribute or attributes dealing with the visibility/layout of the title? Or distinct attributes dealing with a displayed title, perhaps called a "caption" or something, rather than a title?

If you'd suggest adding attributes to use the current title, note that simply making the existing div containing the title visible isn't really workable, as it introduces a box above the Board, throwing off the layout of pages that are prescribing the size of the Board. For layout to be unaffected, the title would need to display within the confines of the Board's display area.

One might suggest that the diagram title/caption simply be displayed as a Text element. But as far as I can see, such elements are always bound to the coordinate system of the Board, whereas this title should always be in the lower left corner of the board's display area, regardless of the coordinate ranges it happens to currently be displaying. But so I guess a third alternative would be to add attributes to Text elements that mean they would be displayed in a fixed physical location with respect to the display area of the Board, regardless of the Board's coordinate system.

If you can provide an indication of your preferred way to handle such titles, we'll be happy to do it that way, and if a PR is needed to add functionality either to Boards or Text elements to support it, we're happy to create the PR.  Thanks!

**Comment by alfredwassermann** [comment]
Probably the most stable solution is the following:

~~~
        var txt = board.create('text', [
                () => board.getBoundingBox()[0],
                () => board.getBoundingBox()[3],
                'Title'], {
            anchorX: 'left',
            anchorY: 'bottom',
            cssClass: 'jsxgraph_title',
            highlightCssClass: 'jsxgraph_title',
            fixed: true
        });
~~~

together with some CSS styling of the text:

~~~
        .jsxgraph_title {
            padding: 10px;
            border: 1px solid black;
        }
~~~

See it live at https://jsfiddle.net/j4a2dLq6/1/

Best wishes,
Alfred

**Comment by gwhitney** [comment]
Ah, thank you. I see this relocates the text within the internal coordinate system. I had been thinking of some way of specifying text relative to the canvas itself, but this works without any visible jitter or anything.
