### ISSUE TITLE
SVG dimensions incorrect with CSS scale.

### ISSUE THREAD

**Issue by bgoldowsky** [jsxgraph/jsxgraph#665]
If the graph is nested in an HTML context where there is a CSS transform applied, the graph does not render correctly.  Minimal example:

```
<div class="container" style="transform: scale(0.5);">
  <div id="jxgbox" class="jxgbox" style="width:500px; height:500px">
  </div>
</div>

<script>
const board = JXG.JSXGraph.initBoard('jxgbox', { 
    boundingbox: [-5, 5, 5, -5], axis:true
});
</script>
```

I have traced this down to the `width` and `height` that gets applied to the `<svg>` element in the SVG renderer.  I have a patch for our particular use case, but have not investigated other renderers or other variations of transforms that might also be problematic.

**Comment by bgoldowsky** [comment]
[jsxgraph+1.8.0.patch](https://github.com/user-attachments/files/15839859/jsxgraph%2B1.8.0.patch)

**Comment by alfredwassermann** [comment]
Thank you very much for your bug report and your patch.
I decided to apply an easier fix in `updateContainerDims` in `board.js` (line 4180 in branch develop).
Your report enabled us to find another regression in the code, so we have to do some more testing.

Thanks a lot!!!

**Comment by bgoldowsky** [comment]
Super!  Happy to test out a revised version when it's ready.
