### ISSUE TITLE
Arrowhead error

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#666]
Hello!

I have found a very specific bug, but it causes the setting of arrowheads in sketchometry to not work correctly.
The error occurs when the arrow type is changed several times, e.g. with:
```javascript
board.jc.parse('Sketcho00003.firstArrow = <<type: 1>>;');
board.jc.parse('Sketcho00003.firstArrow = <<type: 3>>;');
board.jc.parse('Sketcho00003.firstArrow = <<type: 1>>;');
board.jc.parse('Sketcho00003.firstArrow = false;');
```

If `JXG.Options.board.minimizeReflow = 'svg';` is also set, the arrowhead remains at the end of the code, although it should be switched off. The arrowhead is placed incorrectly.

Here is a minimal example: https://jsfiddle.net/andreas_walter/eo2aL950/

**Comment by andreas-web** [comment]
Thank you!

I just saw that `minimizeReflow: 'svg'` **seems** to be obsolete. Is that right? Do you recommend to use `'none'` in sketchometry instead?

**Comment by alfredwassermann** [comment]
Yes, it is obsolete. It seems that meanwhile the browser do a similar thing internally. Just ignore this attribute.
