### ISSUE TITLE
Integral attributes don't copy over

### ISSUE THREAD

**Issue by DylanHojnoski** [jsxgraph/jsxgraph#678]
On the integral element attributes for `curveLeft` and `curveRight` don't copy over to the actual element. When creating the integral element and defining attributes on it the `curveLeft` and `curveRight` do not get the attributes defined. However, changing `JXG.Option.integral.curveLeft` does change the attributes.

https://jsfiddle.net/tg4ynh0f/1/

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. Fortunately, this bug has been fixed last week in commit 22363d4e679f6461740f792660652ec1931516b5. If there is no last minute showstopper, v1.9.2 will be released in two days.
