### ISSUE TITLE
request:  Don't emit SPAN for empty label on 'input'

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#686]
Would it be possible to check the label on an 'input', and not emit the SPAN if it is empty?

I'm trying to use input to capture multiple answers (the X and Y of a point) but the user experience is not friendly.

It would make sense for the TAB key to move to the next input, but a span element for the label interferes, even if there is no label.

Here's some code to illustrate.  The top two inputs are what I want, and the bottom two expose the elements.

```
 <div id="jxgbox" class="jxgbox" style="width:1000px; height:1000px;float:left;"></div>

    <script>
        const board = JXG.JSXGraph.initBoard('jxgbox');

        let inp1 = board.create('input',[-4.5, 4.5, '', ''], { maxLength:1, fontSize: 26, cssStyle: 'width:15px;' })
        let inp2 = board.create('input',[-4.1, 4.5, '', ''], { maxLength:1, fontSize: 26, cssStyle: 'width:15px;' })

        let inp3 = board.create('input',[-4.5, 3.5, 'a', 'b'], { fontSize: 26, cssStyle: 'width:15px;' })
        let inp4 = board.create('input',[-4.1, 3.5, 'c', 'd'], { fontSize: 26, cssStyle: 'width:15px;' })

    </script>
```

It looks like this:

![2024-06-29_18-29](https://github.com/jsxgraph/jsxgraph/assets/11073753/9fb93533-ce7c-4418-ad47-22d57db104fe)

The TAB key stops at both labels and inputs, requiring the user to TAB twice to move from field to field.

The HTML created by JSXGraph looks like this, with the highlighted SPAN for the label.  The SPAN is added, even if the label is empty.

![2024-06-29_18-18](https://github.com/jsxgraph/jsxgraph/assets/11073753/18461d89-d48f-47a0-86eb-782a9216540b)

**Comment by alfredwassermann** [comment]
Indeed, this is a little bit annoying. However, my tests showed that it is not the span element that gets the focus, but the surrounding div element (which in your case is not "surrounding" anymore). 
This can be avoided by using the attribute `tabindex`:

```javascript
let inp1 = board.create('input', [-4.5, 4.5, '', ''], { tabindex:-1, maxLength: 1, fontSize: 26, cssStyle: 'width:15px;' });
```

**Comment by tom-berend** [comment]
Works like a charm, thanks.
