### ISSUE TITLE
Integral mono thin theme broken

### ISSUE THREAD

**Issue by DylanHojnoski** [jsxgraph/jsxgraph#687]
With the mono thin theme applied to the board the integral points and shading is still orange instead of being black.

https://jsfiddle.net/gbLkmzsa/

![screenshot-2024-07-08-21-55-27](https://github.com/jsxgraph/jsxgraph/assets/68570349/70b10c4a-1e22-4e49-af07-0cc667a97b4c)

**Comment by alfredwassermann** [comment]
Thanks for pointing this out!
