### ISSUE TITLE
Problem with dragging lines in 3D

### ISSUE THREAD

**Issue by amaurischat** [jsxgraph/jsxgraph#688]
When one tries to drag a line in 3D, it just vanishes.
(I am using version v1.9.2)

**Comment by alfredwassermann** [comment]
This problem seems to restricted to a special constellation and I can not reproduce it. Could you please provide a minimal example (jsfiddle or js code)?

**Comment by alfredwassermann** [comment]
If you send me a public link, I could test that page with chrome 89.

**Comment by amaurischat** [comment]
This is the javascript-code that I used:
```
<script type="text/javascript">
 var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox: [-10,10,10,-10], axis:false});
var bound = [-5, 5];
 var view = board.create('view3d',
     [[-5, -2],
      [8,8],
      [bound, bound, bound]],
     {

         xPlaneRear: { visible: false},
         yPlaneRear: { visible: false},
         zPlaneRear: { visible: false},

         zPlaneFrontXAxis: {visible: false},
         zPlaneFrontYAxis: {visible: false}, 

     });
     console.log('view', view);

		const A= view.create('point3d', [4,0,0], {visible: true});
		const B= view.create('point3d', [0,4,0], {visible: true});

		const line= view.create('line3d', [A,B], {fixed: false});
</script>
```

**Comment by amaurischat** [comment]
I also copied it to here: https://jsfiddle.net/qoyv1xe7/

If one drags one of the points A or B, it's fine. But dragging the line itself makes it vanish.

**Comment by alfredwassermann** [comment]
Thanks a lot. Indeed, direct 3D lines dragging is not yet implemented. That is, for the moment `fixed:false` has to be used.

This feature will come soon.
