### ISSUE TITLE
Turn off axis ticks using initBoard

### ISSUE THREAD

**Issue by georgekinnear** [jsxgraph/jsxgraph#691]
I'd like to turn off the axis ticks in a plot - still having the x and y axes drawn, but with no ticks or indication of scale.

If I create an axis object, I can do this using `ticks: {visible: false}` as suggested in the docs (https://jsxgraph.uni-bayreuth.de/docs/symbols/Axis.html#withTicks).

However this does not seem to work when applied in `initBoard` - the following code still produces ticks on the axes:
```
var board = JXG.JSXGraph.initBoard(BOARDID, {
    boundingbox: [-1, 5, 5, -1],
    axis: {ticks: {visible: false}}
});
```

Sorry if I have misunderstood something here, but this surprised me because here the docs say that the value for `axis` can be "Boolean or an object containing axis attributes" https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.Board.html#axis

Here is a jsfiddle showing both the `initBoard` and `board.create('axis' ...` versions behaving differently: https://jsfiddle.net/of81ad6u/

**Comment by alfredwassermann** [comment]
Indeed there is a slight inconsistency between attributes for the axis element and for the board. If you want to control the attributes of the default axes with board attributes, there is the attribute `defaultAxes`. Here is as an example the solution for your task:

```javascript
const board = JXG.JSXGraph.initBoard('jxgbox', { 
    boundingbox: [-5, 5, 5, -5], axis:true,
    defaultAxes: {
    	x: { ticks: {visible: false}},
    	y: { ticks: {visible: false}}
    }
});
```

See it live at https://jsfiddle.net/6zt3e9hy/.

Best wishes, Alfred

**Comment by georgekinnear** [comment]
That's great, thanks!
