### ISSUE TITLE
Transformed images are cropped

### ISSUE THREAD

**Issue by timkos** [jsxgraph/jsxgraph#695]
If images are transformed, they are cropped sometimes.

Example:
https://jsxgraph.org/wiki/index.php?title=Reflect_images

Click the right arrow three times to see the problem.
<img width="627" alt="Screenshot 2024-08-17 at 16 28 30" src="https://github.com/user-attachments/assets/a801daeb-b2c5-4dca-bd31-9b1b5c67f2e3">

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing this out. A fix has landed in the develop branch and will be available in the next release which will be published before the [JSXGraph conference](https://jsxgraph.org/conf2024/), 8.-10. October 2024.
