### ISSUE TITLE
please add  randomPareto() to statistics.js

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#702]
Hi, I'm playing with using JSXGraph to drive a simple simulator engine.  I was inspired by the new randomXX functions.  JSXGraph provides random number generators, histograms, and a graphics engine; it already does most of the hard work.

Would it be possible to add [randomPareto()](https://en.wikipedia.org/wiki/Pareto_distribution)  ?   Mostly I ask because Python's Numpy has a Pareto generator and it seems to appear in many models.    

Very low priority.   Thanks in advance.

**Comment by alfredwassermann** [comment]
Good suggestion. What do you suggest as parameters:

- gamma and k for the CDF $F(x) = 1 -(\frac{k}{x})^\gamma$ for $x\ge k$ or
- alpha and $x_m$ instead of gamma and k like in [Pareto_distribution](https://en.wikipedia.org/wiki/Pareto_distribution)?

**Comment by tom-berend** [comment]
I am likely the LAST person you should ask about details.  :)    My observation was only that the pareto distribution appears in many PySim models.  

JSXGraph statistics and graphics are a perfect tool for embedding Pareto Charts into web-based process reports.  A random generator would be helpful for development.

Here's what Numpy offers:

![image](https://github.com/user-attachments/assets/8019ec5f-3afb-473f-bbb9-d05f63a7eaf9)
