### ISSUE TITLE
Angle attribute 'name:' does not respect empty string

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#713]
The workaround is to use a single space as the name.  

```
        var board = JXG.JSXGraph.initBoard('jxgbox')

        let [p1, p2, p3] = [[0, 0], [4, 1], [2, 3]].map((initial) => board.create('point', initial))

        let li1 = board.create('segment', [p1, p2])
        let li2 = board.create('segment', [p1, p3])

        let a1 = board.create('angle', [li1, li2, 1, -1], { radius: 1, name: '' })  // fails
        let a2 = board.create('angle', [li1, li2, 1, -1], { radius: 2, name: ' ' }) // works
```

![image](https://github.com/user-attachments/assets/e64ea61e-d127-4341-8046-e37f7764777e)

**Comment by andreas-web** [comment]
But there is indeed a difference here:

If you set `withLabel: false, name: ''` for points, the name for the point is omitted.

If you do the same for angles, a name is still assigned to the angle. 

Example: https://jsfiddle.net/fokhdmj4/4/

I would not expect this behavior.
