### ISSUE TITLE
Histogram densith

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#715]
Hi, I was playing with randomPareto (THANK YOU!) and not getting the answers I wanted, so looked at histogram again...

Here's what I think is happening.  Some items in the long tail don't get added to the histogram - that's fine, they are off to the right beyond the graph.

But when we NORMALIZE the graph, we don't count them.  If 100 samples and 2 are off the graph, we normalize by 98.  I think we should still normalize by 100.   The extra 2 do NOT affect the cumulative, which is fine.

I would submit a PR, but don't see a DEV branch for 10.0 yet.  So here's how I propose to fix the code.

![image](https://github.com/user-attachments/assets/82a9d4dd-98f1-487e-bbab-f37cba590a36)

**Comment by alfredwassermann** [comment]
Thanks a lot! This is fixed now in 99e01acaccdcd86fb038436c8e12ce483ec9fec5. Also, the branch `develop`  has been updated to v.10.1dev.
