### ISSUE TITLE
Domain of a Glider

### ISSUE THREAD

**Issue by davidf628** [jsxgraph/jsxgraph#718]
Hello, this issue was presented in the recent JSXGraph conference by T Mzoughi in his demonstration on creating Physics questions in MyOpenMath with JSXGraph. The issue mentioned was that gliders should be bound to the domain of the function they are built upon. I found it odd, and assumed that there was something wrong with the library I created to connect JSXGraph with MyOpenMath, but when I looked into the issue, I started with a simple construction in JSFiddle and indeed, it does appear that gliders do not restrict themselves to the function's domain that they are connected to:

[https://jsfiddle.net/wkn86ujL/](https://jsfiddle.net/wkn86ujL/)

In this fiddle you can see that a glider built upon an object like a segment works as expected, as point B stays only on the object it is defined upon. However, point A, which is defined upon a functiongraph, is allowed to move beyond the domain of the graph. This behavior seems to be unexpected, and it seems like the default behavior should be to restrict the domains to the function. 

Can the gliders be changed so that they are restricted to the domain of the object they are connected to or is this the expected behavior and the user should write bounding code through an on('drag') function as I have shown (commented out) within the fiddle?

**Comment by alfredwassermann** [comment]
Indeed, this is an annoying error and it is a bit strange that it has not been reported before.  The good news are, meanwhile this problem is fixed by 5b712b76952bc96eec7bf09fcd95417bc9499361 (in branch `develop`).

We intend to fix a few other problems which were discussed at the conference and quickly release v1.10.1.

Best wishes,
Alfred
